<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cuotum extends CI_Controller{
    private $session_data = "";
    function __construct()
    {
        parent::__construct();
        $this->load->model('Cuotum_model');
        $this->load->model('Empresa_model');
        $this->load->model('Credito_model');
        $this->load->helper('numeros');  
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
    }
    /* *****Funcion que verifica el acceso al sistema**** */
    private function acceso($id_rol){
        $rolusuario = $this->session_data['rol'];
        if($rolusuario[$id_rol-1]['rolusuario_asignado'] == 1){
            return true;
        }else{
            $data['_view'] = 'login/mensajeacceso';
            $this->load->view('layouts/main',$data);
        }
    }
    /*
     * Listing of cuota
     */
    function index()
    {
        if($this->acceso(41)){
            $data['page_title'] = "Cuota";
            $usuario_id = $this->session_data['usuario_id'];
            $data['cuota'] = $this->Cuotum_model->get_all_cuota();

            $data['_view'] = 'cuotum/index';
            $this->load->view('layouts/main',$data);
        }
    }

    function deudas($credito_id)
    {
        if($this->acceso(42)){
            $data['page_title'] = "Cuota";
            $data['rol'] = $this->session_data['rol'];
            $data['cuota'] = $this->Cuotum_model->get_all_deuda($credito_id);
            $data['credito'] = $this->Credito_model->dato_deudas($credito_id);
            $data['_view'] = 'cuotum/deudas';
            $this->load->view('layouts/main',$data);
        }
    }

    function planDeuda($credito_id)
    {
        if($this->acceso(42)){
            $data['page_title'] = "Cuota";
            $data['empresa'] = $this->Empresa_model->get_empresa(1);
            $data['cuota'] = $this->Cuotum_model->get_all_deuda($credito_id);
            //$data['cuotum'] = $this->Cuotum_model->get_cuotum($cuota_id);
            $data['_view'] = 'cuotum/planDeudas';
            $this->load->view('layouts/main',$data);
        }
    }
    
    function cuentas($credito_id)
    {
        if($this->acceso(48)){
            $data['page_title'] = "Plan de pagos";
            $data['rol'] = $this->session_data['rol'];
            $data['cuota'] = $this->Cuotum_model->get_all_cuentas($credito_id);
            $data['credito'] = $this->Credito_model->dato_cuentas($credito_id);
            $data['_view'] = 'cuotum/cuentas';
            $this->load->view('layouts/main',$data);
        }
    }
    function cuenta_serv($credito_id)
    {
        if($this->acceso(47)){
            $data['page_title'] = "Cuota";
            $data['cuota'] = $this->Cuotum_model->get_all_cuenta_serv($credito_id);
            $data['credito'] = $this->Credito_model->dato_cuenta_serv($credito_id);
            $data['_view'] = 'cuotum/cuentas';
            $this->load->view('layouts/main',$data);
        }
    }
    function planCuenta($credito_id)
    {
        if($this->acceso(48)){
            $data['page_title'] = "Cuota";
            $data['empresa'] = $this->Empresa_model->get_empresa(1);
            $data['cuota'] = $this->Cuotum_model->get_all_cuentas($credito_id);
           // $data['cuotum'] = $this->Cuotum_model->get_cuotum($cuota_id);
            $data['_view'] = 'cuotum/planCuentas';
            $this->load->view('layouts/main',$data);
        }
    }
    function planCuentaServ($credito_id)
    {
        if($this->acceso(47)){
            $data['page_title'] = "Cuota";
            $data['empresa'] = $this->Empresa_model->get_empresa(1);
            $data['cuota'] = $this->Cuotum_model->get_all_cuenta_serv($credito_id);
           // $data['cuotum'] = $this->Cuotum_model->get_cuotum($cuota_id);
            $data['_view'] = 'cuotum/planCuentas';
            $this->load->view('layouts/main',$data);
        }
    }
    function recibodeudas($cuota_id)
    {
        if($this->acceso(41)){
            $data['page_title'] = "Cuota";
            $data['cuota'] = $this->Cuotum_model->get_recibo_deuda($cuota_id);
           // $data['cuotum'] = $this->Cuotum_model->get_cuotum($cuota_id);
            $data['_view'] = 'cuotum/reciboDeuda';
            $this->load->view('layouts/main',$data);
        }
    }
     function recibocuentas($cuota_id)
    {
         if($this->acceso(47)){
            $data['page_title'] = "Comprobante";
            $data['cuota'] = $this->Cuotum_model->get_recibo_cuenta($cuota_id);
           // $data['cuotum'] = $this->Cuotum_model->get_cuotum($cuota_id);
            $data['_view'] = 'cuotum/reciboCuenta';
            $this->load->view('layouts/main',$data);
        }
    }

   function recibocuentaserv($cuota_id)
    {
       if($this->acceso(47)){
           $data['page_title'] = "Cuota";
            $data['cuota'] = $this->Cuotum_model->get_recibo_cuentaServ($cuota_id);
           // $data['cuotum'] = $this->Cuotum_model->get_cuotum($cuota_id);
            $data['_view'] = 'cuotum/reciboCuenta';
            $this->load->view('layouts/main',$data);
        }
    }
    function comprobantedeudas($cuota_id,$credito_id)
    {
        if($this->acceso(41)){
            $data['page_title'] = "Cuota";
            $data['cuota'] = $this->Cuotum_model->get_recibo_deuda($cuota_id);
            $data['empresa'] = $this->Empresa_model->get_empresa(1);
            $data['credito'] = $this->Cuotum_model->get_all_deuda($credito_id);
            $data['_view'] = 'cuotum/comprobanteDeuda';
            $this->load->view('layouts/main',$data);
        }
    }
    function comprobantecuentas($cuota_id,$credito_id)
    {
        if($this->acceso(47)){
            $data['page_title'] = "Cuota";
            $data['cuota'] = $this->Cuotum_model->get_recibo_cuenta($cuota_id);
            $data['empresa'] = $this->Empresa_model->get_empresa(1);
            $data['credito'] = $this->Cuotum_model->get_all_cuentas($credito_id);
            $data['_view'] = 'cuotum/comprobanteCuenta';
            $this->load->view('layouts/main',$data);
        }
    }

    function notacobro($cuota_id,$credito_id)
    {
        if($this->acceso(41) or $this->acceso(47)){
            $data['page_title'] = "Cuota";
            $data['cuota'] = $this->Cuotum_model->get_recibo_cuenta($cuota_id);
            $data['empresa'] = $this->Empresa_model->get_empresa(1);
            $data['credito'] = $this->Cuotum_model->get_all_cuentas($credito_id);
            $data['_view'] = 'cuotum/notaCobro';
            $this->load->view('layouts/main',$data);
        }
    }

    function comprobantecuentaserv($cuota_id,$credito_id)
    {
        if($this->acceso(47)){
            $data['page_title'] = "Cuota";
            $data['cuota'] = $this->Cuotum_model->get_recibo_cuentaServ($cuota_id);
            $data['empresa'] = $this->Empresa_model->get_empresa(1);
            $data['credito'] = $this->Cuotum_model->get_all_cuentas($credito_id);
            $data['_view'] = 'cuotum/comprobanteCuenta';
            $this->load->view('layouts/main',$data);
        }
    }
    function pagar($cuota_id)
    {
        if($this->acceso(41)){
            $data['page_title'] = "Cuota";
            $usuario_id = $this->session_data['usuario_id'];
            $data['cuota'] = $this->Cuotum_model->get_cuotum($cuota_id);
           //  $data['cuota'] = $this->Cuotum_model->get_all_deuda($credito_id);
            $estado_id = 8;
            $cuota_id = $this->input->post('cuota_id');
            $num = $this->Cuotum_model->numero();
            $maximo = $num[0]['parametro_montomax'];
            $interes = $num[0]['parametro_interes'];
            $credito_id = $this->input->post('credito_id');
            $credito_tipointeres = $this->input->post('credito_tipointeres');
            $cuota_capital = $this->input->post('cuota_capital');

  $si_orden=$this->input->post('cuota_ordenpago');     
   if ($si_orden==1 ) {
     $this->load->model('Orden_pago_model');
      $nodoc=$this->input->post('cuota_numercibo');
      $orden_fecha = "'".date("Y-m-d")."'"; 
      $orden_hora = "'".date("H:i:s")."'"; 
      $compra_prove=$this->Cuotum_model->get_all_deuda($credito_id);
      $proveedor_nombre = $compra_prove[0]['proveedor_nombre'];
      $orden_monto = $this->input->post('cuota_cancelado');
      $orden_motivo = "'pago de cuota a proveedor No. ".$cuota_id."/credito".$credito_id."  documento No. ".$nodoc." '";
      $comprita = 0;
      $orden = "insert into orden_pago(usuario_id1,usuario_id2,orden_monto,orden_destinatario,orden_motivo,orden_fecha,orden_hora,estado_id,orden_cancelado,compra_id,cuota_id) "
                    . "value(".$usuario_id.",0".",".$orden_monto.",'".$proveedor_nombre."',".$orden_motivo.",".$orden_fecha.",".$orden_hora.",8,0,".$comprita.",".$cuota_id.")";
            //echo $sql;
           $this->Orden_pago_model->registrar_orden($orden);
   }
        if($cuota_capital==0){
         $params = array(
                    
                    'usuario_id' => $usuario_id,
                    'estado_id' => $this->input->post('estado_id'),
                   // 'cuota_numcuota' => $this->input->post('cuota_numcuota'),
                    //'cuota_capital' => $this->input->post('cuota_capital'),
                    //'cuota_interes' => $this->input->post('cuota_interes'),
                    //'cuota_moradias' => $this->input->post('cuota_moradias'),
                    //'cuota_multa' => $this->input->post('cuota_multa'),
                   // 'cuota_subtotal' => $this->input->post('cuota_subtotal'),
                   // 'cuota_descuento' => $this->input->post('cuota_descuento'),
                    //'cuota_total' => $this->input->post('cuota_total'),
                   // 'cuota_fechalimite' => $this->input->post('cuota_fechalimite'),
                    'cuota_cancelado' => $this->input->post('cuota_cancelado'),
                    'cuota_fecha' => $this->input->post('cuota_fecha'),
                    'cuota_hora' => $this->input->post('cuota_hora'),
                    'cuota_numercibo' => $this->input->post('cuota_numercibo'),
                   // 'cuota_saldo' => $this->input->post('cuota_saldo'),
                    'cuota_glosa' => $this->input->post('cuota_glosa'),
                    'cuota_ordenpago' => $this->input->post('cuota_ordenpago'),
                );


                $this->Cuotum_model->update_cuotum($cuota_id,$params); 
                 }   
             else{
                 $params = array(
                    
                        'usuario_id' => $usuario_id,
                    'estado_id' => $this->input->post('estado_id'),
                   // 'cuota_numcuota' => $this->input->post('cuota_numcuota'),
                    //'cuota_capital' => $this->input->post('cuota_capital'),
                    //'cuota_interes' => $this->input->post('cuota_interes'),
                    //'cuota_moradias' => $this->input->post('cuota_moradias'),
                    //'cuota_multa' => $this->input->post('cuota_multa'),
                   // 'cuota_subtotal' => $this->input->post('cuota_subtotal'),
                   // 'cuota_descuento' => $this->input->post('cuota_descuento'),
                    //'cuota_total' => $this->input->post('cuota_total'),
                   // 'cuota_fechalimite' => $this->input->post('cuota_fechalimite'),
                    'cuota_cancelado' => $this->input->post('cuota_cancelado'),
                    'cuota_fecha' => $this->input->post('cuota_fecha'),
                    //'cuota_hora' => $this->input->post('cuota_hora'),
                    'cuota_numercibo' => $this->input->post('cuota_numercibo'),
                   // 'cuota_saldo' => $this->input->post('cuota_saldo'),
                    'cuota_glosa' => $this->input->post('cuota_glosa'),
                    'cuota_ordenpago' => $this->input->post('cuota_ordenpago'),
                );


                $this->Cuotum_model->update_cuotum($cuota_id,$params); 
                 $dias_mora = 0;
                    $multa = 0;
                    $descuento = 0;
                    $cancelado = 0;
                    $credito_fecha = $this->input->post('cuota_fecha');
                    $credito_hora = "'".date('H:i:s')."'";
                    $fechalimite  = $this->input->post('cuota_fechalimite');
                    $credito_fechalimite = "'".$fechalimite."'";
                    $cuota_cancelado = $this->input->post('cuota_cancelado');
           
              if ($credito_tipointeres==1){
                 $cuota_capital = $this->input->post('cuota_capital');
                 $reinteres = $this->input->post('cuota_interes');
                 $capital = $this->input->post('cuota_total');
                 $saldo = $this->input->post('cuota_saldo');
             $fijo = ($cuota_capital * $reinteres)/$capital;
             $cuota_subtotal = $fijo + $cuota_capital + $dias_mora + $multa;

            
                $total =  $cuota_subtotal - $descuento;
              $saldo_deudor = $saldo - $cuota_cancelado + $reinteres;

                $cuota_numcuota = $this->input->post('cuota_numcuota');
                
                  $cuota ="INSERT INTO cuota (credito_id,usuario_id,estado_id,cuota_numcuota,cuota_capital,cuota_interes,cuota_moradias,cuota_multa,cuota_descuento,cuota_cancelado,cuota_total,cuota_subtotal,cuota_fechalimite,cuota_fecha,cuota_saldo,cuota_hora) VALUES (".$credito_id.",".$usuario_id.",".$estado_id.",".$cuota_numcuota.",".$cuota_capital.",".$fijo.",".$dias_mora.",".$multa.",".$descuento.",".$cancelado.",".$total.",".$cuota_subtotal.",".$credito_fechalimite.",".$credito_fecha.",".$saldo_deudor.",".$credito_hora.")";
                $this->db->query($cuota);
  
               
               
              }
                else{
                     $cuota_capital = $this->input->post('cuota_capital');
                    $reinteres = $this->input->post('cuota_interes');
                     $saldo = $this->input->post('cuota_saldo');
                     $saldo_deudor = $saldo - $cuota_cancelado + $reinteres;
                    
            
              
                $variable = $saldo_deudor * ($interes/100);
                $cuota_subtotal = $variable + $cuota_capital + $dias_mora + $multa;
                $cuota_numcuota = $this->input->post('cuota_numcuota');
                $total =  $cuota_subtotal - $descuento;

                 $cuota ="INSERT INTO cuota (credito_id,usuario_id,estado_id,cuota_numcuota,cuota_capital,cuota_interes,cuota_moradias,cuota_multa,cuota_descuento,cuota_cancelado,cuota_total,cuota_subtotal,cuota_fechalimite,cuota_fecha,cuota_saldo,cuota_hora) VALUES (".$credito_id.",".$usuario_id.",".$estado_id.",".$cuota_numcuota.",".$cuota_capital.",".$variable.",".$dias_mora.",".$multa.",".$descuento.",".$cancelado.",".$total.",".$cuota_subtotal.",".$credito_fechalimite.",".$credito_fecha.",".$saldo_deudor.",".$credito_hora.")";
                $this->db->query($cuota);
               
              
                }

            }
    /*} else {
        if ($credito_monto > $maximo){
            $cuota_capital = $credito_monto/$numcuota;
             $fijo = $patron * $credito_monto * ($interes/100/$numcuota);
             $cuota_subtotal = $fijo + $cuota_capital + $dias_mora + $multa;;
             $total = $cuota_subtotal - $descuento;
                $saldo_deudor = $cuota_total;
            
                 $siguiente= 0;
                for ($i=1; $i <= $numcuota; $i++) { 

                $cuota_numcuota = $i;
                $proximo_martes2 = time() + ( ($diasgra+$siguiente-($nroDia-$diapago)) * 24 * 60 * 60 );
                               $credito_fechalimite = "'".date('Y-m-d', $proximo_martes2)."'";
                $cuota ="INSERT INTO cuota (credito_id,usuario_id,estado_id,cuota_numcuota,cuota_capital,cuota_interes,cuota_moradias,cuota_multa,cuota_descuento,cuota_cancelado,cuota_total,cuota_subtotal,cuota_fechalimite,cuota_fecha,cuota_saldo,cuota_hora) VALUES (".$credito_id.",".$usuario_id.",".$estado_id.",".$cuota_numcuota.",".$cuota_capital.",".$fijo.",".$dias_mora.",".$multa.",".$descuento.",".$cancelado.",".$total.",".$cuota_subtotal.",".$credito_fechalimite.",".$credito_fecha.",".$saldo_deudor.",".$credito_hora.")";
                $this->db->query($cuota);
                $siguiente = $siguiente+$periodo;
                $saldo_deudor = $cuota_total - $cuota_capital;
                $cuota_total = $saldo_deudor;
                }
             }
             else{
                $numcuota = 1;
                 $cuota_capital = $credito_monto/$numcuota;
             $fijo = $patron * $credito_monto * ($interes/100/$numcuota);
             $cuota_subtotal = $fijo + $cuota_capital + $dias_mora + $multa;;
             $total = $cuota_subtotal - $descuento;
                $saldo_deudor = $cuota_total;
            
                 $siguiente= 0;
                for ($i=1; $i <= $numcuota; $i++) { 

                $cuota_numcuota = $i;
                $proximo_martes2 = time() + ( ($diasgra+$siguiente-($nroDia-$diapago)) * 24 * 60 * 60 );
                               $credito_fechalimite = "'".date('Y-m-d', $proximo_martes2)."'";
                   $cuota ="INSERT INTO cuota (credito_id,usuario_id,estado_id,cuota_numcuota,cuota_capital,cuota_interes,cuota_moradias,cuota_multa,cuota_descuento,cuota_cancelado,cuota_total,cuota_subtotal,cuota_fechalimite,cuota_fecha,cuota_saldo,cuota_hora) VALUES (".$credito_id.",".$usuario_id.",".$estado_id.",".$cuota_numcuota.",".$cuota_capital.",".$fijo.",".$dias_mora.",".$multa.",".$descuento.",".$cancelado.",".$total.",".$cuota_subtotal.",".$credito_fechalimite.",".$credito_fecha.",".$saldo_deudor.",".$credito_hora.")";
                $this->db->query($cuota);
                $siguiente = $siguiente+$periodo;
                $saldo_deudor = $cuota_total - $cuota_capital;
                $cuota_total = $saldo_deudor;
             }
         }*/
            
            $credis = "SELECT COUNT(cuota_id) as 'creditango' FROM cuota  WHERE cuota.credito_id = ".$credito_id;
            $credingo = $this->db->query($credis)->result_array();
            $cuotis = "SELECT COUNT(cuota_id) as 'cuotanga' FROM cuota  WHERE cuota.estado_id = 9 and cuota.credito_id = ".$credito_id;
            $cuotinga = $this->db->query($cuotis)->result_array();
            
            


            if($cuotinga[0]['cuotanga'] == $credingo[0]['creditango']){
            $actualizar = "UPDATE credito SET credito.estado_id=9 WHERE credito.credito_id=".$credito_id;
            $this->db->query($actualizar);
            }


                 redirect('cuotum/deudas/'.$credito_id);  

            }
    }
    
    function cobrar($cuota_id)
    {
        if($this->acceso(47)){
            $usuario_id = $this->session_data['usuario_id'];
        $data['cuota'] = $this->Cuotum_model->get_cuotum($cuota_id);
       //  $data['cuota'] = $this->Cuotum_model->get_all_deuda($credito_id);
      
        $estado_id = 8;
        $cuota_id = $this->input->post('cuota_id');
         $num = $this->Cuotum_model->numero();
          $maximo = $num[0]['parametro_montomax'];
          $interes = $num[0]['parametro_interes'];
        $credito_id = $this->input->post('credito_id');
        $credito_tipointeres = $this->input->post('credito_tipointeres');
        $cuota_capital = $this->input->post('cuota_capital');

        if($cuota_capital==0){
         $params = array(
                    
                    'usuario_id' => $usuario_id,
                    'estado_id' => $this->input->post('estado_id'),
                   // 'cuota_numcuota' => $this->input->post('cuota_numcuota'),
                    //'cuota_capital' => $this->input->post('cuota_capital'),
                    //'cuota_interes' => $this->input->post('cuota_interes'),
                    //'cuota_moradias' => $this->input->post('cuota_moradias'),
                    //'cuota_multa' => $this->input->post('cuota_multa'),
                   // 'cuota_subtotal' => $this->input->post('cuota_subtotal'),
                   // 'cuota_descuento' => $this->input->post('cuota_descuento'),
                    //'cuota_total' => $this->input->post('cuota_total'),
                   // 'cuota_fechalimite' => $this->input->post('cuota_fechalimite'),
                    'cuota_cancelado' => $this->input->post('cuota_cancelado'),
                    'cuota_fecha' => $this->input->post('cuota_fecha'),
                    'cuota_hora' => date('H:i:s'),
                    'cuota_numercibo' => $this->input->post('cuota_numercibo'),
                   // 'cuota_saldo' => $this->input->post('cuota_saldo'),
                    'cuota_glosa' => $this->input->post('cuota_glosa'),
                );


                $this->Cuotum_model->update_cuotum($cuota_id,$params); 
                 }   
             else{
                 $params = array(
                    
                   'usuario_id' => $usuario_id,
                    'estado_id' => $this->input->post('estado_id'),
                   // 'cuota_numcuota' => $this->input->post('cuota_numcuota'),
                    //'cuota_capital' => $this->input->post('cuota_capital'),
                    //'cuota_interes' => $this->input->post('cuota_interes'),
                    //'cuota_moradias' => $this->input->post('cuota_moradias'),
                    //'cuota_multa' => $this->input->post('cuota_multa'),
                   // 'cuota_subtotal' => $this->input->post('cuota_subtotal'),
                   // 'cuota_descuento' => $this->input->post('cuota_descuento'),
                    //'cuota_total' => $this->input->post('cuota_total'),
                   // 'cuota_fechalimite' => $this->input->post('cuota_fechalimite'),
                    'cuota_cancelado' => $this->input->post('cuota_cancelado'),
                    'cuota_fecha' => $this->input->post('cuota_fecha'),
                    'cuota_hora' => date('H:i:s'),
                    'cuota_numercibo' => $this->input->post('cuota_numercibo'),
                   // 'cuota_saldo' => $this->input->post('cuota_saldo'),
                    'cuota_glosa' => $this->input->post('cuota_glosa'),
                );


                $this->Cuotum_model->update_cuotum($cuota_id,$params); 
                 $dias_mora = 0;
                    $multa = 0;
                    $descuento = 0;
                    $cancelado = 0;
                    $credito_fecha = "'".date('d-m-Y')."'";
                    $credito_hora = "'".date('H:i:s')."'";
                    $fechalimite  = $this->input->post('cuota_fechalimite');
                    $credito_fechalimite = "'".$fechalimite."'";
                    $cuota_cancelado = $this->input->post('cuota_cancelado');
           
              if ($credito_tipointeres==1){
                 $cuota_capital = $this->input->post('cuota_capital');
                 $reinteres = $this->input->post('cuota_interes');
                 $capital = $this->input->post('cuota_total');
                 $saldo = $this->input->post('cuota_saldo');
             $fijo = ($cuota_capital * $reinteres)/$capital;
             $cuota_subtotal = $fijo + $cuota_capital + $dias_mora + $multa;

            
                $total =  $cuota_subtotal - $descuento;
              $saldo_deudor = $saldo - $cuota_cancelado + $reinteres;

                $cuota_numcuota = $this->input->post('cuota_numcuota');
                
                  $cuota ="INSERT INTO cuota (credito_id,usuario_id,estado_id,cuota_numcuota,cuota_capital,cuota_interes,cuota_moradias,cuota_multa,cuota_descuento,cuota_cancelado,cuota_total,cuota_subtotal,cuota_fechalimite,cuota_fecha,cuota_saldo,cuota_hora) VALUES (".$credito_id.",".$usuario_id.",".$estado_id.",".$cuota_numcuota.",".$cuota_capital.",".$fijo.",".$dias_mora.",".$multa.",".$descuento.",".$cancelado.",".$total.",".$cuota_subtotal.",".$credito_fechalimite.",".$credito_fecha.",".$saldo_deudor.",".$credito_hora.")";
                $this->db->query($cuota);
  
               
               
              }
                else{
                     $cuota_capital = $this->input->post('cuota_capital');
                    $reinteres = $this->input->post('cuota_interes');
                     $saldo = $this->input->post('cuota_saldo');
                     $saldo_deudor = $saldo - $cuota_cancelado + $reinteres;
                    
            
              
                $variable = $saldo_deudor * ($interes/100);
                $cuota_subtotal = $variable + $cuota_capital + $dias_mora + $multa;
                $cuota_numcuota = $this->input->post('cuota_numcuota');
                $total =  $cuota_subtotal - $descuento;

                 $cuota ="INSERT INTO cuota (credito_id,usuario_id,estado_id,cuota_numcuota,cuota_capital,cuota_interes,cuota_moradias,cuota_multa,cuota_descuento,cuota_cancelado,cuota_total,cuota_subtotal,cuota_fechalimite,cuota_fecha,cuota_saldo,cuota_hora) VALUES (".$credito_id.",".$usuario_id.",".$estado_id.",".$cuota_numcuota.",".$cuota_capital.",".$variable.",".$dias_mora.",".$multa.",".$descuento.",".$cancelado.",".$total.",".$cuota_subtotal.",".$credito_fechalimite.",".$credito_fecha.",".$saldo_deudor.",".$credito_hora.")";
                $this->db->query($cuota);
               
              
                }
            }
    /*} else {
        if ($credito_monto > $maximo){
            $cuota_capital = $credito_monto/$numcuota;
             $fijo = $patron * $credito_monto * ($interes/100/$numcuota);
             $cuota_subtotal = $fijo + $cuota_capital + $dias_mora + $multa;;
             $total = $cuota_subtotal - $descuento;
                $saldo_deudor = $cuota_total;
            
                 $siguiente= 0;
                for ($i=1; $i <= $numcuota; $i++) { 

                $cuota_numcuota = $i;
                $proximo_martes2 = time() + ( ($diasgra+$siguiente-($nroDia-$diapago)) * 24 * 60 * 60 );
                               $credito_fechalimite = "'".date('Y-m-d', $proximo_martes2)."'";
                $cuota ="INSERT INTO cuota (credito_id,usuario_id,estado_id,cuota_numcuota,cuota_capital,cuota_interes,cuota_moradias,cuota_multa,cuota_descuento,cuota_cancelado,cuota_total,cuota_subtotal,cuota_fechalimite,cuota_fecha,cuota_saldo,cuota_hora) VALUES (".$credito_id.",".$usuario_id.",".$estado_id.",".$cuota_numcuota.",".$cuota_capital.",".$fijo.",".$dias_mora.",".$multa.",".$descuento.",".$cancelado.",".$total.",".$cuota_subtotal.",".$credito_fechalimite.",".$credito_fecha.",".$saldo_deudor.",".$credito_hora.")";
                $this->db->query($cuota);
                $siguiente = $siguiente+$periodo;
                $saldo_deudor = $cuota_total - $cuota_capital;
                $cuota_total = $saldo_deudor;
                }
             }
             else{
                $numcuota = 1;
                 $cuota_capital = $credito_monto/$numcuota;
             $fijo = $patron * $credito_monto * ($interes/100/$numcuota);
             $cuota_subtotal = $fijo + $cuota_capital + $dias_mora + $multa;;
             $total = $cuota_subtotal - $descuento;
                $saldo_deudor = $cuota_total;
            
                 $siguiente= 0;
                for ($i=1; $i <= $numcuota; $i++) { 

                $cuota_numcuota = $i;
                $proximo_martes2 = time() + ( ($diasgra+$siguiente-($nroDia-$diapago)) * 24 * 60 * 60 );
                               $credito_fechalimite = "'".date('Y-m-d', $proximo_martes2)."'";
                   $cuota ="INSERT INTO cuota (credito_id,usuario_id,estado_id,cuota_numcuota,cuota_capital,cuota_interes,cuota_moradias,cuota_multa,cuota_descuento,cuota_cancelado,cuota_total,cuota_subtotal,cuota_fechalimite,cuota_fecha,cuota_saldo,cuota_hora) VALUES (".$credito_id.",".$usuario_id.",".$estado_id.",".$cuota_numcuota.",".$cuota_capital.",".$fijo.",".$dias_mora.",".$multa.",".$descuento.",".$cancelado.",".$total.",".$cuota_subtotal.",".$credito_fechalimite.",".$credito_fecha.",".$saldo_deudor.",".$credito_hora.")";
                $this->db->query($cuota);
                $siguiente = $siguiente+$periodo;
                $saldo_deudor = $cuota_total - $cuota_capital;
                $cuota_total = $saldo_deudor;
             }
         }*/

           $credis = "SELECT COUNT(cuota_id) as 'creditango' FROM cuota  WHERE cuota.credito_id = ".$credito_id;
            $credingo = $this->db->query($credis)->result_array();
            $cuotis = "SELECT COUNT(cuota_id) as 'cuotanga' FROM cuota  WHERE cuota.estado_id = 9 and cuota.credito_id = ".$credito_id;
            $cuotinga = $this->db->query($cuotis)->result_array();
           
            


           if($cuotinga[0]['cuotanga'] == $credingo[0]['creditango']){
            $actualizar = "UPDATE credito SET credito.estado_id=9 WHERE credito.credito_id=".$credito_id;
            $this->db->query($actualizar);
            }

              $servi="SELECT servicio_id as 'servico' FROM credito WHERE credito_id=".$credito_id." ";
              $servic=$this->db->query($servi)->result_array();
              if ($servic[0]['servico']!=0) {
                 redirect('cuotum/cuenta_serv/'.$credito_id);
               } else {
                redirect('cuotum/cuentas/'.$credito_id);  
                }
            }
    }

    function pendiente($cuota_id,$credito_id,$numcuota)
    {
        if($this->acceso(41)){
            $usuario_id = $this->session_data['usuario_id'];
            
            $sql = "UPDATE cuota SET estado_id=8,cuota_cancelado=0,cuota_fecha='0000-00-00' WHERE cuota.cuota_id=".$cuota_id." ";
            $this->db->query($sql);
            $ptq="DELETE FROM cuota WHERE cuota.cuota_numcuota = ".$numcuota." and cuota_id > ".$cuota_id." and cuota.credito_id=".$credito_id." and cuota.estado_id=8 ";
            $this->db->query($ptq);
            $credis = "SELECT COUNT(cuota_id) as 'creditango' FROM cuota  WHERE cuota.credito_id = ".$credito_id;
            $credingo = $this->db->query($credis)->result_array();
            $cuotis = "SELECT COUNT(cuota_id) as 'cuotanga' FROM cuota  WHERE cuota.estado_id = 9 and cuota.credito_id = ".$credito_id;
            $cuotinga = $this->db->query($cuotis)->result_array();
            
            


            if($cuotinga[0]['cuotanga'] != $credingo[0]['creditango']){
            $actualizar = "UPDATE credito SET credito.estado_id=8 WHERE credito.credito_id=".$credito_id;
            $this->db->query($actualizar);
            }

            redirect('cuotum/deudas/'.$credito_id);
        }
    }

    function pendiente1($cuota_id,$credito_id,$numcuota)
    {
        if($this->acceso(47)){
            $usuario_id = $this->session_data['usuario_id'];
            
            $sql = "UPDATE cuota SET estado_id=8,cuota_cancelado=0,cuota_fecha='0000-00-00' WHERE cuota.cuota_id=".$cuota_id." ";
            $this->db->query($sql);
            $ptq="DELETE FROM cuota WHERE cuota.cuota_numcuota = ".$numcuota." and cuota_id > ".$cuota_id." and cuota.credito_id=".$credito_id." and cuota.estado_id=8 ";
            $this->db->query($ptq);
             $credis = "SELECT COUNT(cuota_id) as 'creditango' FROM cuota  WHERE cuota.credito_id = ".$credito_id;
            $credingo = $this->db->query($credis)->result_array();
            $cuotis = "SELECT COUNT(cuota_id) as 'cuotanga' FROM cuota  WHERE cuota.estado_id = 9 and cuota.credito_id = ".$credito_id;
            $cuotinga = $this->db->query($cuotis)->result_array();
            
            


            if($cuotinga[0]['cuotanga'] != $credingo[0]['creditango']){
            $actualizar = "UPDATE credito SET credito.estado_id=8 WHERE credito.credito_id=".$credito_id;
            $this->db->query($actualizar);
            }
           $servi="SELECT servicio_id as 'servico' FROM credito WHERE credito_id=".$credito_id." ";
              $servic=$this->db->query($servi)->result_array();
              if ($servic[0]['servico']!=0) {
                 redirect('cuotum/cuenta_serv/'.$credito_id);
               } else {
                redirect('cuotum/cuentas/'.$credito_id);  
                } 
        }
    }


    function add()
    {
        if($this->acceso(41) or $this->acceso(47)){
            $data['page_title'] = "Cuota";
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'credito_id' => $this->input->post('credito_id'),
				'usuario_id' => $this->input->post('usuario_id'),
				'estado_id' => $this->input->post('estado_id'),
				'cuota_numcuota' => $this->input->post('cuota_numcuota'),
				'cuota_capital' => $this->input->post('cuota_capital'),
				'cuota_interes' => $this->input->post('cuota_interes'),
				'cuota_moradias' => $this->input->post('cuota_moradias'),
				'cuota_multa' => $this->input->post('cuota_multa'),
				'cuota_subtotal' => $this->input->post('cuota_subtotal'),
				'cuota_descuento' => $this->input->post('cuota_descuento'),
				'cuota_total' => $this->input->post('cuota_total'),
				'cuota_fechalimite' => $this->input->post('cuota_fechalimite'),
				'cuota_cancelado' => $this->input->post('cuota_cancelado'),
				'cuota_fecha' => $this->input->post('cuota_fecha'),
				'cuota_hora' => $this->input->post('cuota_hora'),
				'cuota_numercibo' => $this->input->post('cuota_numercibo'),
				'cuota_saldo' => $this->input->post('cuota_saldo'),
				'cuota_glosa' => $this->input->post('cuota_glosa'),
            );
            
            $cuotum_id = $this->Cuotum_model->add_cuotum($params);
            redirect('cuotum/index');
        }
        else
        {
			$this->load->model('Credito_model');
			$data['all_credito'] = $this->Credito_model->get_all_credito();

			$this->load->model('Usuario_model');
			$data['all_usuario'] = $this->Usuario_model->get_all_usuario();

			$this->load->model('Estado_model');
			$data['all_estado'] = $this->Estado_model->get_all_estado();
            
            $data['_view'] = 'cuotum/add';
            $this->load->view('layouts/main',$data);
        }
        }
    }  
    /*
     * Adding a new cuotum
     */
   
    /*
     * Editing a cuotum
     */
    function edit($cuota_id)
    {
        if($this->acceso(41)){
            $data['page_title'] = "Cuota";
            $usuario_id = $this->session_data['usuario_id'];
        // check if the cuotum exists before trying to edit it
        $data['cuotum'] = $this->Cuotum_model->get_cuotum($cuota_id);
        $credito_id = $this->input->post('credito_id');
        if(isset($data['cuotum']['cuota_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'credito_id' => $this->input->post('credito_id'),
					'usuario_id' => $usuario_id,
					'estado_id' => 8,
					'cuota_numcuota' => $this->input->post('cuota_numcuota'),
					'cuota_capital' => $this->input->post('cuota_capital'),
					'cuota_interes' => $this->input->post('cuota_interes'),
					'cuota_moradias' => $this->input->post('cuota_moradias'),
					'cuota_multa' => $this->input->post('cuota_multa'),
					'cuota_subtotal' => $this->input->post('cuota_subtotal'),
					'cuota_descuento' => $this->input->post('cuota_descuento'),
					'cuota_total' => $this->input->post('cuota_total'),
					'cuota_fechalimite' => $this->input->post('cuota_fechalimite'),
					'cuota_cancelado' => $this->input->post('cuota_cancelado'),
					//'cuota_fecha' =>  date('Y-m-d'),
					//'cuota_hora' => date('H:i:s'),
					'cuota_numercibo' => $this->input->post('cuota_numercibo'),
					'cuota_saldo' => $this->input->post('cuota_saldo'),
					'cuota_glosa' => $this->input->post('cuota_glosa'),
                );

                $this->Cuotum_model->update_cuotum($cuota_id,$params);            
                redirect('cuotum/deudas/'.$credito_id); 
            }
            else
            {
				$this->load->model('Credito_model');
				$data['all_credito'] = $this->Credito_model->get_all_credito();

				$this->load->model('Usuario_model');
				$data['all_usuario'] = $this->Usuario_model->get_all_usuario();

				$this->load->model('Estado_model');
				$data['all_estado'] = $this->Estado_model->get_all_estado();

                $data['_view'] = 'cuotum/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The cuotum you are trying to edit does not exist.');
    }
    }
    
     function editar($cuota_id)
    {
        if($this->acceso(47)){
             $data['page_title'] = "Cuota";
            $usuario_id = $this->session_data['usuario_id'];
     
        // check if the cuotum exists before trying to edit it
        $data['cuotum'] = $this->Cuotum_model->get_cuotum($cuota_id);
        $credito_id = $this->input->post('credito_id');
        if(isset($data['cuotum']['cuota_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                    'credito_id' => $this->input->post('credito_id'),
                    'usuario_id' => $usuario_id,
                    'estado_id' => 8,
                    'cuota_numcuota' => $this->input->post('cuota_numcuota'),
                    'cuota_capital' => $this->input->post('cuota_capital'),
                    'cuota_interes' => $this->input->post('cuota_interes'),
                    'cuota_moradias' => $this->input->post('cuota_moradias'),
                    'cuota_multa' => $this->input->post('cuota_multa'),
                    'cuota_subtotal' => $this->input->post('cuota_subtotal'),
                    'cuota_descuento' => $this->input->post('cuota_descuento'),
                    'cuota_total' => $this->input->post('cuota_total'),
                    'cuota_fechalimite' => $this->input->post('cuota_fechalimite'),
                    'cuota_cancelado' => $this->input->post('cuota_cancelado'),
                    //'cuota_fecha' =>  date('Y-m-d'),
                    //'cuota_hora' => date('H:i:s'),
                    'cuota_numercibo' => $this->input->post('cuota_numercibo'),
                    'cuota_saldo' => $this->input->post('cuota_saldo'),
                    'cuota_glosa' => $this->input->post('cuota_glosa'),
                );

                $this->Cuotum_model->update_cuotum($cuota_id,$params);            
                redirect('cuotum/cuentas/'.$credito_id); 
            }
            else
            {
                $this->load->model('Credito_model');
                $data['all_credito'] = $this->Credito_model->get_all_credito();

                $this->load->model('Usuario_model');
                $data['all_usuario'] = $this->Usuario_model->get_all_usuario();

                $this->load->model('Estado_model');
                $data['all_estado'] = $this->Estado_model->get_all_estado();

                $data['_view'] = 'cuotum/editar';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The cuotum you are trying to edit does not exist.');
        }
    }

    function detallecuota()
    {
      $cuota_id = $this->input->post('cuota');
      $cuotum = $this->Cuotum_model->get_cuotum($cuota_id);
      echo json_encode($cuotum);
    }
    /*
     * Deleting cuotum
     */
    function remove($cuota_id,$credito_id)
    {
        if($this->acceso(41)){
            $cuotum = $this->Cuotum_model->get_cuotum($cuota_id);

            // check if the cuotum exists before trying to delete it
            if(isset($cuotum['cuota_id']))
            {
                $this->Cuotum_model->delete_cuotum($cuota_id);
                redirect('cuotum/deudas/'.$credito_id);
            }
            else
                show_error('The cuotum you are trying to delete does not exist.');
        }
    }

    function remover($cuota_id,$credito_id)
    {
        if($this->acceso(47)){
            $cuotum = $this->Cuotum_model->get_cuotum($cuota_id);

            // check if the cuotum exists before trying to delete it
            if(isset($cuotum['cuota_id']))
            {
                $this->Cuotum_model->delete_cuotum($cuota_id);
                redirect('cuotum/cuentas/'.$credito_id);
            }
            else
                show_error('The cuotum you are trying to delete does not exist.');
        }
    }
    
}
