<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Egreso extends CI_Controller{
    private $session_data = "";
    private $sistema;
    function __construct()
    {
        parent::__construct();
        $this->load->model('Egreso_model');
        $this->load->model('Categoria_egreso_model'); 
        $this->load->model('Empresa_model');
        $this->load->model('Usuario_model');   
        $this->load->model('Moneda_model');   
        $this->load->helper('numeros');
        $this->load->model('Parametro_model');
        $this->load->model('Detalle_egreso_model');
        $this->load->model('Forma_pago_model');
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
        $this->load->model('Sistema_model');
        $this->sistema = $this->Sistema_model->get_sistema();
    }
    /* *****Funcion que verifica el acceso al sistema**** */
    private function acceso($id_rol){
        
        $data['sistema'] = $this->sistema;
        $rolusuario = $this->session_data['rol'];
        if($rolusuario[$id_rol-1]['rolusuario_asignado'] == 1){
            return true;
        }else{
            $data['_view'] = 'login/mensajeacceso';
            $this->load->view('layouts/main',$data);
        }
    }
     
    /*  
     * Listegr of egreso
     */
    function index()
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(59)){
            $data['page_title'] = "Egreso";
            $data['rol'] = $this->session_data['rol'];
            //$data['egreso'] = $this->Egreso_model->get_all_egreso();
            $data['all_categoria_egreso'] = $this->Categoria_egreso_model->get_all_categoria_egreso();
            $data['empresa'] = $this->Empresa_model->get_empresa(1);
            $data['parametro'] = $this->Parametro_model->get_parametros();
            $this->load->model('Moneda_model');
            $data['moneda'] = $this->Moneda_model->get_moneda(2); //Obtener moneda extragera
            $data['lamoneda'] = $this->Moneda_model->getalls_monedasact_asc();
            $data['_view'] = 'egreso/index';
            $this->load->view('layouts/main',$data);
        }
    }

    function buscarfecha(){
        
        $data['sistema'] = $this->sistema;
        if($this->acceso(59)){
            if ($this->input->is_ajax_request()){
                $filtro = $this->input->post('filtro');
                $categ = $this->input->post('categ');
                $categoria = $this->input->post('categoria');
                $parametro = "";
                if($categ == 1){
                    $parametro = "and (e.egreso_categoria like '%$categoria%' or e.egreso_especificacion like '%$categoria%')";
                }
                if ($filtro == null){
                    $result = $this->Egreso_model->get_all_egreso();
                }else{
                    $result = $this->Egreso_model->fechaegreso($filtro,$parametro);
                }
                echo json_encode($result);
            }else{                 
                show_404();
            }          
        }
    }

    
    function add()
    {   
        $data['sistema'] = $this->sistema;
        if($this->acceso(60)){
            $data['page_title'] = "Egreso";
            $usuario_id = $this->session_data['usuario_id'];
            $this->load->library('form_validation');
            $this->form_validation->set_rules('egreso_nombre', 'egreso_nombre', 'required');
            //$this->load->model('Parametro_model');
            $parametro = $this->Parametro_model->get_all_parametro();
            $data['parametro'] = $parametro;
            $this->load->model('Moneda_model');
            $all_moneda = $this->Moneda_model->getalls_monedasact_asc();
            $data['all_moneda'] = $all_moneda;
            if($this->form_validation->run())
            {
                $numrec = $this->Egreso_model->numero();
                $numero = $numrec[0]['parametro_numrecegr'] + 1;
                $egreso_monto  = $this->input->post('egreso_monto');
                $egreso_moneda = $this->input->post('egreso_moneda');
                $egreso_tc     = $all_moneda[1]["moneda_tc"];
                $total_final = 0;
                if($parametro[0]["moneda_id"]==1){ //Si es bolivianos
                    $lamoneda = $all_moneda[0]["moneda_descripcion"];
                    if($egreso_moneda != "Bs"){
                        $total_final += $egreso_monto*$all_moneda[1]["moneda_tc"];
                    }else{
                        $total_final += $egreso_monto;
                    }
                }else{ // Si no se multiplica
                    $lamoneda = $all_moneda[1]["moneda_descripcion"];
                    if($egreso_moneda != "Bs"){
                        $total_final += $egreso_monto;
                    }else{
                        $total_final += $egreso_monto/$all_moneda[1]["moneda_tc"];
                    }
                }
                
                $params = array(
                    'usuario_id' => $usuario_id,
                    'egreso_categoria' => $this->input->post('egreso_categoria'),
                    'egreso_numero' => $numero,
                    'egreso_nombre' => $this->input->post('egreso_nombre'),
                    'egreso_monto' => $total_final,
                    'egreso_moneda' => $lamoneda,
                    'egreso_concepto' => $this->input->post('egreso_concepto'),
                    'egreso_fecha' => $this->input->post('egreso_fecha'),
                    'egreso_tc' => $egreso_tc,
                    'forma_id' => $this->input->post('forma_pago'),
                    'egreso_glosa' => $this->input->post('egreso_glosa'),
                );
                $egreso_id = $this->Egreso_model->add_egreso($params);
                $sql = "UPDATE parametros SET parametro_numrecegr=parametro_numrecegr+1 WHERE parametro_id = '1'"; 
                $this->db->query($sql);
                redirect('egreso/index');
            }else{
                $this->load->model('Categoria_egreso_model');
                $data['all_categoria_egreso'] = $this->Categoria_egreso_model->get_all_categoria_egreso();
                $this->load->model('Parametro_model');
                $data['parametro'] = $this->Parametro_model->get_all_parametro();
                $data['all_forma_pago'] = $this->Forma_pago_model->get_all_forma();
                
                $this->load->model('Banco_model');
                $data['all_banco'] = $this->Banco_model->getall_bancosact_asc();
                $data['_view'] = 'egreso/add';
                $this->load->view('layouts/main',$data);
            }
        }
    } 

    /*
     * Editegr a egreso
     */
    function edit($egreso_id)
    {   
        $data['sistema'] = $this->sistema;
        if($this->acceso(61)){
            $data['page_title'] = "Egreso";
            $usuario_id = $this->session_data['usuario_id'];
            // check if the egreso exists before tryegr to edit it
            $data['egreso'] = $this->Egreso_model->get_egreso($egreso_id);
            $data['tipousuario_id'] = $this->session_data['tipousuario_id'];
            $parametro = $this->Parametro_model->get_all_parametro();
            $data['parametro'] = $parametro;
            $this->load->model('Moneda_model');
            $all_moneda = $this->Moneda_model->getalls_monedasact_asc();
            $data['all_moneda'] = $all_moneda;
            if(isset($data['egreso']['egreso_id']))
            {
                if(isset($_POST) && count($_POST) > 0)     
                {
                    $egreso_monto  = $this->input->post('egreso_monto');
                    $egreso_moneda = $this->input->post('egreso_moneda');
                    $egreso_tc     = $all_moneda[1]["moneda_tc"];
                    $total_final = 0;
                    if($parametro[0]["moneda_id"]==1){ //Si es bolivianos
                        $lamoneda = $all_moneda[0]["moneda_descripcion"];
                        if($egreso_moneda != "Bs"){
                            $total_final += $egreso_monto*$all_moneda[1]["moneda_tc"];
                        }else{
                            $total_final += $egreso_monto;
                        }
                    }else{ // Si no se multiplica
                        $lamoneda = $all_moneda[1]["moneda_descripcion"];
                        if($egreso_moneda != "Bs"){
                            $total_final += $egreso_monto;
                        }else{
                            $total_final += $egreso_monto/$all_moneda[1]["moneda_tc"];
                        }
                    }
                    if($this->session_data['tipousuario_id'] == 1){
                        $params = array(
                            'usuario_id' => $this->input->post('usuario_id'),
                            'egreso_categoria' => $this->input->post('egreso_categoria'),
                            'egreso_numero' => $this->input->post('egreso_numero'),
                            'egreso_nombre' => $this->input->post('egreso_nombre'),
                            'egreso_monto' => $total_final,
                            'egreso_moneda' => $lamoneda, //$this->input->post('egreso_moneda'),
                            'egreso_concepto' => $this->input->post('egreso_concepto'),
                            'egreso_fecha' => $this->input->post('egreso_fecha'),
                            'forma_id' => $this->input->post('forma_pago'),
                            'egreso_glosa' => $this->input->post('egreso_glosa'),
                        );
                    }else{
                    $params = array(
                        'usuario_id' => $usuario_id,
                        'egreso_categoria' => $this->input->post('egreso_categoria'),
                        'egreso_numero' => $this->input->post('egreso_numero'),
                        'egreso_nombre' => $this->input->post('egreso_nombre'),
                        'egreso_monto' => $total_final,
                        'egreso_moneda' => $lamoneda, //$this->input->post('egreso_moneda'),
                        'egreso_concepto' => $this->input->post('egreso_concepto'),
                        'forma_id' => $this->input->post('forma_pago'),
                        'egreso_glosa' => $this->input->post('egreso_glosa'),
                        //'egreso_fecha' => $this->input->post('egreso_fecha'),		
                    );
                }
                
                $this->Egreso_model->update_egreso($egreso_id,$params);            
                redirect('egreso/index');
            }else{
	
                $this->load->model('Categoria_egreso_model');
                $data['all_categoria_egreso'] = $this->Categoria_egreso_model->get_all_categoria_egreso();
                $data['all_usuario'] = $this->Usuario_model->get_all_usuario_activo();
                $data['all_forma_pago'] = $this->Forma_pago_model->get_all_forma();
                
                $this->load->model('Banco_model');
                $data['all_banco'] = $this->Banco_model->getall_bancosact_asc();
                $data['_view'] = 'egreso/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The egreso you are tryegr to edit does not exist.');
        }
    }

    /*
     * Deletegr egreso
     */

    public function pdf($egreso_id){
        
        $data['sistema'] = $this->sistema;
        if($this->acceso(64)){
            $data['page_title'] = "Egreso";
            $data['parametro'] = $this->Parametro_model->get_parametros();
            $data['egresos'] = $this->Egreso_model->get_egresos($egreso_id);
            $data['empresa'] = $this->Empresa_model->get_empresa(1);
            $this->load->model('Moneda_model');
            $data['lamoneda'] = $this->Moneda_model->getalls_monedasact_asc();
            $data['_view'] = 'egreso/recibo';
            $this->load->view('layouts/main',$data);
        }
    }


    public function boucher($egreso_id){
        
        $data['sistema'] = $this->sistema;
        if($this->acceso(64)){
            $data['page_title'] = "Egreso";
            $data['parametro'] = $this->Parametro_model->get_parametros();
            $data['egreso'] = $this->Egreso_model->get_egresos($egreso_id);
            $data['empresa'] = $this->Empresa_model->get_empresa(1);
            $this->load->model('Moneda_model');
            $data['lamoneda'] = $this->Moneda_model->getalls_monedasact_asc();
            $data['_view'] = 'egreso/reciboboucher';
            $this->load->view('layouts/main',$data);
        }
    }

    /*************** funcion para mostrar la vista de la factura******************/
    function imprimir($egreso_id){
    
        $data['sistema'] = $this->sistema;
        if($this->acceso(58)){
        //**************** inicio contenido ***************            
                
            $parametros = $this->Parametro_model->get_parametros();

            if (sizeof($parametros)>0){
                
                if ($parametros[0]['parametro_tipoimpresora']=="FACTURADORA")
                    $this->boucher($egreso_id);
                else
                    $this->pdf($egreso_id);
            }

        //**************** fin contenido ***************
        } 
                
    }     
    
    
    
    function remove($egreso_id)
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(62)){
            $egreso = $this->Egreso_model->get_egreso($egreso_id);

            // check if the egreso exists before tryegr to delete it
            if(isset($egreso['egreso_id']))
            {
                $this->Egreso_model->delete_egreso($egreso_id);
                redirect('egreso/index');
            }
            else
                show_error('The egreso you are tryegr to delete does not exist.');
        }
    }
    

    public function convertir()
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(59)){
        $egreso_monto = trim($this->input->post('egreso_monto'));

        if (empty($egreso_monto)) {
            echo json_encode(array('leyenda' => 'Debe introducir una egreso_monto.'));
            
            return;
        }
        
        # verificar si el número no tiene caracteres no númericos, con excepción
        # del punto decimal
        $xegreso_monto = str_replace('.', '', $egreso_monto);
        
        if (FALSE === ctype_digit($xegreso_monto)){
            echo json_encode(array('leyenda' => 'La egreso_monto introducida no es válida.'));
            
            return;
        }

        # procedemos a covertir la egreso_monto en letras
        $this->load->helper('numeros');
        $response = array(
            'leyenda' => num_to_letras($egreso_monto)
            , 'egreso_monto' => $egreso_monto
            );  
        echo json_encode($response);
        }
    }

    function add_egresos(){
        
        $data['sistema'] = $this->sistema;
        if($this->input->is_ajax_request()){
            $usuario_id = $this->session_data['usuario_id'];
            $numrec = $this->Egreso_model->numero();
            $numero = $numrec[0]['parametro_numrecegr'] + 1;
            $egreso_nombre = $this->input->post('egreso_nombre');
            $forma_id = $this->input->post('select_forma_pago');
            $egreso_moneda = $this->input->post('egreso_moneda');
            $egreso_monto = $this->input->post('egreso_monto');
            $egreso_concepto = $this->input->post('egreso_concepto');
            $egreso_glosa = $this->input->post('egreso_glosa');
            $egreso_monreg = $this->input->post('egreso_monreg');
            $egreso_especificacion = $this->input->post('egreso_especificacion');
            $egreso_fecha = date('Y-m-d H:i:s');
            
            $moneda_parametro = $this->Parametro_model->get_moneda();
            $egreso_monto = $egreso_moneda == $moneda_parametro['moneda_id'] ? $egreso_monto : round($egreso_monto/$moneda_parametro['moneda_tc'], 3);
            $egreso_moneda = $moneda_parametro['moneda_descripcion'];
            
            $all_moneda = $this->Moneda_model->getalls_monedasact_asc();
            $egreso_tc = $all_moneda[1]["moneda_tc"];
            $el_banco = 0;
            if($forma_id != 1){
                $el_banco = $this->input->post('banco_id');
            }
            $params = array(
                'usuario_id' => $usuario_id,
                'egreso_numero' => $numero,
                'egreso_nombre' => $egreso_nombre,
                'forma_id' => $forma_id,
                'egreso_moneda' => $egreso_moneda,
                'egreso_monto' => $egreso_monto,
                'egreso_concepto' => $egreso_concepto,
                'egreso_glosa' => $egreso_glosa,
                'egreso_tc' => $egreso_tc,
                'egreso_fecha' => $egreso_fecha,
                'egreso_monreg'=> $egreso_monreg,
                'egreso_categoria'=> $egreso_especificacion,
                'egreso_especificacion'=> $egreso_especificacion,
                'banco_id' => $el_banco,
            );
            $this->Egreso_model->add_egreso($params);
            $sql = "UPDATE parametros SET parametro_numrecegr=parametro_numrecegr+1 WHERE parametro_id = '1'"; 
            $this->db->query($sql);
        }else{
            show_404();
        }
    }

    function edit_egresos(){
        
        $data['sistema'] = $this->sistema;
        if($this->input->is_ajax_request()){
            $egreso_nombre = $this->input->post('egreso_nombre');
            $forma_id = $this->input->post('select_forma_pago');
            $egreso_moneda = $this->input->post('egreso_moneda');
            $egreso_monto = $this->input->post('egreso_monto');
            $egreso_concepto = $this->input->post('egreso_concepto');
            $egreso_glosa = $this->input->post('egreso_glosa');
            $egreso_monreg = $this->input->post('egreso_monreg');
            $egreso_fecha = $this->input->post('egreso_fecha');
            $usuario_id = $this->input->post('usuario_id');
            $egreso_numero = $this->input->post('egreso_numero');
            $all_moneda = $this->Moneda_model->getalls_monedasact_asc();
            $egreso_tc = $all_moneda[1]["moneda_tc"];
            $egreso_id = $this->input->post('egreso_id');
            $egreso_especificacion =$this->input->post('egreso_especificacion');
            
            $moneda_parametro = $this->Parametro_model->get_moneda();
            $egreso_monto = $egreso_moneda == $moneda_parametro['moneda_id'] ? $egreso_monto : round($egreso_monto/$moneda_parametro['moneda_tc'], 3);
            $egreso_moneda = $moneda_parametro['moneda_descripcion'];
            $el_banco = 0;
            if($forma_id != 1){
                $el_banco = $this->input->post('banco_id');
            }
            $params = array(
                'usuario_id' => $usuario_id,
                'egreso_numero' => $egreso_numero,
                'egreso_nombre' => $egreso_nombre,
                'forma_id' => $forma_id,
                'egreso_moneda' => $egreso_moneda,
                'egreso_monto' => $egreso_monto,
                'egreso_concepto' => $egreso_concepto,
                'egreso_glosa' => $egreso_glosa,
                'egreso_tc' => $egreso_tc,
                'egreso_fecha' => $egreso_fecha,
                'egreso_monreg' => $egreso_monreg,
                'egreso_categoria' => $egreso_especificacion,
                'egreso_especificacion' => $egreso_especificacion,
                'banco_id' => $el_banco,
            );

            $this->Egreso_model->edit_egreso($params, $egreso_id);
        }else{
            show_404();
        }
    }
    
}
