<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Inventario_usuario extends CI_Controller{
    
    private $sistema;
    function __construct()
    {
        parent::__construct();
        $this->load->model('Inventario_usuario_model');
        $this->load->model('Venta_model');
        $this->load->model('Usuario_model');
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
        $this->load->model('Sistema_model');
        $this->sistema = $this->Sistema_model->get_sistema();
    }
    /* *****Funcion que verifica el acceso al sistema**** */
    private function acceso($id_rol){
        
        $data['sistema'] = $this->sistema;
        $rolusuario = $this->session_data['rol'];
        if($rolusuario[$id_rol-1]['rolusuario_asignado'] == 1){
            return true;
        }else{
            return false;
        }
    } 

    /*
     * Listing of inventario_usuario
     */
    function index()
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(193)){
            $data['rolusuario'] = $this->session_data['rol'];
            $data['usuario_id'] = $this->session_data['usuario_id'];
            $data['usuario_nombre'] = $this->session_data['usuario_nombre'];
            $data['page_title'] = "Inventario Individual";
            $data['all_usuario'] = $this->Usuario_model->get_all_usuario_activo();
            $this->load->model('Parametro_model');
            $data['parametro'] = $this->Parametro_model->get_parametros();
            $this->load->model('Moneda_model');
            $data['moneda'] = $this->Moneda_model->get_moneda(2); //Obtener moneda extragera
            $data['lamoneda'] = $this->Moneda_model->getalls_monedasact_asc();
            $data['_view'] = 'inventario_usuario/index';
            $this->load->view('layouts/main',$data);
        }
    }

    function buscar()
    {
        $data['sistema'] = $this->sistema;
        if($this->input->is_ajax_request()){
            $filtro = $this->input->post('filtro');
            $datos = $this->Inventario_usuario_model->buscar_inventario_usuario($filtro);
            echo json_encode($datos);
        }else{                 
            show_404();
        }          
    }

    /*
     * Adding a new inventario_usuario
     */
    function add()
    {   
        $data['sistema'] = $this->sistema;
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'producto_id' => $this->input->post('producto_id'),
				'inventario_fecha' => $this->input->post('inventario_fecha'),
				'inventario_hora' => $this->input->post('inventario_hora'),
				'inventario_cantidad' => $this->input->post('inventario_cantidad'),
				'inventario_ventas' => $this->input->post('inventario_ventas'),
				'inventario_pedidos' => $this->input->post('inventario_pedidos'),
				'inventario_devoluciones' => $this->input->post('inventario_devoluciones'),
				'inventario_saldo' => $this->input->post('inventario_saldo'),
				'usuario_id' => $this->input->post('usuario_id'),
            );
            
            $inventario_usuario_id = $this->Inventario_usuario_model->add_inventario_usuario($params);
            redirect('inventario_usuario/index');
        }
        else
        {            
            $data['_view'] = 'inventario_usuario/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    function asignar()
    {
        $data['sistema'] = $this->sistema;
        $fecha   = $this->input->post('fecha');
        $hora    = $this->input->post('hora');
        $usuario = $this->input->post('usuario');
        $filtro  = $this->input->post('filtro');
        if($filtro!=""){
            $datos = $this->Venta_model->get_busqueda($filtro);
            echo json_encode($datos);
            $borrar="DELETE FROM inventario_usuario WHERE usuario_id=".$usuario." and inventario_fecha='".$fecha."' ";
            $this->db->query($borrar);
            foreach ($datos as $dat) {
              $params = array(
                    'producto_id' => $dat['producto_id'],
                    'inventario_fecha' => $fecha,
                    'inventario_hora' => $hora,
                    'inventario_cantidad' => $dat['cantidades'],
                    'inventario_costo' => $dat['producto_costo'],
                    'inventario_ventas' => 0,
                    'inventario_pedidos' => 0,
                    'inventario_devoluciones' => 0,
                    'inventario_saldo' => $dat['cantidades'],
                    'usuario_id' => $usuario,
                );

                $inventario_usuario_id = $this->Inventario_usuario_model->add_inventario_usuario($params);

            }
             $entrega="UPDATE venta v SET entrega_id = 1, v.entrega_usuarioid=".$usuario." WHERE 1=1 ".$filtro."";
             $this->db->query($entrega);
        }
    }
    
    /*
     * Editing a inventario_usuario
     */
    function edit($inventario_id)
    {   
        $data['sistema'] = $this->sistema;
        // check if the inventario_usuario exists before trying to edit it
        $data['inventario_usuario'] = $this->Inventario_usuario_model->get_inventario_usuario($inventario_id);
        
        if(isset($data['inventario_usuario']['inventario_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'producto_id' => $this->input->post('producto_id'),
					'inventario_fecha' => $this->input->post('inventario_fecha'),
					'inventario_hora' => $this->input->post('inventario_hora'),
					'inventario_cantidad' => $this->input->post('inventario_cantidad'),
					'inventario_ventas' => $this->input->post('inventario_ventas'),
					'inventario_pedidos' => $this->input->post('inventario_pedidos'),
					'inventario_devoluciones' => $this->input->post('inventario_devoluciones'),
					'inventario_saldo' => $this->input->post('inventario_saldo'),
					'usuario_id' => $this->input->post('usuario_id'),
                );

                $this->Inventario_usuario_model->update_inventario_usuario($inventario_id,$params);            
                redirect('inventario_usuario/index');
            }
            else
            {
                $data['producto'] = $this->Inventario_usuario_model->get_producto($inventario_id);
                $data['all_usuario'] = $this->Usuario_model->get_all_usuario();
                $data['_view'] = 'inventario_usuario/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The inventario_usuario you are trying to edit does not exist.');
    } 

    /*
     * Deleting inventario_usuario
     */
    function remove($inventario_id)
    {
        $data['sistema'] = $this->sistema;
        $inventario_usuario = $this->Inventario_usuario_model->get_inventario_usuario($inventario_id);

        // check if the inventario_usuario exists before trying to delete it
        if(isset($inventario_usuario['inventario_id']))
        {
            $this->Inventario_usuario_model->delete_inventario_usuario($inventario_id);
            redirect('inventario_usuario/index');
        }
        else
            show_error('The inventario_usuario you are trying to delete does not exist.');
    }
    
    function actualizar_inventario()
    {   
        $data['sistema'] = $this->sistema; 
        $usuario_id = $this->input->post('usuario_id');
        $fecha = $this->input->post('fecha');
        $tipo = $this->input->post('tipo');
        
        $this->Inventario_usuario_model->actualizar_inventario($usuario_id, $fecha, $tipo);
        
        echo true;      
    }
    
    function eliminar_inventario()
    {    
        $data['sistema'] = $this->sistema;
        $usuario_id = $this->input->post('usuario_id');
        $fecha = $this->input->post('fecha');
        
        $this->Inventario_usuario_model->eliminar_inventario($usuario_id, $fecha);
        
        echo true;      
    }
    
}
