<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Item extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Item_model');
    } 

    /*
     * Listing of item
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('item/index?');
        $config['total_rows'] = $this->Item_model->get_all_item_count();
        $this->pagination->initialize($config);

        $data['item'] = $this->Item_model->get_all_item($params);
        
        $data['_view'] = 'item/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new item
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('item_nombre','Item Nombre','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'estadopag_id' => $this->input->post('estadopag_id'),
				'submenu_id' => $this->input->post('submenu_id'),
				'menu_id' => $this->input->post('menu_id'),
				'item_nombre' => $this->input->post('item_nombre'),
				'item_descripcion' => $this->input->post('item_descripcion'),
				'item_enlace' => $this->input->post('item_enlace'),
				'item_imagen' => $this->input->post('item_imagen'),
            );
            
            $item_id = $this->Item_model->add_item($params);
            redirect('item/index');
        }
        else
        {
			$this->load->model('Estado_pagina_model');
			$data['all_estado_pagina'] = $this->Estado_pagina_model->get_all_estado_pagina();

			$this->load->model('Submenu_model');
			$data['all_submenu'] = $this->Submenu_model->get_all_submenu();

			$this->load->model('Menu_model');
			$data['all_menu'] = $this->Menu_model->get_all_menu();
            
            $data['_view'] = 'item/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a item
     */
    function edit($item_id)
    {   
        // check if the item exists before trying to edit it
        $data['item'] = $this->Item_model->get_item($item_id);
        
        if(isset($data['item']['item_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('item_nombre','Item Nombre','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'estadopag_id' => $this->input->post('estadopag_id'),
					'submenu_id' => $this->input->post('submenu_id'),
					'menu_id' => $this->input->post('menu_id'),
					'item_nombre' => $this->input->post('item_nombre'),
					'item_descripcion' => $this->input->post('item_descripcion'),
					'item_enlace' => $this->input->post('item_enlace'),
					'item_imagen' => $this->input->post('item_imagen'),
                );

                $this->Item_model->update_item($item_id,$params);            
                redirect('item/index');
            }
            else
            {
				$this->load->model('Estado_pagina_model');
				$data['all_estado_pagina'] = $this->Estado_pagina_model->get_all_estado_pagina();

				$this->load->model('Submenu_model');
				$data['all_submenu'] = $this->Submenu_model->get_all_submenu();

				$this->load->model('Menu_model');
				$data['all_menu'] = $this->Menu_model->get_all_menu();

                $data['_view'] = 'item/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The item you are trying to edit does not exist.');
    } 

    /*
     * Deleting item
     */
    function remove($item_id)
    {
        $item = $this->Item_model->get_item($item_id);

        // check if the item exists before trying to delete it
        if(isset($item['item_id']))
        {
            $this->Item_model->delete_item($item_id);
            redirect('item/index');
        }
        else
            show_error('The item you are trying to delete does not exist.');
    }
    
}
