<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Mesa extends CI_Controller{
    
    private $sistema;
    private $parametros;
    
    function __construct()
    {
        parent::__construct();
        $this->load->model('Mesa_model');
        $this->load->model('Sistema_model');
        $this->load->model('Estado_model');
        $this->load->model('Venta_model');
        $this->load->model('Tipo_transaccion_model');
        $this->load->model('Forma_pago_model');
        $this->load->model('Tipo_cliente_model');
        $this->load->model('Moneda_model');
        $this->load->model('Tipo_servicio_model');
        $this->load->model('Usuario_model');
        $this->load->model('Preferencia_model');
        $this->load->model('Promocion_model');
        $this->load->model('Empresa_model');
        $this->sistema = $this->Sistema_model->get_sistema();
        
        $this->load->model('Parametro_model');
        $parametro = $this->Parametro_model->get_parametros();
        $this->parametros = $parametro[0];
        
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
    } 

    /*
     * Listing of mesa
     */
    function index()
    {
        $data['sistema'] = $this->sistema;
        $data['mesa'] = $this->Mesa_model->get_all_mesa();
        
        $data['_view'] = 'mesa/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new mesa
     */
    function add()
    {  
        $data['sistema'] = $this->sistema;
        if(isset($_POST) && count($_POST) > 0)     
        {
            $params = array(
                'usuario_id' => $this->input->post('usuario_id'),
                'mesa_nombre' => $this->input->post('mesa_nombre'),
            );
            $mesa_id = $this->Mesa_model->add_mesa($params);
            redirect('mesa/index');
        }
        else
        {
            $this->load->model('Usuario_model');
            $data['all_usuario'] = $this->Usuario_model->get_all_usuario_activo();
            
            $data['_view'] = 'mesa/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a mesa
     */
    function edit($mesa_id)
    {
        $data['sistema'] = $this->sistema;
        // check if the mesa exists before trying to edit it
        $data['mesa'] = $this->Mesa_model->get_mesa($mesa_id);
        if(isset($data['mesa']['mesa_id']))
        {
            if(isset($_POST) && count($_POST) > 0)
            {
                $params = array(
                    'usuario_id' => $this->input->post('usuario_id'),
                    'mesa_nombre' => $this->input->post('mesa_nombre'),
                );
                $this->Mesa_model->update_mesa($mesa_id,$params);            
                redirect('mesa/index');
            }else{
                $this->load->model('Usuario_model');
                $data['all_usuario'] = $this->Usuario_model->get_all_usuario();

                $data['_view'] = 'mesa/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The mesa you are trying to edit does not exist.');
    }

    /*
     * Deleting mesa
     */
    function remove($mesa_id)
    {
        $data['sistema'] = $this->sistema;
        $mesa = $this->Mesa_model->get_mesa($mesa_id);

        // check if the mesa exists before trying to delete it
        if(isset($mesa['mesa_id']))
        {
            $this->Mesa_model->delete_mesa($mesa_id);
            redirect('mesa/index');
        }
        else
            show_error('The mesa you are trying to delete does not exist.');
    }
    
    
     /*
     * Vista para mostrar mesas
     */
    function mesas()
    {
        $data['usuario_id'] = $this->session_data['usuario_id'];
        $data['sistema'] = $this->sistema;
        $data['mesa'] = $this->Mesa_model->get_all_mesa();
        $data['categorias'] = $this->Mesa_model->get_all_categorias();
        $data['all_estado'] = $this->Estado_model->get_tipo_estado(10); //estados basicos de tipo 1
        $data['parametro'] = $this->parametros;
        $data['categoria_producto'] = $this->Venta_model->get_categoria_producto();
        $data['empresa'] = $this->Empresa_model->get_empresa(1);
        
        $data['rolusuario'] = $this->session_data['rol'];
        $data['tipo_transaccion'] = $this->Tipo_transaccion_model->get_all_tipo();
        $data['forma_pago'] = $this->Forma_pago_model->get_all_forma();
        $data['tipo_cliente'] = $this->Tipo_cliente_model->get_all_tipo_cliente();
        $data['moneda'] = $this->Moneda_model->get_moneda(2); //Obtener moneda extragera
        $data['all_moneda'] = $this->Moneda_model->getalls_monedasact_asc();
        $this->load->model('Banco_model');
        $data['all_banco'] = $this->Banco_model->getall_bancosact_asc();
        $tipousuario_id = $this->session_data['tipousuario_id'];
        $data['tipousuario_id'] = $tipousuario_id;
        $data['tipo_servicio'] = $this->Tipo_servicio_model->get_all_tipo_servicio();
        $data['usuarios'] = $this->Usuario_model->get_all_usuario_activo();
        $data['tipo_respuesta'] = $this->Usuario_model->get_tipo_respuesta();

        $data['zonas'] = $this->Categoria_clientezona_model->get_all_categoria_clientezona();

        $data['preferencia'] = $this->Preferencia_model->get_producto_preferencia();
        $data['promociones'] = $this->Promocion_model->get_promociones();
        
        $sql = "select * from mesa where estado_id = 38";
        $data['mesadisponible'] = $this->Venta_model->consultar($sql);

        $cliente_id = 0;
        if ($cliente_id>0){
            $cliente = $this->Cliente_model->get_cliente_by_id($cliente_id);
            if (sizeof($cliente)>0)
                $data['cliente'] = $cliente;
            else
                $data['cliente'] = $this->Venta_model->get_cliente_inicialpreventa();
        }        
        else
        {    $data['cliente'] = $this->Venta_model->get_cliente_inicialpreventa();}

        
        
        
        
        
        $data['_view'] = 'mesa/mesas';
        $this->load->view('layouts/main',$data);
    }
    
    /*
    * Verficar usuario
    */
    function cambiar_estado(){

        if ($this->input->is_ajax_request()) {
            
            $estado_id = $this->input->post("estado_id"); 
            $mesa_id = $this->input->post("mesa_id"); 
            
            $sql = "update mesa set estado_id = {$estado_id} where mesa_id = {$mesa_id} ";
            $resultado = $this->Venta_model->ejecutar($sql);            
            
            echo json_encode(true);                

            

        }


    }

    /*
    * ocupar_mesa
    */
    function ocupar_mesa(){

        if ($this->input->is_ajax_request()) {
            
            $estado_id = $this->input->post("estado_id"); 
            
            $now = "'".date("Y-m-d H:i:s")."'"; //{$now}
            $usuario_id = $this->session_data['usuario_id'];;
            $estado_id = 11; //Pendiente
            $cliente_id = 1;
            $tipotrans_id = 1;
            $pedido_fecha = $now;
            $pedido_subtotal = 0;
            $pedido_descuento = 0;
            $pedido_total = 0;
            $pedido_glosa = "";
            //$pedido_fechaentrega = ;
            //$pedido_horaentrega = ;
            $pedido_latitud = 0;
            $pedido_longitud = 0; 
            $regusuario_id = $usuario_id; 
            $mesa_id = $this->input->post("mesa_id"); 
            
            
            //Registramos el pedido/comanda
            $sql = "insert into pedido(usuario_id, estado_id, cliente_id, tipotrans_id, pedido_fecha, 
            pedido_subtotal, pedido_descuento, pedido_total, pedido_glosa, 
            pedido_fechaentrega, pedido_horaentrega, pedido_latitud, 
            pedido_longitud, regusuario_id, mesa_id) value({$usuario_id}, {$estado_id}, {$cliente_id}, {$tipotrans_id}, {$pedido_fecha},
            {$pedido_subtotal}, {$pedido_descuento}, {$pedido_total}, '{$pedido_glosa}', date({$now}),time({$now}), {$pedido_latitud},
            {$pedido_longitud}, {$regusuario_id}, {$mesa_id})";            
            $pedido_id = $this->Venta_model->ejecutar($sql);
            
            //cambiamos de estado la mesas
            $estado_id = 39; //Pendiente
            $sql = "update mesa set estado_id = {$estado_id} where mesa_id = {$mesa_id} ";
            $this->Venta_model->ejecutar($sql);
            
            //
//            $sql = "select * pedido where pedido_id = {$pedido_id} ";
//            $resultado = $this->Venta_model->consultar($sql);
                        
            echo json_encode($pedido_id);                

            

        }


    }
    
    /*
    * mostra detalle mesa
    */
    function mostrar_datos_pedido(){

        if ($this->input->is_ajax_request()) {
            
            $pedido_id = $this->input->post("pedido_id"); 
            
            $sql = "select p.*, e.estado_descripcion, e.estado_color, c.*, m.*
                    from pedido p
                    left join estado e on e.estado_id = p.estado_id
                    left join cliente c on c.cliente_id = p.cliente_id
                    left join mesa m on m.mesa_id = p.mesa_id
                    where p.pedido_id = {$pedido_id}";
            $resultado = $this->Venta_model->consultar($sql);
                        
            echo json_encode($resultado);      

            

        }


    }
    
    /*
    * mostra detalle mesa
    */
    function get_pedido_asociado(){

        if ($this->input->is_ajax_request()) {
            
            $mesa_id = $this->input->post("mesa_id"); 
            
            $sql = "select pedido_id from pedido where estado_id = 11 and mesa_id = {$mesa_id} ";
            $resultado = $this->Venta_model->consultar($sql);
            //var_dump($resultado);            
            if (sizeof($resultado)>0){
             
                    echo json_encode($resultado[0]["pedido_id"]);                    

                
            }else{
                echo json_encode(0);
            }

            

        }


    }
    
    /*
    * Modificar detalle
    */
    function modificar_detalle(){

        if ($this->input->is_ajax_request()) {
            
            $detalleped_precio = $this->input->post("detalleped_precio"); 
            $detalleped_cantidad = $this->input->post("detalleped_cantidad"); 
            $detalleped_id = $this->input->post("detalleped_id"); 
            $pedido_id = $this->input->post("pedido_id"); 
            
            $sql = "update detalle_pedido set
                    detalleped_precio = {$detalleped_precio},
                    detalleped_cantidad = {$detalleped_cantidad},
                    detalleped_subtotal = {$detalleped_cantidad} * {$detalleped_precio},
                    detalleped_total = {$detalleped_cantidad} *{$detalleped_precio}
                    where detalleped_id = {$detalleped_id}";
            $this->Venta_model->ejecutar($sql);
            
            
            $sql = "update pedido p
                    set
                    p.pedido_subtotal = (select sum(d.detalleped_subtotal) as total from detalle_pedido d where d.pedido_id = {$pedido_id} group by p.pedido_id),
                    p.pedido_total = p.pedido_subtotal
                    where p.pedido_id = {$pedido_id}";
            $this->Venta_model->ejecutar($sql);
            
            echo json_encode(true);
        }


    }
    /*
    * mostra detalle mesa
    */
    function mostrar_detalle_pedido(){

        if ($this->input->is_ajax_request()) {
            
            $pedido_id = $this->input->post("pedido_id"); 
            
            $sql = "select * from detalle_pedido where pedido_id = {$pedido_id} ";
            $resultado = $this->Venta_model->consultar($sql);
                        
            echo json_encode($resultado);                

        }


    }

    /*
    * eliminar item
    */
    function eliminar_item(){

        if ($this->input->is_ajax_request()) {
            
            $detalleped_id = $this->input->post("detalleped_id");             
            $sql = "delete from detalle_pedido where detalleped_id = {$detalleped_id} ";
            $this->Venta_model->ejecutar($sql);
                        

            echo json_encode(true);
            
        }


    }

    /*
    * Anular seleccion de mesa
    */
    function anular_seleccion(){

        if ($this->input->is_ajax_request()) {
            
            $pedido_id = $this->input->post("pedido_id"); 

            
            $sql = "update mesa set estado_id = 38 where mesa_id = (select mesa_id from pedido where pedido_id = {$pedido_id})";
            $this->Venta_model->ejecutar($sql);
            
            $sql = "delete from detalle_pedido where pedido_id = {$pedido_id} ";
            $this->Venta_model->ejecutar($sql);

            $sql = "delete from pedido where pedido_id = {$pedido_id} ";
            $this->Venta_model->ejecutar($sql);
                 
            echo json_encode(true);
            
        }


    }

    /*
    * registrar producto
    */
    function registrar_producto(){

        if ($this->input->is_ajax_request()) {
            
            $producto_id = $this->input->post("producto_id"); 
            $cantidad = $this->input->post("cantidad"); 
            $pedido_id = $this->input->post("pedido_id");
            $descuento = 0;
            $preferencia = "";
            
            
            //Verificar si el producto existe
            $sql = "select * from detalle_pedido where pedido_id = {$pedido_id} and producto_id = {$producto_id}";
            $resultado = $this->Venta_model->consultar($sql);
            
            if(isset($resultado)){
            
                if(! sizeof($resultado)>0){
            
                $sql = "insert into detalle_pedido(
                        pedido_id,
                        producto_id,
                        detalleped_codigo,
                        detalleped_foto,
                        detalleped_nombre,
                        detalleped_unidad,
                        detalleped_costo,
                        detalleped_cantidad,
                        detalleped_precio,
                        detalleped_descuento,
                        detalleped_subtotal,
                        detalleped_total,
                        detalleped_preferencia,
                        detalleped_comision,
                        detalleped_tc,
                        detalleped_descuentoparcial

                        )
                        (
                        select
                        ".$pedido_id.",
                        producto_id,
                        producto_codigo,
                        producto_foto,
                        producto_nombre,
                        producto_unidad,
                        producto_costo,
                        ".$cantidad.",
                        producto_precio - ".$descuento.",
                         0,
                        ".$cantidad." * (producto_precio - ".$descuento."),
                        ".$cantidad." * (producto_precio - ".$descuento."),
                        '".$preferencia."',
                        0,1,0
                        from producto where producto_id = ".$producto_id."
                        )";
                    $this->Venta_model->ejecutar($sql);


                    $sql = "update pedido p
                            set
                            p.pedido_subtotal = (select sum(d.detalleped_subtotal) as total from detalle_pedido d where d.pedido_id = {$pedido_id} group by p.pedido_id),
                            p.pedido_total = p.pedido_subtotal
                            where p.pedido_id = {$pedido_id}";
                    $this->Venta_model->ejecutar($sql);

                    echo json_encode(true);
                }else{
                   
                    $sql = "update detalle_pedido d
                            set                            
                            d.detalleped_cantidad = d.detalleped_cantidad + {$cantidad},
                            d.detalleped_subtotal = d.detalleped_cantidad * d.detalleped_precio,
                            d.detalleped_total = d.detalleped_cantidad * d.detalleped_precio
                            where d.detalleped_id = {$resultado[0]["detalleped_id"]}";
                    $this->Venta_model->ejecutar($sql);

                    $sql = "update pedido p
                            set
                            p.pedido_subtotal = (select sum(d.detalleped_subtotal) as total from detalle_pedido d where d.pedido_id = {$pedido_id} group by p.pedido_id),
                            p.pedido_total = p.pedido_subtotal
                            where p.pedido_id = {$pedido_id}";
                    $this->Venta_model->ejecutar($sql);

                    echo json_encode(true);                    
                    
                    
                }
                
                
            }
        }


    }
    
    /*
    * cambiar_mesa
    */
    function cambiar_mesa(){

        if ($this->input->is_ajax_request()) {
            
            $mesa_disponible = $this->input->post("mesa_disponible"); 
            $mesa_ocupada = $this->input->post("mesa_id"); 
            $pedido_id = $this->input->post("pedido_id");

            // Reasignamos pedido
            $sql = "update pedido set mesa_id = {$mesa_disponible} where pedido_id = {$pedido_id}";
            $this->Venta_model->ejecutar($sql);

            //Ocupamos la mesa libre
            $sql = "update mesa set estado_id = 39 where mesa_id = {$mesa_disponible}";
            $this->Venta_model->ejecutar($sql);
            
            //liberamos la mesa ocupada
            $sql = "update mesa set estado_id = 38 where mesa_id = {$mesa_ocupada}";
            $this->Venta_model->ejecutar($sql);
            
            
            echo json_encode(true);

        }


    }
    
}
