<?php 
/*
 Generated by Manuigniter v2.0 
 www.manuigniter.com
*/
class Nivel_vehiculo extends CI_Controller{

    private $sistema;
    private $parametros;

 function __construct()
 {
       parent::__construct();
      $this->load->model('Nivel_vehiculo_model');
      
        $this->load->model('Sistema_model');
        $this->load->model('Parametro_model');
        $this->sistema = $this->Sistema_model->get_sistema();
        $parametro = $this->Parametro_model->get_parametros();
        $this->parametros = $parametro[0];
        
        
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
 } 
 /*
* Listing of nivel_vehiculo
 */
public function index()
{
     $data['sistema'] = $this->sistema;
  try{
      $data['noof_page'] = 0;
     $data['nivel_vehiculo'] = $this->Nivel_vehiculo_model->get_all_nivel_vehiculo();
      $data['_view'] = 'nivel_vehiculo/index';
      $this->load->view('layouts/main',$data);
    } catch (Exception $ex) {
      throw new Exception('Nivel_vehiculo Controller : Error in index function - ' . $ex);
  }  
}
 /*
  * Adding a new nivel_vehiculo
  */
 function add()
 {  
     $data['sistema'] = $this->sistema;
try{
      $params = array(
       'nivel_nombre'=> $this->input->post('nivel_nombre'),
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
       if(isset($_POST) && count($_POST) > 0)     
        {  
            $nivel_id= $this->Nivel_vehiculo_model->add_nivel_vehiculo($params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully added.</div>');
              redirect('nivel_vehiculo/index');
        }
        else
        { 
           $data['_view'] = 'nivel_vehiculo/add';
            $this->load->view('layouts/main',$data);
        }
  } catch (Exception $ex) {
    throw new Exception('Nivel_vehiculo Controller : Error in add function - ' . $ex);
  }  
 }  
  /*
  * Editing a nivel_vehiculo
 */
 public function edit($nivel_id)
 {   
     $data['sistema'] = $this->sistema;
  try{
   $data['nivel_vehiculo'] = $this->Nivel_vehiculo_model->get_nivel_vehiculo($nivel_id);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['nivel_vehiculo']['nivel_id']))
      {
        $params = array(
           'nivel_nombre'=> $this->input->post('nivel_nombre'),
        );
          if(isset($_POST) && count($_POST) > 0)     
           {  
           $this->Nivel_vehiculo_model->update_nivel_vehiculo($nivel_id,$params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully updated.</div>');
                redirect('nivel_vehiculo/index');
           }
           else
          {
              $data['_view'] = 'nivel_vehiculo/edit';
              $this->load->view('layouts/main',$data);
          }
  }
  else
  show_error('The nivel_vehiculo you are trying to edit does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Nivel_vehiculo Controller : Error in edit function - ' . $ex);
  }  
} 
/*
  * Deleting nivel_vehiculo
  */
  function remove($nivel_id)
   {
    try{
      $nivel_vehiculo = $this->Nivel_vehiculo_model->get_nivel_vehiculo($nivel_id);
  // check if the nivel_vehiculo exists before trying to delete it
       if(isset($nivel_vehiculo['nivel_id']))
       {
         $this->Nivel_vehiculo_model->delete_nivel_vehiculo($nivel_id);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully Removed.</div>');
           redirect('nivel_vehiculo/index');
       }
       else
       show_error('The nivel_vehiculo you are trying to delete does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Nivel_vehiculo Controller : Error in remove function - ' . $ex);
  }  
  }
  /*
  * View more a nivel_vehiculo
 */
 public function view_more($nivel_id)
 {   
try{
   $data['nivel_vehiculo'] = $this->Nivel_vehiculo_model->get_nivel_vehiculo($nivel_id);
     if(isset($data['nivel_vehiculo']['nivel_id']))
      {
              $data['_view'] = 'nivel_vehiculo/view_more';
              $this->load->view('layouts/main',$data);
      }
      else
        show_error('The nivel_vehiculo you are trying to view more does not exist.');
    } catch (Exception $ex) {
    throw new Exception('Nivel_vehiculo Controller : Error in View more function - ' . $ex);
  }  
} 
 /*
* Listing of nivel_vehiculo
 */
public function search_by_clm()
{
    $column_name= $this->input->post('column_name');
    $value_id= $this->input->post('value_id');
     $data['noof_page'] = 0;
     $params = array();
    $data['nivel_vehiculo'] = $this->Nivel_vehiculo_model->get_all_nivel_vehiculo_by_cat($column_name,$value_id);
      $data['_view'] = 'nivel_vehiculo/index';
      $this->load->view('layouts/main',$data);
}
 /*
* get search values by column- nivel_vehiculo
 */
public function get_search_values_by_clm()
{
    $clm_name= $this->input->post('clm_name');
    $value= $this->input->post('value');
    $id= $this->input->post('id');
        $params = array(
        $clm_name=>$value,
        );
           $this->Nivel_vehiculo_model->update_nivel_vehiculo($id,$params);
   $data['noof_page'] = 0;
  $data['nivel_vehiculo'] = $this->Nivel_vehiculo_model->get_all_nivel_vehiculo();
  $this->load->view('nivel_vehiculo/index',$data);
}
 }
