<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pedido extends CI_Controller{
    
    private $sistema;
    private $parametros;
    
    function __construct()
    {
        parent::__construct();
        $this->load->model('Empresa_model');
        $this->load->model('Pedido_model');
        $this->load->model('Producto_model');
        $this->load->model('Estado_model');
        $this->load->model('Tipo_transaccion_model');
        $this->load->model('Forma_pago_model');
        $this->load->model('Tipo_transaccion_model');
        $this->load->model('Venta_model');
        $this->load->model('Usuario_model');
        $this->load->model('Moneda_model');
        $this->load->model('Parametro_model');
        $this->load->model('Categoria_clientezona_model');
        $this->load->model('Inventario_model');
        $this->load->model('Cliente_model');
        $this->load->model('Tipo_cliente_model');
        $this->load->model('Dosificacion_model');
        $this->load->model('Parametro_model');
        $this->load->model('Tipo_servicio_model');
        $this->load->model('Preferencia_model');
        $this->load->model('Promocion_model');
        $this->load->model('Ingreso_model');
        
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
        
        $this->load->model('Sistema_model');
        $this->sistema = $this->Sistema_model->get_sistema();
        
        $this->load->model('Parametro_model');
        $parametro = $this->Parametro_model->get_parametros();
        $this->parametros = $parametro[0];
        
    }
    
    private function acceso($id_rol){
        
        $data['sistema'] = $this->sistema;
        $rolusuario = $this->session_data['rol'];
        
        if($rolusuario[$id_rol-1]['rolusuario_asignado'] == 1){
            return true;
        }else{
            $data['_view'] = 'login/mensajeacceso';
            $this->load->view('layouts/main',$data);
        }
    } 

    /*
     * Listing of pedido
     */
    function index()
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(30)) {
                
        //**************** inicio contenido ***************            
        $usuario_id = $this->session_data['usuario_id'];
        $usuario_nombre = $this->session_data['usuario_nombre'];
        $tipousuario_id = $this->session_data['tipousuario_id'];
        $data['pedido_titulo'] = $this->session_data['pedido_titulo'];
        $rolusuario = $this->session_data['rol'];
        $data['esrol'] = $rolusuario[33-1]['rolusuario_asignado'];
        $data['esrolconsolidar'] = $rolusuario[35-1]['rolusuario_asignado'];
        
        $data['page_title'] = $data['pedido_titulo'];
        $data['usuario'] = $this->Usuario_model->get_all_usuario_activo(); // para el select
        $data['tipo_transaccion'] = $this->Tipo_transaccion_model->get_all_tipo(); //para el select
        $data['usuario_id'] = $usuario_id; //el usuario logueado
        
        $data['tipousuario_id'] = $tipousuario_id; 
        $data['usuario_nombre'] = $usuario_nombre;
        //$data['usuarios'] = $this->Venta_model->get_usuarios(); corregido mediante left join
        
        /*$filtro = $this->input->post('filtro');
        
        if ($filtro == null){
            $data['pedido'] = $this->Pedido_model->get_pedidos(" and date(p.pedido_fecha) = date(now())");
        }
        else{
            $data['pedido'] = $this->Pedido_model->get_pedidos($filtro);
        }*/
        
        $this->load->model('Categoria_clientezona_model');
        $data['all_categoria_clientezona'] = $this->Categoria_clientezona_model->get_all_categoria_clientezona_asc();

        //$data['pedidosn'] = $this->Pedido_model->get_pedido_sin_nombre($usuario_id);
        $data['estado'] = $this->Estado_model->get_tipo_estado(5);
        
        $data['_view'] = 'pedido/index';
        $this->load->view('layouts/main',$data);
        
        		
        //**************** fin contenido ***************
        			}
        			       
        
    }
    /*
     * Listing of pedido
     */
    function nota_pedido($pedido_id)
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(32)) {
        //**************** inicio contenido ***************            
        $usuario_id = $this->session_data['usuario_id'];
        $empresa_id = 1;
        
        $data['page_title'] = "Nota de Pedido";
        $data['pedido'] = $data['pedido'] = $this->Pedido_model->get_pedido_id($pedido_id);
        $data['empresa'] = $data['empresa'] = $this->Empresa_model->get_empresa($empresa_id);
        $data['parametro'] = $this->Parametro_model->get_parametros();
        $data['moneda'] = $this->Moneda_model->get_moneda(2); //Obtener moneda extragera
        $data['pedido_titulo'] = $this->session_data['pedido_titulo'];
        
        $data['_view'] = 'pedido/nota_pedido';
        $this->load->view('layouts/main',$data);
        
        		
        //**************** fin contenido ***************
        			}
        		
    }

    /*
     * Listing of pedido
     */
    function nota_pedido_boucher($pedido_id)
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(32)) {
        //**************** inicio contenido ***************            
            $usuario_id = $this->session_data['usuario_id'];
            $empresa_id = 1;

            $data['page_title'] = "Nota de Pedido";
            $data['pedido'] = $data['pedido'] = $this->Pedido_model->get_pedido_id($pedido_id);
            $data['empresa'] = $data['empresa'] = $this->Empresa_model->get_empresa($empresa_id);
            $data['parametro'] = $this->Parametro_model->get_parametros();
            $data['pedido_titulo'] = $this->session_data['pedido_titulo'];
            
            $data['_view'] = 'pedido/nota_pedido_boucher';
            $this->load->view('layouts/main',$data);

        		
        //**************** fin contenido ***************
        }
        		
    }
    
    
    /*
     * Listing of pedido
     */
    function imprimir($pedido_id)
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(32)) {
            //**************** inicio contenido ***************            
            
                            
            $parametros = $this->Parametro_model->get_parametros();

            if (sizeof($parametros)>0){
                
                if ($parametros[0]['parametro_tipoimpresora']=="FACTURADORA")
                    $this->nota_pedido_boucher($pedido_id);
                else
                    $this->nota_pedido($pedido_id);
            }

            
            //**************** fin contenido ***************
        }
        		
    }
    
    
    /*
     * Listing of pedido
     */
    function mostrar_pedidos()
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(30)) {
        //**************** inicio contenido ***************            
        
        $usuario_id = $this->session_data['usuario_id'];

        if ($this->input->is_ajax_request()) {
            
            $filtro = $this->input->post('filtro');
            
            if ($filtro == null){
                $result = $this->Pedido_model->get_pedidos(" and date(p.pedido_fecha) = date(now()) and p.usuario_id=".$usuario_id);
            }
            else{
                $result = $this->Pedido_model->get_pedidos($filtro);
            }

           echo json_encode($result);
            
        }
        else
        {                 
                    show_404();
        }  
        		
        //**************** fin contenido ***************
        			}
        			
    }

    /*
     * Registrar pedido
     */
    function crearpedido()
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(31)) {
        //**************** inicio contenido ***************            
        $usuario_id = $this->session_data['usuario_id'];
        
        //Registrar Pedido
        $pedido_id = $this->Pedido_model->crear_pedido($usuario_id);        
        redirect('pedido/pedidoabierto/'.$pedido_id);
    		
        //**************** fin contenido ***************
        			}
        			        
    }
    

    /*
     * Registrar pedido
     */
    function modificarpedido($pedido_id)
    {
        $data['sistema'] = $this->sistema;
        
        if($this->acceso(31)) {
        //**************** inicio contenido ***************            
        
        $data['page_title'] = "Modificar Pedido";
        $usuario_id = $this->session_data['usuario_id'];
        
        $data['parametros'] = $this->parametros;

        $pedido = $this->Pedido_model->get_cliente_id($pedido_id);
        
        if(sizeof($pedido)>0){
            $cliente_id = $pedido[0]['cliente_id'];
            $usuario_id = $pedido[0]['usuario_id'];
            
        }        
        else
            $cliente_id = 0;
        
        
            if ($cliente_id == 0) //si el pedido aun no fue registrado a un cliente
            {    $data['pedido'] = $this->Pedido_model->get_pedido($pedido_id,$usuario_id); 
            
            }
            else
            {    
                $data['pedido'] = $this->Pedido_model->get_pedido_cliente($pedido_id,$usuario_id); 
                $data['zona'] = $this->Categoria_clientezona_model->get_cliente_zona($pedido[0]['cliente_id']);
            }

            $data['pedido_id'] = $pedido_id;
            $data['usuarios'] = $this->Usuario_model->get_all_usuario_activo();
            $data['usuario_activo'] = $usuario_id;
            $data['rolusuario'] = $this->session_data['rol'];
            
            //$data['cliente'] = $this->Pedido_model->get_all_cliente($usuario_id);
            $data['tipo_transaccion'] = $this->Tipo_transaccion_model->get_all_tipo();
            
            $data['pedido_titulo'] = $this->session_data['pedido_titulo'];
            
            $data['_view'] = 'pedido/modificarpedido';
            $this->load->view('layouts/main',$data);            
                                        		
        //**************** fin contenido ***************
        			}		     
    }
    
    function pedidoabierto($cliente_id)
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(31)){
            //**************** inicio contenido ***************        

            $usuario_id = $this->session_data['usuario_id'];
            $tipousuario_id = $this->session_data['tipousuario_id'];
            $data['rolusuario'] = $this->session_data['rol'];
            $data['page_title'] = "Pedidos";
            //$data['dosificacion'] = $this->Dosificacion_model->get_all_dosificacion();
            //$data['pedidos'] = $this->Pedido_model->get_pedidos_activos();

            if ($cliente_id>0){
                $cliente = $this->Cliente_model->get_cliente_by_id($cliente_id);
                if (sizeof($cliente)>0)
                    $data['cliente'] = $cliente;
                else
                    $data['cliente'] = $this->Venta_model->get_cliente_inicialpreventa();
            }        
            else
            {    $data['cliente'] = $this->Venta_model->get_cliente_inicialpreventa();}

            $data['categoria_producto'] = $this->Venta_model->get_categoria_producto();
            $data['tipo_transaccion'] = $this->Tipo_transaccion_model->get_all_tipo();
            $data['forma_pago'] = $this->Forma_pago_model->get_all_forma();
            $data['tipo_cliente'] = $this->Tipo_cliente_model->get_all_tipo_cliente();
            $data['parametro'] = $this->Parametro_model->get_parametros();
            $data['moneda'] = $this->Moneda_model->get_moneda(2); //Obtener moneda extragera
            $data['all_moneda'] = $this->Moneda_model->getalls_monedasact_asc();
            $this->load->model('Banco_model');
            $data['all_banco'] = $this->Banco_model->getall_bancosact_asc();
            $data['usuario_id'] = $usuario_id;
            $data['tipousuario_id'] = $tipousuario_id;
            $data['tipo_servicio'] = $this->Tipo_servicio_model->get_all_tipo_servicio();
            $data['preferencia'] = $this->Preferencia_model->get_all_preferencia();
            $data['usuarios'] = $this->Usuario_model->get_all_usuario_activo();
            $data['tipo_respuesta'] = $this->Usuario_model->get_tipo_respuesta();

            $data['zonas'] = $this->Categoria_clientezona_model->get_all_categoria_clientezona();

            $data['preferencia'] = $this->Preferencia_model->get_producto_preferencia();
            $data['promociones'] = $this->Promocion_model->get_promociones();

            $data['pedido_titulo'] = $this->session_data['pedido_titulo'];

            //$data['venta'] = $this->Venta_model->get_all_venta($usuario_id);

            $data['_view'] = 'pedido/pedidoabierto';
            $this->load->view('layouts/main',$data);

            //**************** fin contenido ***************
        }       
        
    }

    /*
     * Registrar pedido abierto
     */
    function detalle_pedido()
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(30)) {
            //**************** inicio contenido ***************    
            if ($this->input->is_ajax_request()) {


               $pedido_id = $this->input->post('pedido_id');
               $detalle_pedido = $this->Pedido_model->get_detalle_pedido($pedido_id);            
               echo json_encode($detalle_pedido);

            }
            else
            {                 
                show_404();
            }  

            //**************** fin contenido ***************
        }
        			      
    }

    /*
     * Pasar un pedido a ventas
     */
    function pasaraventas($pedido_id,$cliente_id)
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(30)) {
        //**************** inicio contenido ***************    
        $usuario_id = $this->session_data['usuario_id'];
                
        $sql = "delete from detalle_venta_aux where usuario_id = ".$usuario_id;
        $this->Pedido_model->ejecutar($sql);
        
        $sql = "insert into detalle_venta_aux(
            producto_id,
            venta_id,
            
            detalleven_codigo,
            detalleven_cantidad,
            detalleven_unidad,
            detalleven_costo,
            detalleven_precio,
            detalleven_subtotal,
            detalleven_descuento,
            detalleven_descuentoparcial,
            detalleven_total,
            detalleven_caracteristicas,
            detalleven_preferencia,
            detalleven_comision,
            detalleven_tipocambio,
            usuario_id,
            producto_nombre,
            producto_unidad,
            producto_marca,
            categoria_id,
            producto_codigobarra,
            existencia,
            detalleven_tc
            )
            
            (select 
            d.producto_id,
            0 as venta_id,
            d.detalleped_codigo,
            d.detalleped_cantidad,
            d.detalleped_unidad,
            d.detalleped_costo,
            d.detalleped_precio,
            d.detalleped_subtotal,
            d.detalleped_descuento,
            d.detalleped_descuentoparcial,
            d.detalleped_total,
            '' as caracteristicas,
            d.detalleped_preferencia,
            d.detalleped_comision,
            1 as tipocambio,
            ".$usuario_id.",
            p.producto_nombre,
            p.producto_unidad,
            p.producto_marca,
            p.categoria_id,
            p.producto_codigobarra,
            p.existencia,
            d.detalleped_tc

            from detalle_pedido d, pedido e,usuario u, consinventario p
            where p.producto_id = d.producto_id and e.pedido_id =".$pedido_id." and d.pedido_id = e.pedido_id and e.usuario_id = u.usuario_id)";
       
        
        $this->Pedido_model->ejecutar($sql);
        return true;
        		
        //**************** fin contenido ***************
        }
        			         
    }
    /*
     * Pasar un pedido a ventas
     */
    function datoscliente()
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(30)) {
        //**************** inicio contenido ***************    
        if ($this->input->is_ajax_request()) {
            
                $cliente_id = $this->input->post('cliente_id');
                $sql = "select * from cliente where cliente_id = ".$cliente_id;
                $datosx = $this->Pedido_model->consultar($sql);

               echo json_encode($datosx);

                }
                else
                {                 
                            show_404();
                }  

            //**************** fin contenido ***************
        }
        			
    }
    
    function finalizarpedido()
    {
        $data['sistema'] = $this->sistema;
       if($this->acceso(30)) {
                //**************** inicio contenido ***************    
                $regusuario_id = $this->session_data['usuario_id'];     
                $usuario_id = $this->input->post('usuario_id');

                $estado_id = 3;

                $tipotrans_id = $this->input->post('tipo_transaccion');
                $pedido_fecha = "now()";
                $pedido_id = $this->input->post('pedido_id1');
                $pedido_subtotal = $this->input->post('pedido_subtotal');
                $pedido_descuento = $this->input->post('pedido_descuento');
                $pedido_total = $this->input->post('pedido_totalfinal');
                $pedido_glosa = $this->input->post('pedido_glosa');

                $pedido_latitud = $this->input->post('latitud');
                $pedido_longitud = $this->input->post('longitud');

                $fechahora = $this->input->post('fechahora_entrega');

        //        $dato = '2011-07-12 10:35:27';
                $fecha = date('Y-m-d',strtotime($fechahora)); 
                $hora = date('H:i:s',strtotime($fechahora));          
                //$pedido_horaentrega = $this->input->post('pedido_horaentrega');

                $sql = "update pedido set "
                        //."usuario_id = ".$usuario_id
                        ."estado_id = 11"
                        .",tipotrans_id = ".$tipotrans_id
                        .",pedido_fecha = now()"
                        .",pedido_subtotal = ".$pedido_subtotal
                        .",pedido_descuento = ".$pedido_descuento
                        .",pedido_total = ".$pedido_total
                        .",pedido_glosa = '".$pedido_glosa."'"
                        .",pedido_fechaentrega = '".$fecha."'"
                        .",pedido_horaentrega = '".$hora."'"
                        .",pedido_latitud = '".$pedido_latitud."'"
                        .",pedido_longitud = '".$pedido_longitud."'"
                        .",regusuario_id = ".$regusuario_id
                        ."  where pedido_id=".$pedido_id;        

                $this->Pedido_model->ejecutar($sql);

                $sql = "update inventario i, detalle_pedido d set 
                        i.existencia = i.existencia - d.detalleped_cantidad 
                        where d.pedido_id = ".$pedido_id." and i.producto_id = d.producto_id";
                $this->Pedido_model->ejecutar($sql);

                redirect('pedido');

                //**************** fin contenido ***************
        }
        			         
    }

    
    function registrarpedido()
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(30)){ //12 ventas o 30 pedidos
        //**************** inicio contenido ***************        
        
        $usuario_id = $this->session_data['usuario_id'];
        
        
        $porcentaje = 0;
        
        $cad = $this->input->post('cad'); // recuperamos la consulta sql enviada mediante JS para el insert en la venta
        $pedido_fecha = $this->input->post('pedido_fecha'); // recuperamos la consulta sql enviada mediante JS para el insert en la venta
        $pedido_hora = $this->input->post('pedido_hora'); // recuperamos la consulta sql enviada mediante JS para el insert en la venta
        $cliente_id = $this->input->post('cliente_id'); 

        
        $sql = "insert into pedido(usuario_id, estado_id, cliente_id, tipotrans_id, pedido_fecha, 
            pedido_subtotal, pedido_descuento, pedido_total, pedido_glosa, 
            pedido_fechaentrega, pedido_horaentrega, pedido_latitud, 
            pedido_longitud, regusuario_id) value(".$cad.")";
        
        $pedido_id = $this->Venta_model->ejecutar($sql);// ejecutamos la consulta para registrar la venta y recuperamos venta_id
        
        $venta_total = $this->input->post('pedido_total'); // recuperamos la consulta sql enviada mediante JS
        $venta_descuento = $this->input->post('pedido_descuento'); // descuento de la venta
                
        if (($venta_total+$venta_descuento)>0)
            $porcentaje = $venta_descuento / ($venta_total+$venta_descuento);
        else
            $porcentaje = 0;
            
        $sql =  "insert into detalle_pedido
        (   
            pedido_id,
            producto_id,
            detalleped_codigo,
            detalleped_foto,
            detalleped_nombre,
            detalleped_unidad,
            detalleped_costo,
            detalleped_cantidad,
            detalleped_precio,
            detalleped_descuento,
            detalleped_descuentoparcial,
            detalleped_subtotal,
            detalleped_total,
            detalleped_preferencia,
            detalleped_comision,          
            detalleped_tc        
        )
        (SELECT           
          ".$pedido_id." as pedido_id,
          producto_id,
          producto_codigobarra,
          '-' as detalleped_foto,
          producto_nombre,
          detalleven_unidad,
          detalleven_costo,
          detalleven_cantidad,
          detalleven_precio - (detalleven_subtotal*".$porcentaje."/detalleven_cantidad),
          (detalleven_subtotal*".$porcentaje."/detalleven_cantidad),
          detalleven_descuentoparcial,
          detalleven_subtotal,
          detalleven_total * (1 - ".$porcentaje."),
          detalleven_preferencia,
          detalleven_comision,
          detalleven_tc

        FROM
          detalle_venta_aux
        WHERE 
          usuario_id=".$usuario_id.")";
        
        //echo $sql;
        $this->Pedido_model->ejecutar($sql);// cargar los productos del detalle_aux al detalle_venta
        
        
        //************* reducir inventario
        
        $this->Inventario_model->reducir_inventario_aux($usuario_id);

        $tiporespuesta_id = 0;
        //$pedido_id ya existe
        //$cliente_id = 0; //no es necesario
        //$usuario_id ya existe
        $recorrido_fecha = "'".$pedido_fecha."'";
        $recorrido_hora = "'".$pedido_hora."'";
        $recorrido_detalleresp = "'PEDIDO REALIZADO'";

        $sql = "insert into recorrido_usuario(tiporespuesta_id,
                pedido_id,cliente_id,usuario_id,recorrido_fecha,
                recorrido_hora,recorrido_detalleresp) value(".
                $tiporespuesta_id.",".
                $pedido_id.",".
                $cliente_id.",".
                $usuario_id.",".
                $recorrido_fecha.",".
                $recorrido_hora.",".
                $recorrido_detalleresp.")";
        $this->Pedido_model->ejecutar($sql);// cargar los productos del detalle_aux al detalle_venta
        
        $esreserva = $this->input->post('esreserva');
        if($esreserva){
            $numrec = $this->Ingreso_model->numero();
            $numero = $numrec[0]['parametro_numrecing'] + 1;
            $cliente = $this->Cliente_model->get_cliente($cliente_id);

            $detallepedido = $this->Pedido_model->get_detalle_pedido($pedido_id);
            $glosa = "RESERVA: ";
            foreach ($detallepedido as $detalle) {
                $glosa .= $detalle['detalleped_nombre']."; ";
            }

            $all_moneda = $this->Moneda_model->getalls_monedasact_asc();
            $data['all_moneda'] = $all_moneda;
            $ingreso_monto  = $this->input->post('ingreso_monto');
            $ingreso_moneda = $this->input->post('ingreso_moneda');
            $ingreso_tc     = $all_moneda[1]["moneda_tc"];
            $total_final = 0;
            $parametro = $this->Parametro_model->get_all_parametro();
            if($parametro[0]["moneda_id"]==1){ //Si es bolivianos
                $lamoneda = $all_moneda[0]["moneda_descripcion"];
                if($ingreso_moneda != "Bs"){
                    $total_final += $ingreso_monto*$all_moneda[1]["moneda_tc"];
                }else{
                    $total_final += $ingreso_monto;
                }
            }else{ // Si no se multiplica
                $lamoneda = $all_moneda[1]["moneda_descripcion"];
                if($ingreso_moneda != "Bs"){
                    $total_final += $ingreso_monto;
                }else{
                    $total_final += $ingreso_monto/$all_moneda[1]["moneda_tc"];
                }
            }
            $el_banco = 0;
            if($this->input->post('select_forma_pago') != 1){
                $el_banco = $this->input->post('banco_id');
            }
            $params = array(
                'usuario_id' => $usuario_id,
                'ingreso_categoria' => "",
                'ingreso_numero' => $numero,
                'ingreso_nombre' => $cliente['cliente_nombre'],
                'ingreso_monto' => $total_final,
                'ingreso_moneda' => $lamoneda, //$this->input->post('ingreso_moneda'),
                'ingreso_concepto' => $glosa, //$this->input->post('ingreso_concepto'),
                'ingreso_fecha' => $this->input->post('ingreso_fecha'),
                'ingreso_tc' => $ingreso_tc,
                'forma_id' => $this->input->post('select_forma_pago'),
                'ingreso_glosa' => $this->input->post('ingreso_glosa'),
                'banco_id' => $el_banco,
            );
            $ingreso_id = $this->Ingreso_model->add_ingreso($params);
            $sql = "UPDATE parametros SET parametro_numrecing=parametro_numrecing+1 WHERE parametro_id = '1'"; 
            $this->db->query($sql);

            $params = array(
                'ingreso_id' => $ingreso_id,
            );
            $this->Pedido_model->update_pedido($pedido_id,$params);
        }
        //**************** fin contenido ***************
        }
        
    }
    
    
    /*
     * Registrar pedido
     */
    function ingresarproducto()
    {
        $data['sistema'] = $this->sistema;
       if($this->acceso(30)) {
        //**************** inicio contenido ***************            $usuario_id = 1;    
        
        
        $pedido_id = $this->input->post('pedido_id');
        $producto_id = $this->input->post('producto_id');
        $cantidad = $this->input->post('cantidad'); 
        $descuento = $this->input->post('descuento'); 
        $preferencia = $this->input->post('preferencia'); 
        $precio = $this->input->post('precio'); 
            
                
        $sql = "insert into detalle_pedido(
                pedido_id,
                producto_id,
                detalleped_codigo,
                detalleped_foto,
                detalleped_nombre,
                detalleped_unidad,
                detalleped_costo,
                detalleped_cantidad,
                detalleped_precio,
                detalleped_descuento,
                detalleped_subtotal,
                detalleped_total,
                detalleped_preferencia
                )
                (
                select
                ".$pedido_id.",
                producto_id,
                producto_codigo,
                producto_foto,
                producto_nombre,
                producto_unidad,
                producto_costo,
                ".$cantidad.",
                ".$precio." - ".$descuento.",
                 0,
                ".$cantidad." * (".$precio." - ".$descuento."),
                ".$cantidad." * (".$precio." - ".$descuento."),
                '".$preferencia."'
                from producto where producto_id = ".$producto_id."
                )";
        $this->Pedido_model->ejecutar($sql);
        redirect('pedido/pedidoabierto/'.$pedido_id);
        		
        //**************** fin contenido ***************
        }
    }

    /*
     * Adding a new pedido
     */
    function add()
    {   
        $data['sistema'] = $this->sistema;
        if($this->acceso(31)) {
        //**************** inicio contenido ***************  
                
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'estado_id' => $this->input->post('estado_id'),
				'cliente_id' => $this->input->post('cliente_id'),
				'pedido_fecha' => $this->input->post('pedido_fecha'),
				'pedido_subtotal' => $this->input->post('pedido_subtotal'),
				'pedido_descuento' => $this->input->post('pedido_descuento'),
				'pedido_total' => $this->input->post('pedido_total'),
				'pedido_glosa' => $this->input->post('pedido_glosa'),
				'pedido_fechaentrega' => $this->input->post('pedido_fechaentrega'),
				'pedido_horaentrega' => $this->input->post('pedido_horaentrega'),
            );
            
            $pedido_id = $this->Pedido_model->add_pedido($params);
            redirect('pedido/index');
        }
        else
        {
			$this->load->model('Estado_model');
			$data['all_estado'] = $this->Estado_model->get_all_estado();

			$this->load->model('Cliente_model');
			$data['all_cliente'] = $this->Cliente_model->get_all_cliente();
            $data['page_title'] = "Pedido";
            $data['_view'] = 'pedido/add';
            $this->load->view('layouts/main',$data);
        }
        		
        //**************** fin contenido ***************
        }
        			          
    }  

    /*
     * Editing a pedido
     */
    function edit($pedido_id)
    {   
        $data['sistema'] = $this->sistema;
        if($this->acceso(33)) {
        //**************** inicio contenido ***************    
        // check if the pedido exists before trying to edit it
        $data['pedido'] = $this->Pedido_model->get_pedido($pedido_id);
        
        if(isset($data['pedido']['pedido_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'estado_id' => $this->input->post('estado_id'),
					'cliente_id' => $this->input->post('cliente_id'),
					'pedido_fecha' => $this->input->post('pedido_fecha'),
					'pedido_subtotal' => $this->input->post('pedido_subtotal'),
					'pedido_descuento' => $this->input->post('pedido_descuento'),
					'pedido_total' => $this->input->post('pedido_total'),
					'pedido_glosa' => $this->input->post('pedido_glosa'),
					'pedido_fechaentrega' => $this->input->post('pedido_fechaentrega'),
					'pedido_horaentrega' => $this->input->post('pedido_horaentrega'),
                );

                $this->Pedido_model->update_pedido($pedido_id,$params);            
                redirect('pedido/index');
            }
            else
            {
				$this->load->model('Estado_model');
				$data['all_estado'] = $this->Estado_model->get_all_estado();

				$this->load->model('Cliente_model');
				$data['all_cliente'] = $this->Cliente_model->get_all_cliente();
                $data['page_title'] = "Pedido";
                $data['_view'] = 'pedido/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The pedido you are trying to edit does not exist.');
        
        		
        //**************** fin contenido ***************
        			}
    } 

    /*
     * Deleting pedido
     */
    function remove($pedido_id)
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(34)) {
        //**************** inicio contenido ***************    
        
        if($pedido_id>0)
        {
            $this->Pedido_model->delete_pedido($pedido_id);
            redirect('pedido/index');
        }
        else
            show_error('El pedido que intenta eliminar, no existe..!');
        
        		
        //**************** fin contenido ***************
        			}
        			    
    }
    
    function pedido_a_ventas(){
        
        $data['sistema'] = $this->sistema;
        if($this->acceso(30)){ //12 ventas o 30 pedidos
        //**************** inicio contenido ***************    
        $usuario_id = $this->session_data['usuario_id'];
       
        
        
        if ($this->input->is_ajax_request()){
            
            $pedido_id = $this->input->post('pedido_id');
            $moneda = $this->Moneda_model->get_moneda(2); //Obtener moneda extrangera
            $tipotrans_id = $this->input->post('tipotrans_id');
            $venta_total = $this->input->post('pedido_total');
            $cuotas = 1;
            $cuota_inicial = 0;
            
            
            $sql = "insert into venta(forma_id, tipotrans_id, usuario_id, cliente_id, moneda_id, estado_id, 
            venta_fecha, venta_hora, venta_subtotal, venta_descuento, venta_total, venta_efectivo, 
            venta_cambio, venta_glosa, venta_comision, venta_tipocambio, detalleserv_id,entrega_estadoid, pedido_id, usuarioprev_id)

            (select 1 as forma_id,".$tipotrans_id.", ".$usuario_id.", cliente_id, 1 as moneda_id, 1 as estado_id, 
            date(now()) as venta_fecha, time(now()) as venta_hora, pedido_subtotal as venta_subtotal, pedido_descuento as venta_descuento, pedido_total as venta_total, pedido_total as venta_efectivo, 
            0 as venta_cambio, pedido_glosa as venta_glosa, 0 as venta_comision,1 as venta_tipocambio,'' as  detalleserv_id, 1 as entrega_estadoid, ".$pedido_id.", usuario_id
            from pedido
            where pedido_id=".$pedido_id." ) ";            
            $venta_id = $this->Pedido_model->ejecutar($sql);
                 
            $sql = "insert into detalle_venta
                    (producto_id, venta_id, moneda_id, detalleven_codigo, detalleven_cantidad, 
                    detalleven_unidad, detalleven_costo, detalleven_precio, detalleven_subtotal, detalleven_descuento,
                    detalleven_descuentoparcial,
                    detalleven_total, detalleven_caracteristicas, detalleven_preferencia, detalleven_comision, 
                    detalleven_tipocambio, usuario_id, detalleven_tc)
                    (select
                    producto_id, ".$venta_id." as venta_id, 1 as moneda_id, detalleped_codigo, detalleped_cantidad,
                    detalleped_unidad, detalleped_costo, detalleped_precio, detalleped_subtotal, detalleped_descuento,
                    detalleped_descuentoparcial,
                    detalleped_total,'' as detalleven_caracteristicas, detalleped_preferencia, detalleped_comision,
                    1 as detalleven_tipocambio, ".$usuario_id.", ".$moneda['moneda_tc']."
                    from detalle_pedido
                    where pedido_id = ".$pedido_id.")";
            $detalleven_id = $this->Pedido_model->modificar($sql);
            
            
            
            //actualizar el estado de la del pedido
            $sql = "update pedido set estado_id = 13 where pedido_id = ".$pedido_id; //como vendido y entregado
            echo $sql;
            
            $pedido_idx = $this->Pedido_model->modificar($sql);
            
            
                if($tipotrans_id == 2) //Si la transaccion es a credito
                {            
                    //$credito_id =  
                    $estado_id =  8; //8 pendiente 9 cancelado
                    $compra_id =  0;
                    $venta_id =  $venta_id; //
                    $credito_monto =  $venta_total; //
                    $credito_cuotainicial =  0;
                    $credito_interesproc =  0;
                    $credito_interesmonto =  0; //revisar
                    $credito_numpagos =  $cuotas;
                    $credito_fechalimite =  "date_add(date(now()), INTERVAL +1 WEEK)";
                    $credito_fecha = date('Y-m-d');
                    $time = time();
                    $credito_hora =  date("H:i:s", $time);
                    $credito_tipo = 1; // 1- ventas 2 - compras

                    $cuotas       = 1; //$this->input->post('cuotas');
                    $interes       = 0; //$this->input->post('interes');
                    $modalidad    = "MENSUAL"; //$this->input->post('modalidad');
                    $dia_pago     = date('d');
                    $fecha_inicio = $credito_fechalimite;

                    $sql = "insert  into credito(estado_id,compra_id,venta_id,credito_monto,credito_cuotainicial,credito_interesproc,credito_interesmonto,credito_numpagos,credito_fechalimite,credito_fecha,credito_hora,credito_tipo) value(".
                            $estado_id.",".$compra_id.",".$venta_id.",".$credito_monto.",".$credito_cuotainicial.",".$credito_interesproc.",".$credito_interesmonto.",".$credito_numpagos.",'".$credito_fechalimite."','".$credito_fecha."','".$credito_hora."',".$credito_tipo.")";
                    $credito_id = $this->Venta_model->ejecutar($sql);// cargar los productos del detalle_aux al detalle_venta


                    $estado_id =  8; //8 pendiente 9 cancelado
                    $cuota_numcuota = 1;
                    $cuota_capital = $venta_total - $cuota_inicial;
                    $cuota_interes = ($venta_total - $cuota_inicial)*($credito_interes/100);
                    $cuota_moradias = 0;
                    $cuota_multa = 0;
                    $cuota_subtotal =  $venta_total - $cuota_inicial;
                    $cuota_descuento = 0;
                    $cuota_total = $venta_total - $cuota_inicial+$cuota_interes;

                    $cuota_cancelado = 0;
                    $cuota_fecha = "'1900-01-01'";
                    $cuota_hora = "'00:00'";
                    $cuota_numercibo =  0;
                    $cuota_saldo = $venta_total - $cuota_inicial;
                    $cuota_glosa = "''";
                    $cuota_saldocredito = $venta_total - $cuota_inicial;

                    $dias_mora = 0;
                    $multa = 0;
                    $descuento = 0;
                    $cancelado = 0;
                    $credito_monto = $venta_total - $cuota_inicial;
                    $numcuota = $cuotas; //numero de cuotas
                    $patron = ($numcuota*0.5) + 0.5;
                    $cuota_capital = ($credito_monto)/$numcuota;   // bien         
                    $fijo = $patron * $credito_monto * ($credito_interes/100/$numcuota);
                    $cuota_subtotal = $fijo + $cuota_capital + $dias_mora + $multa;
                    $total = $cuota_subtotal - $descuento;
                    $saldo_deudor = $credito_monto;

                    $siguiente= 0;
                    $cuota_fechalimite = $fecha_inicio;

                    $cuota_fechalimite = $fecha_inicio;


                    if ($modalidad == "MENSUAL") $intervalo = 30; //si los pagos son mensuales
                    else $intervalo = 7; //si los pagos son semanales


                        for ($i=1; $i <= $numcuota; $i++) { // ciclo para llenar las cuotas
                            $cuota_numcuota = $i;

                            $cuota_fechalimitex = (time() + ($intervalo * $i * 24 * 60 * 60 ));
                            if ($modalidad == "MENSUAL") 
                                $cuota_fechalimite = date('Y-m-'.$dia_pago, $cuota_fechalimitex);
                            else 
                                $cuota_fechalimite = date('Y-m-d', $cuota_fechalimitex); 

                            $cuota ="insert into cuota (credito_id,usuario_id,estado_id,cuota_numcuota,cuota_capital,cuota_interes,cuota_moradias,cuota_multa,cuota_descuento,cuota_cancelado,cuota_total,cuota_subtotal,cuota_fechalimite,cuota_saldo) VALUES (".
                                    $credito_id.",".$usuario_id.",".$estado_id.",".$cuota_numcuota.",".$cuota_capital.",".$fijo.",".
                                    $dias_mora.",".$multa.",".$descuento.",".$cancelado.",".$total.",".$cuota_subtotal.",'".$cuota_fechalimite."',".$saldo_deudor.")";

                            $this->Venta_model->ejecutar($cuota);

        //                    $saldo_deudor = $cuota_total - $cuota_capital;
        //                    $cuota_total = $saldo_deudor;
                            $saldo_deudor = $saldo_deudor - $cuota_capital;
                            //$cuota_total = $saldo_deudor;
                        }

                }
            
        }
        		
        //**************** fin contenido ***************
        			}
        			         
    }
    
    
    function anular_pedido(){
        
        $data['sistema'] = $this->sistema;
        if($this->acceso(34)) {
        //**************** inicio contenido ***************    
        $usuario_id = $this->session_data['usuario_id'];
        
        if ($this->input->is_ajax_request()){
            
            $pedido_id = $this->input->post('pedido_id');
            
            $sql = "update detalle_pedido set 
                     detalleped_costo = 0
                    ,detalleped_cantidad = 0
                    ,detalleped_precio = 0
                    ,detalleped_descuento = 0
                    ,detalleped_subtotal = 0
                    ,detalleped_total = 0
                    ,detalleped_comision = 0 
                     where pedido_id = ".$pedido_id;      
            //echo $sql;
            $this->Pedido_model->modificar($sql);
                 
            $sql = "update pedido set
                     estado_id = 15
                    ,pedido_subtotal = 0
                    ,pedido_descuento = 0
                    ,pedido_total = 0 
                    where pedido_id = ".$pedido_id;
            echo $sql;
            $this->Pedido_model->modificar($sql);
            
        }
        		
        //**************** fin contenido ***************
        			}
    }
    

    /*
     * Eliminar item de detalle
     */
    function eliminaritemx($detalleped_id)
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(30)) {
        //**************** inicio contenido ***************                            

        $sql = "delete from detalle_pedido where detalleped_id = ".$detalleped_id;
        $this->Pedido_model->ejecutar($sql);
        return true;
            		
        //**************** fin contenido ***************
        }
       		         
    }

    /*
     * Eliminar todos los items
     */
    function eliminartodox($pedido_id)
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(30)) {
        //**************** inicio contenido ***************            
       
        $usuario_id = $this->session_data['usuario_id'];
        $sql = "delete from detalle_pedido where pedido_id = ".$pedido_id;
        $this->Pedido_model->ejecutar($sql);
        return true;	
        //**************** fin contenido ***************
        			}
        
    }
    /*
     * incrementar cantidad de productos en el detalle
     */
    function incrementar()
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(30)) {
        //**************** inicio contenido ***************            
         
        
        $detalleped_id = $this->input->post('detalleped_id');
        $cantidad = $this->input->post('cantidad');
        $descuento = 0;
        
            $sql = "update detalle_pedido set detalleped_cantidad = detalleped_cantidad + ".$cantidad.
                    ", detalleped_subtotal = detalleped_precio * (detalleped_cantidad)".
                    ", detalleped_descuento = ".$descuento.
                    ", detalleped_total = (detalleped_precio - ".$descuento.")*(detalleped_cantidad)".
                    "  where detalleped_id = ".$detalleped_id;
            
        $this->Pedido_model->ejecutar($sql);
        return true;
            		
        //**************** fin contenido ***************
        			}

    }

    /*
     * reduce la cantidad de productos en el detalle
     */
    function reducir()
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(30)) {
        //**************** inicio contenido ***************    
        
        
        $detalleped_id = $this->input->post('detalleped_id');
        $cantidad = $this->input->post('cantidad');
        $descuento = 0;
        
                    
            $sql = "update detalle_pedido set detalleped_cantidad = detalleped_cantidad - ".$cantidad.
                    ", detalleped_subtotal = detalleped_precio * (detalleped_cantidad)".
                    ", detalleped_descuento = ".$descuento.
                    ", detalleped_total = (detalleped_precio - ".$descuento.")*(detalleped_cantidad)".
                    "  where detalleped_id = ".$detalleped_id;
            
        $this->Pedido_model->ejecutar($sql);
        return true;
            		
        //**************** fin contenido ***************
        			}
    }

    function mapa_pedido()        
    {

        //control de sesion
//        if ($this->session->userdata('perfil')=='PREVENDEDOR'){
        $data['sistema'] = $this->sistema;    
        if($this->acceso(30)) {
        //**************** inicio contenido ***************  
        
            $data['page_title'] = "Mapa de Pedidos";
            $usuario_id = $this->session_data['usuario_id']; //$this->session->userdata('id_usu');
            
            $data['all_pedido'] = $this->Pedido_model->get_mis_pedidos($usuario_id);
            //$data['puntos_referencia'] = $this->Puntos_referencia_model->get_all_puntos_referencia();
            $data['_view'] = 'pedido/mapapedidos';
            
            $this->load->view('layouts/main',$data);
            
        //**************** fin contenido ***************
        }     
    }

    function mapa_entregas()
    {
        $data['sistema'] = $this->sistema;
       if($this->acceso(30)) {
        //**************** inicio contenido ***************  
        
            $data['page_title'] = "Mapa de Entregas";
            $usuario_id = $this->session_data['usuario_id']; //$this->session->userdata('id_usu');

            $data['parametros'] = $this->Parametro_model->get_parametros();
            $data['all_pedido'] = $this->Pedido_model->get_mis_pedidos($usuario_id);
            $data['pedido_titulo'] = $this->session_data['pedido_titulo'];
            //$data['puntos_referencia'] = $this->Puntos_referencia_model->get_all_puntos_referencia();
            $data['_view'] = 'pedido/mapaentregas';
            
            $this->load->view('layouts/main',$data);
            
        //**************** fin contenido ***************
        }
        
    }

    function mapa_paraentregas()
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(30)) {
            //**************** inicio contenido ***************
            $data['page_title'] = "Mapa de Entregas";
            
            $fecha_desde = $this->input->post('fecha_desde');
            $fecha_hasta = $this->input->post('fecha_hasta');
            $usuariodist_id = $this->input->post('usuariodist_id');
            
                $usuario_id = $this->input->post('usuario_id');
            /*if ($this->session_data['tipousuario_id']==1)
                $usuario_id = $this->input->post('usuario_id');
            else
                $usuario_id = $this->session_data['usuario_id']; //$this->session->userdata('id_usu');
            */
            $data['pedido_titulo'] = $this->session_data['pedido_titulo'];
            $data['parametros'] = $this->Parametro_model->get_parametro(1);
            $data['all_pedido'] = $this->Pedido_model->get_para_mapaentregas($usuario_id, $fecha_desde, $fecha_hasta, $usuariodist_id);
            //$data['puntos_referencia'] = $this->Puntos_referencia_model->get_all_puntos_referencia();
            $data['_view'] = 'pedido/mapaentregas';
            
            $this->load->view('layouts/main',$data);
            //**************** fin contenido ***************
        }
    }

    function mapa_distribuidor()
    {
        $data['sistema'] = $this->sistema;
       if($this->acceso(30)) {
        //**************** inicio contenido ***************  
        
            $data['page_title'] = "Mapa de Entregas";
            $usuario_id = $this->session_data['usuario_id']; //$this->session->userdata('id_usu');
            
            $data['all_pedido'] = $this->Pedido_model->get_mis_pedidos($usuario_id);
            //$data['puntos_referencia'] = $this->Puntos_referencia_model->get_all_puntos_referencia();
            $data['_view'] = 'pedido/mapaentregas';
            
            $this->load->view('layouts/main',$data);
            
        //**************** fin contenido ***************
        }
        
    }
    

    function mapa_clientes($usuario_id,$dia_visita)
    {
        $data['sistema'] = $this->sistema;
       if($this->acceso(30)) {
        //**************** inicio contenido ***************  
//
//            $usuario_id = $this->session_data['usuario_id'];
//            $dia_visita = $this->input->post('dia_visita');
            
            if($dia_visita == 1){ $condicion = " and c.lun = 1"; } //lunes
            if($dia_visita == 2){ $condicion = " and c.mar = 1"; }
            if($dia_visita == 3){ $condicion = " and c.mie = 1"; }
            if($dia_visita == 4){ $condicion = " and c.jue = 1"; }
            if($dia_visita == 5){ $condicion = " and c.vie = 1"; }
            if($dia_visita == 6){ $condicion = " and c.sab = 1"; }
            if($dia_visita == 7){ $condicion = " and c.dom = 1"; }
            if($dia_visita == 0){ $condicion = " "; } //todos

            $sql="select c.*,p.pedido_id from cliente c
                  left join (select * from pedido where date(pedido_fecha) = date(now())) as p on p.cliente_id = c.cliente_id ".
                 " where c.estado_id = 1 and  c.usuario_id = ".
                  $usuario_id." ".$condicion.                    
                  " order by c.cliente_ordenvisita, c.cliente_nombre";
            $resultado = $this->Pedido_model->consultar($sql);           
           
           
            $data['page_title'] = "Mapa Clientes";
            $data['parametro'] = $this->Parametro_model->get_parametros();
            $data['pedido_titulo'] = $this->session_data['pedido_titulo'];
//            $usuario_id = $this->session_data['usuario_id']; //$this->session->userdata('id_usu');            
//            $data['all_pedido'] = $this->Pedido_model->get_mis_pedidos($usuario_id);
            $data['all_pedido'] = $resultado;
            
            $data['_view'] = 'pedido/mapaclientes';
            
            $this->load->view('layouts/main',$data);
            
        //**************** fin contenido ***************
        }
        
    }
    
    

    function eliminardetalle()
    {      
        $data['sistema'] = $this->sistema;
        if($this->acceso(30)){ //12 ventas o 30 pedidos
        //**************** inicio contenido ***************       
        
        $usuario_id = $this->session_data['usuario_id'];
        
        $sql =  "delete from detalle_venta_aux where usuario_id=".$usuario_id;
        $this->Venta_model->ejecutar($sql);
        return true;
    
        //**************** fin contenido ***************
        }
        		   
    }    
    

    /*
     * Eliminar item de detalle
     */
    function eliminaritem($detalleven_id)
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(30)){ //12 ventas o 30 pedidos
        //**************** inicio contenido ***************        

        $sql = "delete from detalle_venta_aux where detalleven_id = ".$detalleven_id;
        $this->Venta_model->ejecutar($sql);
        return true;
            		
        //**************** fin contenido ***************
        }
        			
    }

    /*
     * Eliminar todos los items
     */
    function eliminartodo()
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(12)||$this->acceso(30)){ //12 ventas o 30 pedidos
        //**************** inicio contenido ***************        
        $usuario_id = $this->session_data['usuario_id'];
        $sql = "delete from detalle_venta_aux where usuario_id = ".$usuario_id;
        $this->Venta_model->ejecutar($sql);
        return true;
            		
        //**************** fin contenido ***************
        }
    }
    

    /*
     * registro de recorrido
     */
    function registrar_recorrido()
    {
        $data['sistema'] = $this->sistema;
//        if($this->acregistrarpedidoceso(12)){
        //**************** inicio contenido ***************        
        $usuario_id = $this->session_data['usuario_id'];
        
        $tiporespuesta_id = $this->input->post("tiporespuesta_id");
        $pedido_id = $this->input->post("pedido_id");
        $cliente_id = $this->input->post("cliente_id");
        $usuario_id = $this->input->post("usuario_id");
        $recorrido_fecha = "'".$this->input->post("recorrido_fecha")."'";
        $recorrido_hora = "'".$this->input->post("recorrido_hora")."'";
        $recorrido_detalleresp = "'".$this->input->post("recorrido_detalleresp")."'";


        $sql = "insert into recorrido_usuario(tiporespuesta_id,
                pedido_id,cliente_id,usuario_id,recorrido_fecha,
                recorrido_hora,recorrido_detalleresp) value(".
                $tiporespuesta_id.",".
                $pedido_id.",".
                $cliente_id.",".
                $usuario_id.",".
                $recorrido_fecha.",".
                $recorrido_hora.",".
                $recorrido_detalleresp.")";
        
        $this->Pedido_model->ejecutar($sql);// cargar los productos del detalle_aux al detalle_venta
            		
        //**************** fin contenido ***************
//        }
        			
        
    }
    

    /*
     * Lista de clientes asigandos a un usuario prevendedor
     */
    function misclientes()
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(12)||$this->acceso(30)){ //12 ventas o 30 pedidos

        //**************** inicio contenido ***************        
        
            $usuario_id = $this->session_data['usuario_id'];
            $data['tipousuario_id'] = $this->session_data['tipousuario_id'];
            $data['usuario'] = $this->Usuario_model->get_todos_usuario(); // para el select
            $data['usuario_id'] = $usuario_id;            
            $data['pedido_titulo'] = $this->session_data['pedido_titulo'];
            $data['_view'] = 'pedido/misclientes';
            $this->load->view('layouts/main',$data);
            		
        //**************** fin contenido ***************
        }        			
        
    }

    /*
     * Lista de clientes asigandos a un usuario prevendedor
     */
    function buscar_clientes()
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(12)||$this->acceso(30)){ //12 ventas o 30 pedidos

        //**************** inicio contenido ***************        
        
            //$usuario_id = $this->session_data['usuario_id'];
            $usuario_id = $this->input->post('usuario_id');
            $dia_visita = $this->input->post('dia_visita');
            
            if($dia_visita == 1){ $condicion = " and c.lun = 1"; } //lunes
            if($dia_visita == 2){ $condicion = " and c.mar = 1"; }
            if($dia_visita == 3){ $condicion = " and c.mie = 1"; }
            if($dia_visita == 4){ $condicion = " and c.jue = 1"; }
            if($dia_visita == 5){ $condicion = " and c.vie = 1"; }
            if($dia_visita == 6){ $condicion = " and c.sab = 1"; }
            if($dia_visita == 7){ $condicion = " and c.dom = 1"; }
            if($dia_visita == 0){ $condicion = " "; } //todos

//            $sql="select c.*,p.pedido_id from cliente c
//                  left join (select * from pedido where date(pedido_fecha) = date(now())) as p on p.cliente_id = c.cliente_id ".
//                 " where c.estado_id = 1 and  c.usuario_id = ".
//                  $usuario_id." ".$condicion.                    
//                  " order by c.cliente_ordenvisita, c.cliente_nombre";
            
        
            $sql="select c.*,p.pedido_id,p.tiporespuesta_id from cliente c
                  left join (select * from recorrido_usuario where recorrido_fecha = date(now())) as p on p.cliente_id = c.cliente_id ".
                 " where c.estado_id = 1 and  c.usuario_id = ".
                  $usuario_id." ".$condicion.                    
                  " order by c.cliente_ordenvisita, c.cliente_nombre";
            
            $resultado = $this->Pedido_model->consultar($sql);
            echo json_encode($resultado);
            		
        //**************** fin contenido ***************
        }
        
    }
    

    /*
     * Lista de clientes asigandos a un usuario prevendedor
     */
    function buscar_cliente_usuario()
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(12)||$this->acceso(30)){ //12 ventas o 30 pedidos

        //**************** inicio contenido ***************        
        
            $usuario_id = $this->input->post('usuario_id');

            $sql="select * from cliente where usuario_id = ".$usuario_id;            
            $resultado = $this->Pedido_model->consultar($sql);
            echo json_encode($resultado);
            		
        //**************** fin contenido ***************
        }
        
    }
    

    /*
     * Lista de clientes asigandos a un usuario prevendedor
     */
    function cambiar_orden()
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(12)||$this->acceso(30)){ //12 ventas o 30 pedidos

        //**************** inicio contenido ***************        
        
            $cliente_id = $this->input->post('cliente_id');
            $numero_orden = $this->input->post('numero_orden');

            $sql="update cliente set cliente_ordenvisita = ".$numero_orden.
                  " where cliente_id = ".$cliente_id;
            
            $this->Pedido_model->ejecutar($sql);
            echo true;
            		
        //**************** fin contenido ***************
        }
        
    }
    /*
    * mapa de clientes para pedidos
    */
    function mapa_depedidos($zona_id)
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(30)) {
            //**************** inicio contenido ***************
            $data['page_title'] = "Mapa de pedidos";
            //$usuario_id = $this->session_data['usuario_id']; //$this->session->userdata('id_usu');

            //$fecha_desde = $this->input->post("fecha_desde");
            //$fecha_hasta = $this->input->post("fecha_hasta");
            //$zona_id = $this->input->post("zona_busqueda");
            if(isset($zona_id)){

                $data['parametros'] = $this->Parametro_model->get_parametro(1);
                
                $data['all_cliente'] = $this->Cliente_model->get_clientes_por_pedidos($zona_id);
                $data['zona'] = $this->Categoria_clientezona_model->get_categoria_clientezona($zona_id);
                //$data['puntos_referencia'] = $this->Puntos_referencia_model->get_all_puntos_referencia();
                $data['_view'] = 'pedido/mapa_depedidos';

                $this->load->view('layouts/main',$data);

            }
            else{
                redirect('pedido');
            }
                //**************** fin contenido ***************

        }
    }
    
    function mapa_seg_entregas($usuario_id, $fecha_desde, $fecha_hasta,$select_pedido){
        
            $data['sistema'] = $this->sistema;
        // if($this->acceso(30)) {
            //**************** inicio contenido ***************  
                $data['page_title'] = "Mapa";
                // echo "hola $fecha_hasta $fecha_desde";
                if($select_pedido == 1 || $select_pedido == 6){
                    $fecha_desde = date("Y-m-d",strtotime($fecha_desde."- $select_pedido day"));
                }else{
                    if($select_pedido == 2 || $select_pedido == 7){
                        $fecha_desde = date("Y-m-d",strtotime($fecha_desde."- $select_pedido day"));
                        $aux = $select_pedido-1;
                        $fecha_hasta = date("Y-m-d",strtotime($fecha_hasta."- $aux day"));
                    }else{
                        if($select_pedido == 3 || $select_pedido == 8){
                            $fecha_desde = date("Y-m-d",strtotime($fecha_desde."- 1 week"));
                        }else{
                            if($select_pedido == 4 || $select_pedido == 9){
                                $fecha_desde = date("Y-m-d",strtotime($fecha_desde."- 5 year"));
                            }
                        }
                    }
                }
                $data['parametros'] = $this->Parametro_model->get_parametro(1);
                $data['all_pedido'] = $this->Pedido_model->get_para_entregas($usuario_id, $fecha_desde, $fecha_hasta);

                $data['_view'] = 'pedido/mapa_seguimiento';
                $this->load->view('layouts/main',$data);
                
            //**************** fin contenido ***************
        // }
    }
    /*
    * mapa de pedidos por fechas, por prevendedor/vendedor
    */
    function mapa_pedidos()
    {
        $data['sistema'] = $this->sistema;
        if($this->acceso(30)) {
            $data['page_title'] = "Mapa de pedidos";
            $data['parametros'] = $this->Parametro_model->get_parametro(1);

            //$data['all_cliente'] = $this->Cliente_model->get_clientes_por_pedidos($zona_id);
            $data['all_usuario'] = $this->Usuario_model->get_all_usuario_activo();
            //$data['puntos_referencia'] = $this->Puntos_referencia_model->get_all_puntos_referencia();
            $data['_view'] = 'pedido/mapa_pedidos';
            $this->load->view('layouts/main',$data);
        }
    }
    function pedidos_pendientes(){
        
        $data['sistema'] = $this->sistema;
        if($this->acceso(30)) {
            if ($this->input->is_ajax_request()) {
                $usuario_id = $this->input->post('usuario_id');
                $desde      = $this->input->post('desde');
                $hasta      = $this->input->post('hasta');
                $resultado = $this->Pedido_model->get_pedidos_pendientes($usuario_id, $desde, $hasta);
                echo json_encode($resultado);
            }else{
                show_404();
            }
        }
    }
    function mapapedido_a_ventas(){
        
        $data['sistema'] = $this->sistema;
        if($this->acceso(30)){ //12 ventas o 30 pedidos
            //**************** inicio contenido ***************    
            $usuario_id = $this->session_data['usuario_id'];
            if ($this->input->is_ajax_request()){

                $pedido_id = $this->input->post('pedido_id');
                
                $moneda = $this->Moneda_model->get_moneda(2); //Obtener moneda extrangera
                $sql = "insert into venta(forma_id, tipotrans_id, usuario_id, cliente_id, moneda_id, estado_id, 
                venta_fecha, venta_hora, venta_subtotal, venta_descuento, venta_total, venta_efectivo, 
                venta_cambio, venta_glosa, venta_comision, venta_tipocambio, detalleserv_id,entrega_estadoid, pedido_id, usuarioprev_id)

                (select 1 as forma_id,1 as tipotrans_id, ".$usuario_id.", cliente_id, 1 as moneda_id, 1 as estado_id, 
                date(now()) as venta_fecha, time(now()) as venta_hora, pedido_subtotal as venta_subtotal, pedido_descuento as venta_descuento, pedido_total as venta_total, pedido_total as venta_efectivo, 
                0 as venta_cambio, pedido_glosa as venta_glosa, 0 as venta_comision,1 as venta_tipocambio,'' as  detalleserv_id, 1 as entrega_estadoid, ".$pedido_id.", usuario_id
                from pedido
                where pedido_id=".$pedido_id." ) ";            
                $venta_id = $this->Pedido_model->ejecutar($sql);

                $sql = "insert into detalle_venta
                        (producto_id, venta_id, moneda_id, detalleven_codigo, detalleven_cantidad, 
                        detalleven_unidad, detalleven_costo, detalleven_precio, detalleven_subtotal, detalleven_descuento, 
                        detalleven_total, detalleven_caracteristicas, detalleven_preferencia, detalleven_comision, 
                        detalleven_tipocambio, usuario_id, detalleven_tc)
                        (select
                        producto_id, ".$venta_id." as venta_id, 1 as moneda_id, detalleped_codigo, detalleped_cantidad,
                        detalleped_unidad, detalleped_costo, detalleped_precio, detalleped_subtotal, detalleped_descuento,
                        detalleped_total,'' as detalleven_caracteristicas, detalleped_preferencia, detalleped_comision,
                        1 as detalleven_tipocambio, ".$usuario_id.", ".$moneda['moneda_tc']."
                        from detalle_pedido
                        where pedido_id = ".$pedido_id.")";
                $detalleven_id = $this->Pedido_model->modificar($sql);



                //actualizar el estado de la del pedido
                $sql = "update pedido set estado_id = 13 where pedido_id = ".$pedido_id; //como vendido y entregado
                //echo $sql;

                $pedido_idx = $this->Pedido_model->modificar($sql);
                echo json_encode("ok");
            }
        }
    }
    /* entregar pedido desde mapa de pedidos */
    function entregarpedido(){
        
        $data['sistema'] = $this->sistema;
        //if($this->acceso(30)) {
            if ($this->input->is_ajax_request()) {
                $venta_id = $this->input->post('venta_id');
                $venta_fechaentrega=date('Y-m-d'); 
                $venta_horaentrega=date('H:i:s');
                $entrega_id = 2; //<-- pedido entregado
                
                $params = array(
                    'venta_fechaentrega' => $venta_fechaentrega,
                    'venta_horaentrega' => $venta_horaentrega,
                    'entrega_id' => $entrega_id,
                );
                $this->Venta_model->update_venta($venta_id,$params);
                
                echo json_encode("ok");
            }else{
                show_404();
            }
        //}
    }
    /* modifica la fecha y hora de un pedido!.. */
    function modificar_fechapedido()
    {
        if ($this->input->is_ajax_request()) {
            $pedido_id = $this->input->post('pedido_id');
            $pedido_fecha = $this->input->post('pedido_fecha');
            $pedido_hora  = $this->input->post('pedido_hora');
            
            $params = array(
                'pedido_fecha' => $this->input->post('pedido_fecha')." ".$this->input->post('pedido_hora'),
            );
            $this->Pedido_model->update_pedido($pedido_id, $params);
            echo json_encode("ok");
        }else{                 
            show_404();
        }              
    }
}