<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Reporte_ing_egr_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
function get_reportes($fecha1, $fecha2, $usuario_id)
{
    if($usuario_id == 0){
      $cadusuario1 = "";
      $cadusuario2 = "";
      $cadusuario3 = "";
      $cadusuario4 = "";
      $cadusuario5 = "";
      $cadusuario6 = "";
    }else{
      $cadusuario1 = " and v.usuario_id = ".$usuario_id." ";
      $cadusuario2 = " and c.usuario_id = ".$usuario_id." ";
      $cadusuario3 = " and i.usuario_id = ".$usuario_id." ";
      $cadusuario4 = " and e.usuario_id = ".$usuario_id." ";
      $cadusuario5 = " and c.usuario_id = ".$usuario_id." ";
      $cadusuario6 = " and c.usuario_id = ".$usuario_id." ";

    }
        $ingresos = $this->db->query("
                  
      select 
            u.usuario_nombre as usuario, v.venta_fecha as fecha, p.producto_nombre as detalle,
            d.detalleven_total as ingreso, 0 as egreso,
            d.detalleven_total-(d.detalleven_costo * d.detalleven_cantidad) as utilidad
      from
            venta v, detalle_venta d, producto p, usuario u
      where
            v.venta_fecha >= '".$fecha1."'
            and v.venta_fecha <= '".$fecha2."'
            and v.venta_id = d.venta_id
            and d.producto_id = p.producto_id
            and v.usuario_id = u.usuario_id
            ".$cadusuario1."
      UNION
      (select 
            u.usuario_nombre as usuario, c.compra_fecha as fecha, p.producto_nombre as detalle,
            0 as ingreso, d.detallecomp_total as egreso,
            0 as utilidad
      from
            compra c, detalle_compra d, producto p, usuario u
      where
            c.compra_fecha >= '".$fecha1."'
            and c.compra_fecha <= '".$fecha2."'
            and c.compra_id = d.compra_id
            and d.producto_id = p.producto_id
            and c.usuario_id = u.usuario_id
            ".$cadusuario2.")
      UNION
      (select 
            u.usuario_nombre as usuario, i.ingreso_fecha as fecha, i.ingreso_nombre as detalle,
            i.ingreso_monto as ingreso, 0 as egreso,
            0 as utilidad
      from
            ingresos i, usuario u
      where
            i.ingreso_fecha >= '".$fecha1."'
            and i.ingreso_fecha <= '".$fecha2."'
            and i.usuario_id = u.usuario_id
            ".$cadusuario3.")
      UNION
      (select 
            u.usuario_nombre as usuario, e.egreso_fecha as fecha, e.egreso_nombre as detalle,
            0 as ingreso, e.egreso_monto as egreso,
            0 as utilidad
      from
            egresos e, usuario u
      where
            e.egreso_fecha >= '".$fecha1."'
            and e.egreso_fecha <= '".$fecha2."'
            and e.usuario_id = u.usuario_id
            ".$cadusuario4.")
      UNION
      (select 
            u.usuario_nombre as usuario, c.cuota_fecha as fecha, concat('Pago por credito N°: ', c.credito_id) as detalle,
            0 as ingreso, c.cuota_total as egreso,
            0 as utilidad
      from
            cuota c, credito cr, usuario u
      where
            c.cuota_fecha >= '".$fecha1."'
            and c.cuota_fecha <= '".$fecha2."'
            and c.credito_id = cr.credito_id
            and cr.credito_tipo = 1
            and c.usuario_id = u.usuario_id
            ".$cadusuario5.")
      UNION
      (select 
            u.usuario_nombre as usuario, c.cuota_fecha as fecha, concat('Cuota credito N°: ', c.credito_id) as detalle,
            c.cuota_total as ingreso, 0 as egreso,
            c.cuota_interes as utilidad
      from
            cuota c, credito cr, usuario u
      where
            c.cuota_fecha >= '".$fecha1."'
            and c.cuota_fecha <= '".$fecha2."'
            and c.credito_id = cr.credito_id
            and cr.credito_tipo = 2
            and c.usuario_id = u.usuario_id
            ".$cadusuario6.")




        ")->result_array();
        /*$ingresos = $this->db->query("
            SELECT v.venta_fecha AS Fecha, p.producto_nombre as Detalle, d.detalleven_total as Ingreso, 0 as Egreso, d.detalleven_total-(d.detalleven_costo * d.detalleven_cantidad)  as Utilidad
            FROM venta v, detalle_venta d, producto p
            WHERE v.venta_id = d.venta_id and d.producto_id = p.producto_id
            UNION
            SELECT c.compra_fecha AS Fecha, p.producto_nombre as Detalle,0 as Ingreso, d.detallecomp_total as Egreso,0 as Utilidad
            FROM compra c, detalle_compra d, producto p
            WHERE c.compra_id =d.compra_id and d.producto_id = p.producto_id
            UNION

            SELECT date (i.ingreso_fecha) AS Fecha, i.ingreso_concepto as Detalle, i.ingreso_monto as Ingreso,0 as Egreso, 0 as Utilidad
            FROM ingresos i
            UNION

            SELECT date (e.egreso_fecha) AS Fecha, e.egreso_concepto as Detalle, 0 as Ingreso,e.egreso_monto as Egreso, 0 as Utilidad
            FROM egresos e




        ")->result_array(); */

        return $ingresos;
    }
}
?>