<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipo_transaccion extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tipo_transaccion_model');
    } 

    /*
     * Listing of tipo_transaccion
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tipo_transaccion/index?');
        $config['total_rows'] = $this->Tipo_transaccion_model->get_all_tipo_transaccion_count();
        $this->pagination->initialize($config);

        $data['tipo_transaccion'] = $this->Tipo_transaccion_model->get_all_tipo_transaccion($params);
        
        $data['_view'] = 'tipo_transaccion/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tipo_transaccion
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('tipotrans_nombre','Tipotrans Nombre','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'tipotrans_nombre' => $this->input->post('tipotrans_nombre'),
            );
            
            $tipo_transaccion_id = $this->Tipo_transaccion_model->add_tipo_transaccion($params);
            redirect('tipo_transaccion/index');
        }
        else
        {            
            $data['_view'] = 'tipo_transaccion/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tipo_transaccion
     */
    function edit($tipotrans_id)
    {   
        // check if the tipo_transaccion exists before trying to edit it
        $data['tipo_transaccion'] = $this->Tipo_transaccion_model->get_tipo_transaccion($tipotrans_id);
        
        if(isset($data['tipo_transaccion']['tipotrans_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('tipotrans_nombre','Tipotrans Nombre','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'tipotrans_nombre' => $this->input->post('tipotrans_nombre'),
                );

                $this->Tipo_transaccion_model->update_tipo_transaccion($tipotrans_id,$params);            
                redirect('tipo_transaccion/index');
            }
            else
            {
                $data['_view'] = 'tipo_transaccion/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tipo_transaccion you are trying to edit does not exist.');
    } 

    /*
     * Deleting tipo_transaccion
     */
    function remove($tipotrans_id)
    {
        $tipo_transaccion = $this->Tipo_transaccion_model->get_tipo_transaccion($tipotrans_id);

        // check if the tipo_transaccion exists before trying to delete it
        if(isset($tipo_transaccion['tipotrans_id']))
        {
            $this->Tipo_transaccion_model->delete_tipo_transaccion($tipotrans_id);
            redirect('tipo_transaccion/index');
        }
        else
            show_error('The tipo_transaccion you are trying to delete does not exist.');
    }
    
}
