<?php 
/*
 Generated by Manuigniter v2.0 
 www.manuigniter.com
*/
class Viaje extends CI_Controller{

    private $sistema;
    private $parametros;

    public function __construct()
    {
        parent::__construct();

        $this->load->model('Viaje_model');
        $this->load->model('Sistema_model');
        $this->load->model('Parametro_model');
        $this->load->model('Empresa_model');
        $this->load->model('Moneda_model');
        $this->load->model('Venta_model');

        $this->load->library('form_validation');
        $this->load->helper(array('form', 'url'));

        $this->sistema = $this->Sistema_model->get_sistema();
        $parametro = $this->Parametro_model->get_parametros();
        $this->parametros = isset($parametro[0]) ? $parametro[0] : array();

        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        } else {
            redirect('', 'refresh');
        }
    } 
 /*
* Listing of viaje
 */
public function index()
{
    $data['sistema']   = $this->sistema;
    $data['parametro'] = $this->parametros;

    $this->load->library('pagination');

    $config['base_url'] = site_url('viaje/index');
    $config['total_rows'] = $this->Viaje_model->get_all_viaje_count();
    $config['per_page'] = 25;
    $config['uri_segment'] = 3;

    $this->pagination->initialize($config);

    $page = ($this->uri->segment(3)) ? $this->uri->segment(3) : 0;

    $params = array(
        'limit'  => $config['per_page'],
        'offset' => $page
    );

    $data['noof_page'] = $page;

    // CAMBIO IMPORTANTE
    $data['viaje'] = $this->Viaje_model->get_viajes_con_pasajes($params);

    $data['_view'] = 'viaje/index';
    $this->load->view('layouts/main', $data);
}
 /*
  * Adding a new viaje
  */
public function add()
{
    $data['sistema'] = $this->sistema;
    $data['parametro'] = $this->parametros;        
    $this->_cargar_datos_formulario($data);
    $this->_set_validation_rules();

    if ($this->form_validation->run()) {

        $params = $this->_get_post_data();

        // extraer vehiculo_id desde params
        $vehiculo_id = $params['vehiculo_id'];

        $viaje_id = $this->Viaje_model->add_viaje($params);

        if ($viaje_id) {

            $this->session->set_flashdata(
                'alert_msg',
                '<div class="alert alert-success text-center">Viaje registrado correctamente.</div>'
            );

            // Generar pasajes
            $this->generar_pasajes($viaje_id, $vehiculo_id);

            redirect('viaje/index');
        }
    }

    $data['_view'] = 'viaje/add';
    $this->load->view('layouts/main', $data);
}
  /*
  * Editing a viaje
 */
    public function edit($viaje_id = null)
    {
        $data['sistema'] = $this->sistema;
        $data['parametro'] = $this->parametros;
        $data['viaje'] = $this->Viaje_model->get_viaje($viaje_id);

        if (!isset($data['viaje']['viaje_id'])) {
            show_error('El viaje que intenta editar no existe.');
        }

        $this->_cargar_datos_formulario($data);
        $this->_set_validation_rules();

        if ($this->form_validation->run()) {
            $params = $this->_get_post_data();

            $ok = $this->Viaje_model->update_viaje($viaje_id, $params);

            if ($ok) {
                $this->session->set_flashdata('alert_msg', '<div class="alert alert-success text-center">Viaje actualizado correctamente.</div>');
                redirect('viaje/index');
            }
        }

        $data['_view'] = 'viaje/edit';
        $this->load->view('layouts/main', $data);
    }
/*
  * Deleting viaje
  */
    public function remove($viaje_id)
    {
        $viaje = $this->Viaje_model->get_viaje($viaje_id);

        if (!isset($viaje['viaje_id'])) {
            show_error('El viaje que intenta eliminar no existe.');
        }

        $this->Viaje_model->delete_viaje($viaje_id);
        $this->session->set_flashdata('alert_msg', '<div class="alert alert-success text-center">Viaje eliminado correctamente.</div>');
        redirect('viaje/index');
    }
  /*
  * View more a viaje
 */
 public function view_more($viaje_id)
 {   
     $data['sistema'] = $this->sistema;
try{
   $data['viaje'] = $this->Viaje_model->get_viaje($viaje_id);
     if(isset($data['viaje']['viaje_id']))
      {
              $data['_view'] = 'viaje/view_more';
              $this->load->view('layouts/main',$data);
      }
      else
        show_error('The viaje you are trying to view more does not exist.');
    } catch (Exception $ex) {
    throw new Exception('Viaje Controller : Error in View more function - ' . $ex);
  }  
} 
 /*
* Listing of viaje
 */
public function search_by_clm()
{
     $data['sistema'] = $this->sistema;
    $column_name= $this->input->post('column_name');
    $value_id= $this->input->post('value_id');
     $data['noof_page'] = 0;
     $params = array();
    $data['viaje'] = $this->Viaje_model->get_all_with_asso_viaje_by_cat($column_name,$value_id);
      $data['_view'] = 'viaje/index';
      $this->load->view('layouts/main',$data);
}
  /*
  * get get_search_values_byclms by id
 */
 public function get_search_values_by_ayudante_id()
 {   
     $data['sistema'] = $this->sistema;
     $ayudante_id= $this->input->post('value');
        $this->load->model('Ayudante_model');
        $data['all_ayudante'] = $this->Ayudante_model->get_all_ayudante(); 
      $viaje = $this->Viaje_model->get_all_with_asso_viaje();
if(isset($data['all_ayudante']) && $data['all_ayudante']!=null)
                                              {
                                              foreach($data['all_ayudante'] as $v){ 
      echo          "<option value='".$v['ayudante_id']."'> ".$v['ayudante_nombres']."</option>"; 
 } 
                                              }
                                              else{
                                                        echo '<tr>No data found</tr>';
                                              }
 } 
  /*
  * get get_search_values_byclms by id
 */
 public function get_search_values_by_vehiculo_id()
 {   
     $data['sistema'] = $this->sistema;
     $vehiculo_id= $this->input->post('value');
        $this->load->model('Vehiculo_model');
        $data['all_vehiculo'] = $this->Vehiculo_model->get_all_vehiculo(); 
      $viaje = $this->Viaje_model->get_all_with_asso_viaje();
    if(isset($data['all_vehiculo']) && $data['all_vehiculo']!=null)
                                                  {
                                                  foreach($data['all_vehiculo'] as $v){ 
          echo          "<option value='".$v['vehiculo_id']."'> ".$v['vehiculo_modelo']."</option>"; 
     } 
    }
    else{
              echo '<tr>No data found</tr>';
    }
 } 
  /*
  * get get_search_values_byclms by id
 */
 public function get_search_values_by_ruta_id()
 {   
     $ruta_id= $this->input->post('value');
        $this->load->model('Ruta_model');
        $data['all_ruta'] = $this->Ruta_model->get_all_ruta(); 
      $viaje = $this->Viaje_model->get_all_with_asso_viaje();
    if(isset($data['all_ruta']) && $data['all_ruta']!=null)
                                                  {
                                                  foreach($data['all_ruta'] as $v){ 
          echo          "<option value='".$v['ruta_id']."'> ".$v['ruta_nombre']."</option>"; 
     } 
                                                  }
    else{
              echo '<tr>No data found</tr>';
    }
 } 
  /*
  * get get_search_values_byclms by id
 */
 public function get_search_values_by_usuario_id()
 {   
     $usuario_id= $this->input->post('value');
        $this->load->model('Usuario_model');
        $data['all_usuario'] = $this->Usuario_model->get_all_usuario(); 
      $viaje = $this->Viaje_model->get_all_with_asso_viaje();
if(isset($data['all_usuario']) && $data['all_usuario']!=null)
                                              {
                                              foreach($data['all_usuario'] as $v){ 
      echo          "<option value='".$v['usuario_id']."'> ".$v['usuario_nombre']."</option>"; 
 } 
                                              }
                                              else{
                                                        echo '<tr>No data found</tr>';
                                              }
 } 
  /*
  * get get_search_values_byclms by id
 */
 public function get_search_values_by_conductor_id()
 {   
     $conductor_id= $this->input->post('value');
        $this->load->model('Conductor_model');
        $data['all_conductor'] = $this->Conductor_model->get_all_conductor(); 
        $viaje = $this->Viaje_model->get_all_with_asso_viaje();
        
        if(isset($data['all_conductor']) && $data['all_conductor']!=null){
            
            foreach($data['all_conductor'] as $v){ 
                echo          "<option value='".$v['conductor_id']."'> ".$v['conductor_nombres']."</option>"; 
            }
            
        }else{
                  echo '<tr>No data found</tr>';
        }
 } 
    /*
   * get search values by column- viaje
    */
   public function get_search_values_by_clm()
   {
       $clm_name= $this->input->post('clm_name');
       $value= $this->input->post('value');
       $id= $this->input->post('id');
           $params = array(
           $clm_name=>$value,
           );
              $this->Viaje_model->update_viaje($id,$params);
      $data['noof_page'] = 0;
     $data['viaje'] = $this->Viaje_model->get_all_with_asso_viaje();
     $this->load->view('viaje/index',$data);
   }
   
    /*
    * Listing of viaje
     */
    public function nomina_pasajeros($viaje_id)
    {
        
      try{
            $data['sistema'] = $this->sistema;
            $data['page_title'] = "Nomina Pasajeros";
            $data['parametro'] = $this->Parametro_model->get_parametros();
            $data['empresa'] = $this->Empresa_model->get_empresa(1);
            $data['lamoneda'] = $this->Moneda_model->getalls_monedasact_asc();

            $data['noof_page'] = 0;
            $data['datos_viaje'] = $this->Viaje_model->get_datos_viaje($viaje_id);
            $data['lista_pasajeros'] = $this->Viaje_model->get_lista_pasajeros($viaje_id);
            $data['_view'] = 'viaje/nomina_pasajeros';
            $this->load->view('layouts/main',$data);

        } catch (Exception $ex) {
          throw new Exception('Viaje Controller : Error in index function - ' . $ex);
      }  
    }
   
    /*
    * Listing of viaje
     */
    public function control_abordaje($viaje_id)
    {
        
      try{
            $data['sistema'] = $this->sistema;
            $data['page_title'] = "Control de Abordaje";
            $data['parametro'] = $this->Parametro_model->get_parametros();
            $data['empresa'] = $this->Empresa_model->get_empresa(1);
            $data['lamoneda'] = $this->Moneda_model->getalls_monedasact_asc();

            $data['noof_page'] = 0;
            $data['datos_viaje'] = $this->Viaje_model->get_datos_viaje($viaje_id);
            $data['lista_pasajeros'] = $this->Viaje_model->get_lista_pasajeros($viaje_id);
            $data['_view'] = 'viaje/control_abordaje';
            $this->load->view('layouts/main',$data);

        } catch (Exception $ex) {
          throw new Exception('Viaje Controller : Error in index function - ' . $ex);
      }  
    }
    
    /*
    * Listing of viaje
     */
    public function nomina_equipaje($viaje_id)
    {
        
      try{
            $data['sistema'] = $this->sistema;
            $data['page_title'] = "Nomina Pasajeros";
            $data['parametro'] = $this->Parametro_model->get_parametros();
            $data['empresa'] = $this->Empresa_model->get_empresa(1);
            $data['lamoneda'] = $this->Moneda_model->getalls_monedasact_asc();

            $data['noof_page'] = 0;
            $data['datos_viaje'] = $this->Viaje_model->get_datos_viaje($viaje_id);
            $data['lista_pasajeros'] = $this->Viaje_model->get_lista_equipaje($viaje_id);
            $data['_view'] = 'viaje/nomina_equipaje';
            $this->load->view('layouts/main',$data);

        } catch (Exception $ex) {
          throw new Exception('Viaje Controller : Error in index function - ' . $ex);
      }  
    }

    /*
    * Listing of viaje
     */
    public function nomina_pasajeros_viaje()
    {
        
      try{
            $viaje_id = $this->input->post("viaje_id");
            /*$data['sistema'] = $this->sistema;
            $data['page_title'] = "Nomina Pasajeros";
            $data['parametro'] = $this->Parametro_model->get_parametros();
            $data['empresa'] = $this->Empresa_model->get_empresa(1);
            $data['lamoneda'] = $this->Moneda_model->getalls_monedasact_asc();

            $data['noof_page'] = 0;
            $data['datos_viaje'] = $this->Viaje_model->get_datos_viaje($viaje_id);
            $data['lista_pasajeros'] = $this->Viaje_model->get_lista_pasajeros($viaje_id);
            $data['_view'] = 'viaje/nomina_pasajeros';
            $this->load->view('layouts/main',$data);*/
            
            redirect("viaje/nomina_pasajeros/".$viaje_id);

        } catch (Exception $ex) {
          throw new Exception('Viaje Controller : Error in index function - ' . $ex);
      }  
    }
    /*
   * get search values by column- viaje
    */
   public function imprimir_pasaje($venta_id)
   {
            $data['sistema'] = $this->sistema;
            $data['page_title'] = "Nomina Pasajeros";
            $data['parametro'] = $this->Parametro_model->get_parametros();
            $data['empresa'] = $this->Empresa_model->get_empresa(1);
            $data['lamoneda'] = $this->Moneda_model->getalls_monedasact_asc();      
       
            $data['pasaje'] = $this->Viaje_model->get_pasaje($venta_id);
            $data['detalle_pasaje'] = $this->Viaje_model->get_detalle_pasaje($venta_id);
            $data['title'] = "PASAJE";
            $data['_view'] = 'viaje/pasaje_boucher';
            $this->load->view('layouts/main',$data);
   }
    /*
   * get search values by column- viaje
    */
   public function imprimir_pasajes($venta_id)
   {
            $data['sistema'] = $this->sistema;
            $data['page_title'] = "Nomina Pasajeros";
            $data['parametro'] = $this->Parametro_model->get_parametros();
            $data['empresa'] = $this->Empresa_model->get_empresa(1);
            $data['lamoneda'] = $this->Moneda_model->getalls_monedasact_asc();      
       
            $data['pasaje'] = $this->Viaje_model->get_pasaje($venta_id);
            $data['detalle_pasaje'] = $this->Viaje_model->get_detalle_pasaje($venta_id);
            $data['title'] = "PASAJE";
            $data['_view'] = 'viaje/pasajes_boucher';
            $this->load->view('layouts/main',$data);
   }
   
    public function reporte_ventas() {
        
        $data['sistema'] = $this->sistema;
        $data['page_title'] = "Reporte de Ventas";
        $data['parametro'] = $this->Parametro_model->get_parametros();
        $data['empresa'] = $this->Empresa_model->get_empresa(1);
        $data['lamoneda'] = $this->Moneda_model->getalls_monedasact_asc();
        $data['ventas'] = $this->Viaje_model->obtener_ventas();
        $data['title'] = "REPORTE VENTAS";
        $data['_view'] = 'viaje/reporte_ventas';
        $this->load->view('layouts/main',$data);
        
    }
   
    public function buscar_asientolibre() {
        
        
        $pasaje_id = $this->input->post("pasaje_id");
        
        
        
        $sql = "select p.*, a.* from pasaje p, asientos a
                where 
                p.asiento_id = a.asiento_id and
                p.estado_id = 50 and  p.viaje_id in (
                select viaje_id from pasaje
                where pasaje_id = {$pasaje_id})";
        $pasajes_libres = $this->Venta_model->Consultar($sql);
        
        $sql = "select p.*, a.* from pasaje p, asientos a
                where 
                p.asiento_id = a.asiento_id and p.pasaje_id = {$pasaje_id}";
        $pasaje_actual = $this->Venta_model->Consultar($sql);

        $response = ['pasajes_libres' => $pasajes_libres,'pasaje_actual' => $pasaje_actual];
        echo json_encode($response);
        
    }
   
    public function cambiar_asiento() {
        
        
        $pasaje_origen = $this->input->post("pasaje_origen");
        $pasaje_destino = $this->input->post("pasaje_destino");
        
        //1.- obtener datos del origen
        $sql = "select * from pasaje where pasaje_id = {$pasaje_origen}";
        $pasaje = $this->db->query($sql)->row_array();
        
        //2. Actualizamos el origen
        $sql = "update pasaje set
                factura_id = 0,
                cliente_id = 0,
                pasaje_nombre = '',
                pasaje_telefono = '',
                pasaje_documento = '',
                estado_id = 50,
                usuario_id = 0,
                venta_id = 0,
                cdi_codigoclasificador = 0
                where pasaje_id = {$pasaje_origen}";
        $this->Venta_model->Ejecutar($sql);
        
        //3. Actualizamos el origen
        $sql = "update pasaje set
                factura_id = {$pasaje["factura_id"]},
                cliente_id = {$pasaje["cliente_id"]},
                pasaje_nombre = '{$pasaje["pasaje_nombre"]}',
                pasaje_telefono = '{$pasaje["pasaje_telefono"]}',
                pasaje_documento = '{$pasaje["pasaje_documento"]}',
                estado_id = 54,
                usuario_id = {$pasaje["usuario_id"]},
                venta_id = {$pasaje["venta_id"]},
                cdi_codigoclasificador = {$pasaje["cdi_codigoclasificador"]}
                where pasaje_id = {$pasaje_destino}";
        $this->Venta_model->Ejecutar($sql);
        
        echo json_encode(true);
        
        
        /*
        //1. salvamos destino
        $sql = "update pasaje set pasaje_id = 0 where pasaje_id = {$pasaje_destino}";
        $this->Venta_model->Ejecutar($sql);
        
        //2. Colocamos el origen en vez del destino
        $sql = "update pasaje set pasaje_id = {$pasaje_destino} where pasaje_id = {$pasaje_origen}";
        $this->Venta_model->Ejecutar($sql);
        
        //2. Colocamos destino en lugar del origen
        $sql = "update pasaje set pasaje_id = {$pasaje_origen} where pasaje_id = 0";
        $this->Venta_model->Ejecutar($sql);*/
        
            
        
        
        
    }
   
    public function buscar_viajes() {
        
        
            $fecha_viaje = $this->input->post("fecha_viaje");

            $sql = "select v.*, r.*,h.* from viaje v
                    left join ruta r on r.ruta_id = v.ruta_id
                    left join vehiculo h on h.vehiculo_id = v.vehiculo_id
                    where 
                    v.viaje_fechasalida = '{$fecha_viaje}'";
            $resultado = $this->Venta_model->Consultar($sql);

            echo json_encode($resultado);
        
    }
   
    public function registrar_equipaje_adjunto() {
        
            $now = "'".date("Y-m-d H:i:s")."'"; //{$now}
            $pasaje_id = $this->input->post("pasaje_id");
            $equipaje = $this->input->post("equipaje");

            $sql = "update pasaje set 
                    pasaje_tieneequipaje = 1,
                    pasaje_detalleequipaje = '{$equipaje}',
                    pasaje_fechahoraequipaje = {$now}
                    where pasaje_id = {$pasaje_id}";
            $this->Venta_model->Ejecutar($sql);

            echo json_encode(true);
        
    }

    private function _cargar_datos_formulario(&$data)
    {
        $this->load->model('Ayudante_model');
        $this->load->model('Vehiculo_model');
        $this->load->model('Ruta_model');
        $this->load->model('Usuario_model');
        $this->load->model('Conductor_model');

        $data['all_ayudante'] = $this->Ayudante_model->get_all_ayudante();
        $data['all_vehiculo'] = $this->Vehiculo_model->get_all_vehiculo();
        $data['all_ruta'] = $this->Ruta_model->get_all_ruta();
        $data['all_usuario'] = $this->Usuario_model->get_all_usuario();
        $data['all_conductor'] = $this->Conductor_model->get_all_conductor();
    }

    private function _set_validation_rules()
    {
        $this->form_validation->set_rules('vehiculo_id', 'Vehículo', 'required|integer');
        $this->form_validation->set_rules('ruta_id', 'Ruta', 'required|integer');
        $this->form_validation->set_rules('ayudante_id', 'Ayudante', 'integer');
        $this->form_validation->set_rules('conductor_id', 'Conductor', 'required|integer');
        $this->form_validation->set_rules('conductor_id2', 'Conductor de relevo', 'integer');
        $this->form_validation->set_rules('viaje_fechasalida', 'Fecha salida', 'required');
        $this->form_validation->set_rules('viaje_horasalida', 'Hora salida', 'required');
        $this->form_validation->set_rules('viaje_fechallegada', 'Fecha llegada', 'required');
        $this->form_validation->set_rules('viaje_horallegada', 'Hora llegada', 'required');
        $this->form_validation->set_rules('viaje_preciopasaje', 'Precio base', 'numeric');
        $this->form_validation->set_rules('viaje_precio1', 'Precio 1', 'numeric');
        $this->form_validation->set_rules('viaje_precio2', 'Precio 2', 'numeric');
        $this->form_validation->set_rules('viaje_precio3', 'Precio 3', 'numeric');
    }

    private function _get_post_data()
    {
        return array(
            'ruta_id' => $this->input->post('ruta_id') !== '' ? (int)$this->input->post('ruta_id') : null,
            'ayudante_id' => $this->input->post('ayudante_id') !== '' ? (int)$this->input->post('ayudante_id') : null,
            'vehiculo_id' => $this->input->post('vehiculo_id') !== '' ? (int)$this->input->post('vehiculo_id') : null,
            'usuario_id' => (int)$this->session_data['usuario_id'],
            'conductor_id' => $this->input->post('conductor_id') !== '' ? (int)$this->input->post('conductor_id') : null,
            'conductor_id2' => $this->input->post('conductor_id2') !== '' ? (int)$this->input->post('conductor_id2') : null,
            'viaje_fechasalida' => $this->input->post('viaje_fechasalida') ?: null,
            'viaje_horasalida' => $this->input->post('viaje_horasalida') ?: null,
            'viaje_fechallegada' => $this->input->post('viaje_fechallegada') ?: null,
            'viaje_horallegada' => $this->input->post('viaje_horallegada') ?: null,
            'viaje_preciopasaje' => $this->input->post('viaje_preciopasaje') !== '' ? (float)$this->input->post('viaje_preciopasaje') : 0,
            'viaje_precio1' => $this->input->post('viaje_precio1') !== '' ? (float)$this->input->post('viaje_precio1') : 0,
            'viaje_precio2' => $this->input->post('viaje_precio2') !== '' ? (float)$this->input->post('viaje_precio2') : 0,
            'viaje_precio3' => $this->input->post('viaje_precio3') !== '' ? (float)$this->input->post('viaje_precio3') : 0,
        );
    }

    public function generar_pasajes($viaje_id, $vehiculo_id)
    {
        if (empty($viaje_id) || empty($vehiculo_id)) {
            return array(
                'status'  => false,
                'mensaje' => 'Parámetros inválidos'
            );
        }

        $asientos = $this->db
            ->where('vehiculo_id', $vehiculo_id)
            ->order_by('asiento_orden', 'ASC')
            ->get('asientos')
            ->result();

        if (!$asientos) {
            return array(
                'status'  => false,
                'mensaje' => 'No se encontraron asientos para el vehículo'
            );
        }

        $insertados = 0;
        $existentes = 0;

        $this->db->trans_begin();

        foreach ($asientos as $asiento) {

            $existe = $this->db
                ->where('viaje_id', $viaje_id)
                ->where('asiento_id', $asiento->asiento_id)
                ->get('pasaje')
                ->row();

            if ($existe) {
                $existentes++;
                continue;
            }

            $data = array(
                'asiento_id'      => $asiento->asiento_id,
                'viaje_id'        => $viaje_id,
                'pasaje_numero'   => $asiento->asiento_numero,
                'pasaje_precio'   => ($asiento->asiento_precio !== null) ? (float)$asiento->asiento_precio : 0,
                'estado_id'       => 50,
                'pasaje_fecha'    => date('Y-m-d'),
                'pasaje_hora'     => date('H:i:s'),
                'usuario_id'      => $this->session->userdata('usuario_id') ? $this->session->userdata('usuario_id') : null
            );

            $this->db->insert('pasaje', $data);
            $insertados++;
        }

        if ($this->db->trans_status() === false) {
            $this->db->trans_rollback();
            return array(
                'status'  => false,
                'mensaje' => 'Ocurrió un error al generar los pasajes'
            );
        }

        $this->db->trans_commit();

        return array(
            'status'     => true,
            'mensaje'    => 'Pasajes generados correctamente',
            'insertados' => $insertados,
            'existentes' => $existentes
        );
    }    
    
    public function generar_pasajes_viaje($viaje_id)
    {
        if (empty($viaje_id)) {
            $this->session->set_flashdata(
                'alert_msg',
                '<div class="alert alert-danger text-center">Viaje inválido.</div>'
            );
            redirect('viaje/index');
        }

        $viaje = $this->Viaje_model->get_viaje($viaje_id);

        if (!$viaje) {
            $this->session->set_flashdata(
                'alert_msg',
                '<div class="alert alert-danger text-center">No se encontró el viaje.</div>'
            );
            redirect('viaje/index');
        }

        $vehiculo_id = isset($viaje['vehiculo_id']) ? $viaje['vehiculo_id'] : null;

        if (empty($vehiculo_id)) {
            $this->session->set_flashdata(
                'alert_msg',
                '<div class="alert alert-danger text-center">El viaje no tiene vehículo asignado.</div>'
            );
            redirect('viaje/index');
        }

        $cantidad_pasajes = $this->Viaje_model->contar_pasajes_por_viaje($viaje_id);

        if ($cantidad_pasajes > 0) {
            $this->session->set_flashdata(
                'alert_msg',
                '<div class="alert alert-warning text-center">Este viaje ya tiene asientos generados.</div>'
            );
            redirect('viaje/index');
        }

        $resultado = $this->generar_pasajes($viaje_id, $vehiculo_id);

        if ($resultado) {
            $this->session->set_flashdata(
                'alert_msg',
                '<div class="alert alert-success text-center">Asientos generados correctamente.</div>'
            );
        } else {
            $this->session->set_flashdata(
                'alert_msg',
                '<div class="alert alert-danger text-center">No se pudieron generar los asientos.</div>'
            );
        }

        redirect('viaje/index');
    }
    
    public function registrar_controlabordaje($pasaje_id, $accion, $viaje_id)
    {
        if (!$this->session->userdata('logged_in')) {
            redirect('usuario/login');
        }

        $this->load->model('Pasaje_model');

        $valor = null;

        if ($accion == "ABORDO") {
            $valor = "A BORDO";
        } elseif ($accion == "NOPRESENTE") {
            $valor = "NO PRESENTE";
        }

        if ($valor !== null) {
            $params = array(
                'pasaje_controlabordaje' => $valor
            );

            $this->Pasaje_model->update_pasaje($pasaje_id, $params);
        }

        redirect('viaje/control_abordaje/'.$viaje_id);
    }    
    

}
