<?php $this->load->view('encomienda/comprobantes/_print_header'); ?>
<div class="paper">
<table class="noborder"><tr><td style="width:30%"><?php $this->load->view('encomienda/comprobantes/_company'); ?></td><td class="center"><span class="title">GUÍA DE ENVÍO Y RECEPCIÓN DE ENCOMIENDA</span><br><b>Nº <?= html_escape($encomienda['encomienda_guia']); ?></b></td><td class="center" style="width:18%"><img class="qr" src="<?= $codigoqr; ?>"></td></tr></table>
<table>
<tr><td><b>Fecha:</b> <?= date('d/m/Y',strtotime($encomienda['encomienda_fecha'])); ?> <?= html_escape($encomienda['encomienda_hora']); ?></td><td><b>Estado:</b> <?= html_escape($encomienda['encomiendaestado_nombre']); ?></td></tr>
<tr><td><b>Origen:</b> <?= html_escape($encomienda['origen_nombre']); ?></td><td><b>Destino:</b> <?= html_escape($encomienda['destino_nombre']); ?></td></tr>
<tr><td><b>Remitente:</b> <?= html_escape($encomienda['encomienda_remitentenombre']); ?><br>CI: <?= html_escape($encomienda['encomienda_remitenteci']); ?><br>Teléfono: <?= html_escape($encomienda['encomienda_remitentetelefono']); ?><br>Dirección: <?= html_escape($encomienda['encomienda_remitentedireccion']); ?></td><td><b>Destinatario:</b> <?= html_escape($encomienda['encomienda_destinatarionombre']); ?><br>CI: <?= html_escape($encomienda['encomienda_destinatarioci']); ?><br>Teléfono: <?= html_escape($encomienda['encomienda_destinatariotelefono']); ?><br>Dirección: <?= html_escape($encomienda['encomienda_destinatariodireccion']); ?></td></tr>
<tr><td colspan="2"><b>Contenido:</b> <?= html_escape($encomienda['encomienda_contenido']); ?><br><b>Observación:</b> <?= nl2br(html_escape($encomienda['encomienda_observacion'])); ?></td></tr>
</table>
<table><thead><tr><th>Cantidad</th><th>Peso</th><th>Dimensiones</th><th>Valor declarado</th><th>Subtotal</th><th>Seguro/Recargo</th><th>Total</th></tr></thead><tbody><tr class="center"><td><?= (int)$encomienda['encomienda_cantidad']; ?></td><td><?= number_format($encomienda['encomienda_peso'],2,'.',','); ?> Kg</td><td><?= number_format($encomienda['encomienda_largo'],2); ?> x <?= number_format($encomienda['encomienda_ancho'],2); ?> x <?= number_format($encomienda['encomienda_alto'],2); ?></td><td>Bs <?= number_format($encomienda['encomienda_valordeclarado'],2,'.',','); ?></td><td>Bs <?= number_format($encomienda['encomienda_subtotal'],2,'.',','); ?></td><td>Bs <?= number_format($encomienda['encomienda_seguro']+$encomienda['encomienda_recargo'],2,'.',','); ?></td><td><b>Bs <?= number_format($encomienda['encomienda_total'],2,'.',','); ?></b></td></tr></tbody></table>
<table><tr><td><b>A cuenta:</b> Bs <?= number_format($encomienda['encomienda_acuenta'],2,'.',','); ?></td><td><b>Saldo:</b> Bs <?= number_format($encomienda['encomienda_saldo'],2,'.',','); ?></td><td class="status-paid"><?= ($encomienda['encomienda_pagadoen']==='DESTINO' || (float)$encomienda['encomienda_saldo']>0) ? 'POR PAGAR AL RECOGER' : 'PAGADO EN ORIGEN'; ?></td></tr></table>
<br><table class="noborder"><tr><td class="center"><div class="signature"></div>Firma remitente</td><td class="center"><div class="signature"></div>Responsable recepción</td><td class="center"><div class="signature"></div>Destinatario</td></tr></table>
<p class="muted">Código de seguimiento: <?= html_escape($cadenaqr); ?> | Usuario: <?= html_escape($encomienda['usuario_nombre']); ?></p>
</div><div class="no-print"><button onclick="window.print()">Imprimir</button> <button onclick="window.close()">Cerrar</button></div>
