<div class="box box-primary">
 <div class="box-header with-border"><h3 class="box-title">Guía de Encomienda <?php echo $encomienda['encomienda_guia']; ?></h3><div class="box-tools"><a target="_blank" href="<?php echo site_url('encomienda/imprimir_guia/'.$encomienda['encomienda_id']); ?>" class="btn btn-primary btn-sm"><i class="fa fa-print"></i> Imprimir comprobante</a></div></div>
 <div class="box-body">
  <div class="row"><div class="col-xs-8"><h3><?php echo isset($sistema['sistema_nombre'])?$sistema['sistema_nombre']:'Ximpleman'; ?></h3><b>Origen:</b> <?php echo $encomienda['origen_nombre']; ?> &nbsp; <b>Destino:</b> <?php echo $encomienda['destino_nombre']; ?><br><b>Fecha:</b> <?php echo $encomienda['encomienda_fecha'].' '.$encomienda['encomienda_hora']; ?></div><div class="col-xs-4 text-center"><h2><?php echo $encomienda['encomienda_guia']; ?></h2><div style="border:1px solid #000;padding:15px;font-size:18px;">QR / BARCODE<br><?php echo $encomienda['encomienda_guia']; ?></div></div></div><hr>
  <div class="row"><div class="col-xs-6"><h4>Remitente</h4><?php echo $encomienda['encomienda_remitentenombre']; ?><br>CI/NIT: <?php echo $encomienda['encomienda_remitenteci']; ?><br>Tel: <?php echo $encomienda['encomienda_remitentetelefono']; ?></div><div class="col-xs-6"><h4>Destinatario</h4><?php echo $encomienda['encomienda_destinatarionombre']; ?><br>CI: <?php echo $encomienda['encomienda_destinatarioci']; ?><br>Tel: <?php echo $encomienda['encomienda_destinatariotelefono']; ?><br>Dir: <?php echo $encomienda['encomienda_destinatariodireccion']; ?></div></div><hr>
  <table class="table table-bordered"><thead><tr><th>Cant.</th><th>Contenido</th><th>Peso</th><th>Valor declarado</th><th>Total</th><th>Saldo</th><th>Pago</th></tr></thead><tbody><tr><td><?php echo $encomienda['encomienda_cantidad']; ?></td><td><?php echo $encomienda['encomienda_contenido']; ?></td><td><?php echo $encomienda['encomienda_peso']; ?> Kg</td><td><?php echo number_format($encomienda['encomienda_valordeclarado'],2); ?></td><td><?php echo number_format($encomienda['encomienda_total'],2); ?></td><td><?php echo number_format($encomienda['encomienda_saldo'],2); ?></td><td><?php if(isset($encomienda['encomienda_pagadoen']) && $encomienda['encomienda_pagadoen']=='POR PAGAR AL RECOGER'){ ?><span class="label label-danger">POR PAGAR AL RECOGER</span><?php } else { ?><span class="label label-success">PAGADO</span><?php } ?></td></tr></tbody></table>
  <p><b>Observación:</b> <?php echo $encomienda['encomienda_observacion']; ?></p><br><br>
  <div class="row"><div class="col-xs-6 text-center">_________________________<br>Firma remitente</div><div class="col-xs-6 text-center">_________________________<br>Operador</div></div>
 </div>
</div>
