<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Caja_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get caja by caja_id
     */
    function get_caja($caja_id)
    {
                     
        $caja = $this->db->query("
            SELECT
                *

            FROM
                `caja`

            WHERE
                `caja_id` = ?
        ",array($caja_id))->row_array();

        return $caja;
    }

    /*
     * Get caja by caja_id
     */
    function get_caja_usuario($usuario_id)
    {
        $sql = "select * from caja where usuario_id = ".$usuario_id.
                " and (estado_id = 29  or estado_id = 30)";
                     
        $caja = $this->db->query($sql)->result_array();
        return $caja;
        
    }
    /*
     * Get caja by caja_id
     */
    function caja_pendiente($usuario_id)
    {
        
        $sql = "insert into caja( caja_apertura, caja_fechaapertura, caja_horaapertura, caja_cierre, 
                caja_diferencia, usuario_id, caja_corte1000, caja_corte500, caja_corte200, 
                caja_corte100, caja_corte50, caja_corte20, caja_corte10, caja_corte5, caja_corte2, 
                caja_corte1, caja_corte050 , caja_corte020, caja_corte010, caja_corte005, estado_id, 
                moneda_id, caja_efectivo, caja_credito, caja_transacciones) 
                values (
                0, date(now()), time(now()), 0, 0, ".$usuario_id.", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 29, 1, 0, 0, 0)";

        
        $this->db->query($sql);
        return true;
        
    }
        
    /*
     * Get all caja
     */
    function get_all_caja()
    {
        $caja = $this->db->query("
            SELECT
                c.*, m.moneda_descripcion, e.estado_descripcion, u.usuario_nombre
            FROM
                `caja` c
            LEFT JOIN moneda m on c.moneda_id = m.moneda_id
            LEFT JOIN estado e on c.estado_id = e.estado_id
            LEFT JOIN usuario u on c. usuario_id = u.usuario_id
            WHERE
                1 = 1
            ORDER BY c.`caja_id` DESC
        ")->result_array();

        return $caja;
    }
        
    /*
     * function to add new caja
     */
    function add_caja($params)
    {
        $this->db->insert('caja',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update caja
     */
    function update_caja($caja_id,$params)
    {
        $this->db->where('caja_id',$caja_id);
        return $this->db->update('caja',$params);
    }
    
    /*
     * function to delete caja
     */
    function delete_caja($caja_id)
    {
        return $this->db->delete('caja',array('caja_id'=>$caja_id));
    }
    
    /*
     * function to delete caja
     */
    function ejecutar($sql)
    {
       $this->db->query($sql);
       
        return true;
    }

    function get_caja_id($caja_id)
    {
        $sql = "select * from caja c, bitacora_caja b, usuario u
                where
                c.caja_id = ".$caja_id." and
                c.usuario_id  = u.usuario_id and
                c.caja_id =  b.caja_id 
                order by b.bitacoracaja_id
                ";
       
        return $this->db->query($sql)->result_array();
    }
    /*
     * Get caja by usuario_id
     */
    function get_cajausuario_now($usuario_id)
    {
        $caja = $this->db->query("
            select c.*,u.* from caja c
            left join usuario u on c.usuario_id = u.usuario_id
            where 
            c.usuario_id = ".$usuario_id." and
            c.caja_fechaapertura = date(now())
        ")->row_array();
        return $caja;
    }
    
    
    function get_cajausuario_fecha($usuario_id,$desde,$hasta)
    {
        $caja = $this->db->query("
            select c.*,u.* from caja c
            left join usuario u on c.usuario_id = u.usuario_id
            where 
            c.usuario_id = ".$usuario_id." and
            c.caja_fechaapertura >= {$desde} and
            c.caja_fechaapertura <= {$hasta}
        ")->row_array();
        return $caja;
    }
    /*
     * Get caja by  fecha_desde, fecha_hasta, usuario_id
     */
    function get_cajausuario_admin($fecha_reporte, $usuario_id)
    {
        if($usuario_id > 0){
            $usuario = " c.usuario_id = ".$usuario_id." and ";
        }else{
            $usuario = "";
        }
        $caja = $this->db->query("
            select c.*,u.* from caja c
            left join usuario u on c.usuario_id = u.usuario_id
            where 
            $usuario
            date(c.caja_fechaapertura) = date('$fecha_reporte')
        ")->row_array();
        return $caja;
    }
    /*
     * Get caja by caja_id
     */
    function get_caja_usuarioadmin($caja_id)
    {
        $sql = "select * from caja where caja_id = ".$caja_id.
                " and (estado_id = 29  or estado_id = 30)";
                     
        $caja = $this->db->query($sql)->row_array();
        return $caja;
        
    }
}
