<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cambio_producto_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get cambio_producto by cambio_producto_id
     */
    function get_cambio_producto($cambio_producto_id)
    {
        return $this->db->get_where('cambio_producto',array('cambio_producto_id'=>$cambio_producto_id))->row_array();
    }

   
    
     function get_detalle_compra($cambio_producto_id)
    {
        $sql = "SELECT d.*, p.* from detalle_compra d, producto p
               where d.producto_id=p.producto_id and d.cambio_id = ".$cambio_producto_id;
        $result = $this->db->query($sql)->result_array();
        return $result;        
    } 

    function get_detalle_venta($cambio_producto_id)
    {
        $sql = "SELECT d.*, p.* from detalle_venta d, producto p
               where d.producto_id=p.producto_id and d.cambio_id = ".$cambio_producto_id;
        $result = $this->db->query($sql)->result_array();
        return $result;        
    } 
    /*
     * Get all cambio_producto
     */
    function get_all_cambio_producto()
    
     {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $cambio_producto = $this->db->query("
            SELECT
                *

            FROM
                `cambio_producto`

            WHERE
                1 = 1

            ORDER BY `cambio_producto_id` DESC

            " . $limit_condition . "
        ")->result_array();

        return $cambio_producto;
    }
        
  
   

    function crear_cambio($usuario_id)
    {
        
        $cambio_producto_fecha = "'".date("Y-m-d   H:i:s")."'";
        
        $sql = "insert into cambio_producto(cambio_producto_fecha, usuario_id) ".
                "value(".$cambio_producto_fecha.",".$usuario_id.")";
        $cambio_producto = $this->db->query($sql);
        $cambio_producto_id = $this->db->insert_id();
        return $cambio_producto_id;        
        
    }

        
    /*
     * function to add new cambio_producto
     */
    function add_cambio_producto($params)
    {
        $this->db->insert('cambio_producto',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update cambio_producto
     */
    function update_cambio_producto($cambio_producto_id,$params)
    {
        $this->db->where('cambio_producto_id',$cambio_producto_id);
        return $this->db->update('cambio_producto',$params);
    }
       
    /*
     * function to delete cambio_producto
     */
    function delete_cambio_producto($cambio_producto_id)
    {
        return $this->db->delete('cambio_producto',array('cambio_producto_id'=>$cambio_producto_id));
    }
function ejecutar($sql)
    {
        $cambio_producto = $this->db->query($sql);
        return $cambio_producto;
        
    }

}
