<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class Categoria_vehiculo_model extends CI_Model 
{ 
     function __construct()
      {
          parent::__construct();
      }
      /*
        * Get categoria_vehiculo by categoriavehiculo_id 
      */ 
      function get_categoria_vehiculo($categoriavehiculo_id)
      {
        try{
           return $this->db->get_where('categoria_vehiculo',array('categoriavehiculo_id'=>$categoriavehiculo_id))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Categoria_vehiculo_model Model : Error in get_categoria_vehiculo function - ' . $ex);
           }  
      }
      /*
        * Get categoria_vehiculo by  column name
      */ 
      function get_categoria_vehiculobyclm_name($clm_name,$clm_value)
      {
        try{
           return $this->db->get_where('categoria_vehiculo',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Categoria_vehiculo_model Madel : Error in get_categoria_vehiculobyclm_name function - ' . $ex);
           }  
      }
     /*
        * Get All categoria_vehiculo count 
      */ 
      function get_all_categoria_vehiculo_count()
      {
        try{
           $this->db->from('categoria_vehiculo');
           return $this->db->count_all_results();
           } catch (Exception $ex) {
             throw new Exception('Categoria_vehiculo_model model : Error in get_all_categoria_vehiculo_count function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join categoria_vehiculocount 
      */ 
      function get_all_with_asso_categoria_vehiculo()
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Categoria_vehiculo_model model : Error in get_all_with_asso_categoria_vehiculo function - ' . $ex);
           }  
      }
      /*
          * Get all categoria_vehiculo 
      */ 
      function get_all_categoria_vehiculo($params = array())
      {
        try{
              $this->db->order_by('categoriavehiculo_id', 'desc');
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('categoria_vehiculo')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Categoria_vehiculo_model model : Error in get_all_categoria_vehiculo function - ' . $ex);
           }  
      } 
      /*
         * function to add new categoria_vehiculo 
      */
      function add_categoria_vehiculo($params)
      {
        try{
          $this->db->insert('categoria_vehiculo',$params);
        return $this->db->insert_id();
           } catch (Exception $ex) {
             throw new Exception('Categoria_vehiculo_model model : Error in add_categoria_vehiculo function - ' . $ex);
           }  
      }
      /* 
          * function to update categoria_vehiculo 
      */
      function update_categoria_vehiculo($categoriavehiculo_id,$params)
      {
        try{
            $this->db->where('categoriavehiculo_id',$categoriavehiculo_id);
        return $this->db->update('categoria_vehiculo',$params);
           } catch (Exception $ex) {
             throw new Exception('Categoria_vehiculo_model model : Error in update_categoria_vehiculo function - ' . $ex);
           }  
       }
     /* 
          * function to delete categoria_vehiculo 
      */
       function delete_categoria_vehiculo($categoriavehiculo_id)
       {
        try{
             return $this->db->delete('categoria_vehiculo',array('categoriavehiculo_id'=>$categoriavehiculo_id));
           } catch (Exception $ex) {
             throw new Exception('Categoria_vehiculo_model model : Error in delete_categoria_vehiculo function - ' . $ex);
           }  
       }
      /*
        * Get categoria_vehiculo by  column name where not in particular id
      */ 
      function get_categoria_vehiculobyclm_name_not_id($clm_name,$clm_value,$where_cond)
      {
        try{
            $this->db->where('categoriavehiculo_id!=', $where_cond);
           return $this->db->get_where('categoria_vehiculo',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Categoria_vehiculo_model model : Error in get_categoria_vehiculobyclm_name_not_id function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join categoria_vehiculocount 
      */ 
      function get_all_with_asso_categoria_vehiculo_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Categoria_vehiculo_model model : Error in get_all_with_asso_categoria_vehiculo_by_cat function - ' . $ex);
           }  
      }
      /*
          * Get all categoria_vehiculo_by_cat 
      */ 
      function get_all_categoria_vehiculo_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
              $this->db->order_by('categoriavehiculo_id', 'desc');
              $this->db->where($column_name, $value_id);
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('categoria_vehiculo')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Categoria_vehiculo_model model : Error in get_all_categoria_vehiculo_by_cat function - ' . $ex);
           }  
      } 
 }
