<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Credito_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get credito by credito_id
     */
    function get_credito($credito_id)
    {
        $credito = $this->db->query("
            SELECT
                *

            FROM
                `credito`

            WHERE
                `credito_id` = ?
        ",array($credito_id))->row_array();

        return $credito;
    }
    
    /*
     * Get all credito count
     */
    function get_all_credito_count()
    {
        $credito = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `credito`
        ")->row_array();

        return $credito['count'];
    }

    function get_deudas($filtro)
    {
        $deuda = $this->db->query("
            SELECT
                c.*, p.*, co.*, e.*

            FROM
                credito c, proveedor p, compra co, estado e

            WHERE
                c.compra_id = co.compra_id
                and p.proveedor_id = co.proveedor_id
                and c.estado_id = e.estado_id
                ".$filtro." 

            ORDER BY c.credito_fecha DESC

            
        ")->result_array();

        return $deuda;
    }
        
    function get_cuentas($filtro)
    {
        $deuda = $this->db->query("
            SELECT
                c.*, p.*, co.*, e.*

            FROM
                credito c, cliente p, venta co, estado e

            WHERE
                c.venta_id = co.venta_id
                and p.cliente_id = co.cliente_id
                and c.estado_id = e.estado_id
                ".$filtro." 

            ORDER BY c.credito_fecha DESC

            
        ")->result_array();

        return $deuda;
    }
        
    /*
     * Get all credito
     */
    function get_all_credito($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $credito = $this->db->query("
            SELECT
                *

            FROM
                `credito`

            WHERE
                1 = 1

            ORDER BY `credito_id` DESC

            " . $limit_condition . "
        ")->result_array();

        return $credito;
    }
         function get_all_deuda($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $credito = $this->db->query("
            SELECT
                c.*, p.*, co.*, e.*

            FROM
                credito c, proveedor p, compra co, estado e

            WHERE
                c.compra_id = co.compra_id
                and p.proveedor_id = co.proveedor_id
                and c.estado_id = e.estado_id

            ORDER BY `credito_id` DESC

            " . $limit_condition . "
        ")->result_array();

        return $credito;
    }
    
     function get_all_cuentas($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $credito = $this->db->query("
            SELECT
                c.*, p.*, ve.*, e.*

            FROM
                credito c, cliente p, venta ve, estado e

            WHERE
                c.venta_id = ve.venta_id
                and p.cliente_id = ve.cliente_id
                and c.estado_id = e.estado_id

            ORDER BY `credito_id` DESC

            " . $limit_condition . "
        ")->result_array();

        return $credito;
    }
    /*
     * function to add new credito
     */
    function add_credito($params)
    {
        $this->db->insert('credito',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update credito
     */
    function update_credito($credito_id,$params)
    {
        $this->db->where('credito_id',$credito_id);
        return $this->db->update('credito',$params);
    }
    
    /*
     * function to delete credito
     */
    function delete_credito($credito_id)
    {
        return $this->db->delete('credito',array('credito_id'=>$credito_id));
    }
}
