<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Detalle_venta_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get detalle_venta by detalleven_id
     */
//    function get_detalle_venta($detalleven_id)
//    {
//        $detalle_venta = $this->db->query("
//            SELECT
//                *
//
//            FROM
//                `detalle_venta`
//
//            WHERE
//                `detalleven_id` = ?
//        ",array($detalleven_id))->row_array();
//
//        return $detalle_venta;
//    }

    function get_venta($venta_id)
    {
        $sql = "select *  from venta v, cliente c, usuario u, tipo_transaccion t where v.cliente_id = c.cliente_id and "
                . " v.usuario_id = u.usuario_id and v.tipotrans_id = t.tipotrans_id and v.venta_id = ".$venta_id;
        $venta = $this->db->query($sql)->result_array();        
        return $venta;
    }
    
    function get_detalle_venta($venta_id)
    {
        $sql = "select * from detalle_venta d, producto p where d.producto_id = p.producto_id and venta_id = ".$venta_id;
        $detalle_venta = $this->db->query($sql)->result_array();        
        return $detalle_venta;
    }

    function cargar_detalle_venta($venta_id,$usuario_id)
    {
        $sql = "delete from detalle_venta_aux where usuario_id = ".$usuario_id;
        $this->db->query($sql);
        
        $sql =  "insert into detalle_venta_aux
        (producto_id,
          venta_id,
          moneda_id,
          detalleven_codigo,
          detalleven_cantidad,
          detalleven_unidad,
          detalleven_costo,
          detalleven_precio,
          detalleven_subtotal,
          detalleven_descuento,
          detalleven_total,
          detalleven_caracteristicas,
          detalleven_preferencia,
          detalleven_comision,
          detalleven_tipocambio,
          usuario_id,
          existencia,
          producto_nombre, 
          producto_unidad, 
          producto_marca, 
          categoria_id, 
          producto_codigobarra
        )


        (SELECT 
          d.producto_id,
          ".$venta_id." as venta_id,
          d.moneda_id,
          d.detalleven_codigo,
          d.detalleven_cantidad,
          d.detalleven_unidad,
          d.detalleven_costo,
          d.detalleven_precio,
          d.detalleven_subtotal,
          d.detalleven_descuento,
          d.detalleven_total,
          d.detalleven_caracteristicas,
          d.detalleven_preferencia,
          d.detalleven_comision,
          d.detalleven_tipocambio,
          ".$usuario_id.",
          i.existencia,
          i.producto_nombre, 
          i.producto_unidad, 
          i.producto_marca, 
          i.categoria_id, 
          i.producto_codigobarra              
        FROM
          detalle_venta d, inventario i
        WHERE           
          venta_id=".$venta_id." and d.producto_id = i.producto_id )";
        $this->db->query($sql);
        
        $sql =  "select * from detalle_venta_aux d, producto p where "
               ." d.producto_id = p.producto_id and  d.venta_id=".$venta_id;        
        $detalle_venta = $this->db->query($sql)->result_array();

        
        return $detalle_venta;
    }
    
    /*
     * Get all detalle_venta count
     */
    function get_all_detalle_venta_count()
    {
        $detalle_venta = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `detalle_venta`
        ")->row_array();

        return $detalle_venta['count'];
    }
        
    /*
     * Get all detalle_venta
     */
    function get_all_detalle_venta($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $detalle_venta = $this->db->query("
            SELECT
                *

            FROM
                detalle_venta d, producto p, venta v, moneda m

            WHERE
                d.producto_id = p.producto_id
                and d.venta_id = v.venta_id
                and d.moneda_id = m.moneda_id

            ORDER BY `detalleven_id` DESC

            " . $limit_condition . "
        ")->result_array();

        return $detalle_venta;
    }
        
    /*
     * function to add new detalle_venta
     */
    function add_detalle_venta($params)
    {
        $this->db->insert('detalle_venta',$params);
        return $this->db->insert_id();
    }
    
    function get_all_detalle_ventas($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $detalle_compra = $this->db->query("
           SELECT
                dc.*, p.*

            FROM
                detalle_venta dc, producto p

            WHERE
                dc.producto_id = p.producto_id

            ORDER BY `detalleven_id` DESC limit 30

            " . $limit_condition . "
        ")->result_array();

        return $detalle_compra;
    }
    
    /*
     * function to update detalle_venta
     */
    function update_detalle_venta($detalleven_id,$params)
    {
        $this->db->where('detalleven_id',$detalleven_id);
        return $this->db->update('detalle_venta',$params);
    }
    
    /*
     * function to delete detalle_venta
     */
    function delete_detalle_venta($detalleven_id)
    {
        return $this->db->delete('detalle_venta',array('detalleven_id'=>$detalleven_id));
    }
    
    /* ****Obtiene la cantidad de detalle venta (para insumos de servicio)****** */
    function get_cantidad_detalle_venta($detalleven_id)
    {
        $sql = "select detalleven_cantidad, producto_id from detalle_venta where detalleven_id = ".$detalleven_id;
        $res = $this->db->query($sql)->row_array();        
        return $res;
    }
    /* ********Nos da el resultado si esta asignado un insumo ******** */
    function existe_insumo_asignado($producto_id,$detalleserv_id)
    {
        $sql = "select
                        * 
                  from
                        detalle_venta
                 where
                        producto_id = '$producto_id'
                        and detalleserv_id = '$detalleserv_id'";
        $detalle_ven = $this->db->query($sql)->row_array();
        return $detalle_ven;
    }
    /* ****Obtiene todos los insumos de un detalle de servicio****** */
    function get_all_insumo_usado($detalleserv_id)
    {
        $sql = "select
                       dv.detalleven_cantidad, dv.detalleven_total, p.producto_nombre, p.producto_codigo, 
                       p.producto_codigobarra
                  from
                       detalle_venta dv, producto p
                 where
                       dv.producto_id = p.producto_id
                       and dv.detalleserv_id = ".$detalleserv_id;
        $res = $this->db->query($sql)->result_array();
        return $res;
    }
    /* ****Obtiene el total del precio del insumo usado****** */
    function get_costototal_insumos_usados($detalleserv_id)
    {
        $sql = "SELECT
                SUM(dv.detalleven_total) as total
            FROM
                detalle_venta dv
           WHERE
                
                 dv.detalleserv_id = ".$detalleserv_id;
        $res = $this->db->query($sql)->row_array();
        return $res['total'];
    }
    
}
