<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Menu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get menu by menu_id
     */
    function get_menu($menu_id)
    {
        $menu = $this->db->query("
            SELECT
                *

            FROM
                `menu`

            WHERE
                `menu_id` = ?
        ",array($menu_id))->row_array();

        return $menu;
    }
    
    /*
     * Get all menu count
     */
    function get_all_menu_count()
    {
        $menu = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `menu`
        ")->row_array();

        return $menu['count'];
    }
        
    /*
     * Get all menu
     */
    function get_all_menu($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $menu = $this->db->query("
            SELECT
                *

            FROM
                menu m, estado_pagina e, menu_principal mp

            WHERE
                m.estadopag_id = e.estadopag_id
                and m.menup_id = mp.menup_id

            ORDER BY `menu_id` DESC

            " . $limit_condition . "
        ")->result_array();

        return $menu;
    }
        
    /*
     * function to add new menu
     */
    function add_menu($params)
    {
        $this->db->insert('menu',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update menu
     */
    function update_menu($menu_id,$params)
    {
        $this->db->where('menu_id',$menu_id);
        return $this->db->update('menu',$params);
    }
    
    /*
     * function to delete menu
     */
    function delete_menu($menu_id)
    {
        return $this->db->delete('menu',array('menu_id'=>$menu_id));
    }
}
