<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Mesa_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get mesa by mesa_id
     */
    function get_mesa($mesa_id)
    {
        $mesa = $this->db->query("
            SELECT
                *

            FROM
                `mesa`

            WHERE
                `mesa_id` = ?
        ",array($mesa_id))->row_array();

        return $mesa;
    }
        
    /*
     * Get all mesa
     */
    function get_all_mesa()
    {
        $mesa = $this->db->query("
            SELECT
                *

            FROM
                `mesa`

            WHERE
                1 = 1

            ORDER BY `mesa_id` DESC
        ")->result_array();

        return $mesa;
    }
        
    /*
     * function to add new mesa
     */
    function add_mesa($params)
    {
        $this->db->insert('mesa',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update mesa
     */
    function update_mesa($mesa_id,$params)
    {
        $this->db->where('mesa_id',$mesa_id);
        return $this->db->update('mesa',$params);
    }
    
    /*
     * function to delete mesa
     */
    function delete_mesa($mesa_id)
    {
        return $this->db->delete('mesa',array('mesa_id'=>$mesa_id));
    }
}
