<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Moneda_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get moneda by moneda_id
     */
    function get_moneda($moneda_id)
    {
        $sql = "select * from moneda where moneda_id = ".$moneda_id;
        
        $moneda = $this->db->query($sql)->row_array();

        return $moneda;
    }
    
    /*
     * Get all moneda count
     */
    function get_all_moneda_count()
    {
        $moneda = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `moneda`
        ")->row_array();

        return $moneda['count'];
    }
        
    /*
     * Get all moneda
     */
    function get_all_moneda($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $sql = "SELECT * FROM moneda m, estado e
                WHERE m.estado_id = e.estado_id
                ORDER BY moneda_id ".$limit_condition;
        
        $moneda = $this->db->query($sql)->result_array();
        return $moneda;
    }
        
    /*
     * function to add new moneda
     */
    function add_moneda($params)
    {
        $this->db->insert('moneda',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update moneda
     */
    function update_moneda($moneda_id,$params)
    {
        $this->db->where('moneda_id',$moneda_id);
        return $this->db->update('moneda',$params);
    }
    
    /*
     * function to delete moneda
     */
    function delete_moneda($moneda_id)
    {
        return $this->db->delete('moneda',array('moneda_id'=>$moneda_id));
    }
    
    /*
     * Get alls moneda
     */
    function get_alls_moneda()
    {
        $moneda = $this->db->query("
            SELECT
                moneda_id, moneda_descripcion
            FROM
                moneda m, estado e

            WHERE
                m.estado_id = e.estado_id

            ORDER BY `moneda_id` DESC

        ")->result_array();

        return $moneda;
    }
    /*
     * Get alls moneda orden ASC
     */
    function get_alls_moneda_asc()
    {
        $moneda = $this->db->query("
            SELECT
                m.*
            FROM
                moneda m, estado e

            WHERE
                m.estado_id = e.estado_id

            ORDER BY `moneda_id` ASC

        ")->result_array();

        return $moneda;
    }
    /*
     * Get alls monedas activas orden ASC
     */
    function getalls_monedasact_asc()
    {
        $sql = "SELECT vs.producto_id, vs.`producto_codigo`, vs.`producto_nombre`, tt.tipotrans_nombre, 
                vs.producto_unidad, sum(vs.detalleven_cantidad) as total_cantidad, 
                (sum(`vs`.`detalleven_total`) / sum(vs.detalleven_cantidad)) as total_punitario, 
                sum(`vs`.`detalleven_descuento`*`vs`.`detalleven_cantidad`) as total_descuento, 
                sum(`vs`.`detalleven_total`) as total_venta, (sum(`vs`.`detalleven_costo`*`vs`.`detalleven_cantidad`)) as total_costo, 
                (sum(`vs`.`detalleven_total`)-SUM(vs.`detalleven_costo`*`vs`.`detalleven_cantidad`)) as total_utilidad, 
                avg(vs.detalleven_tc) as tipo_cambio 
                FROM ventas vs 
                LEFT JOIN tipo_transaccion tt on vs.tipotrans_id = tt.tipotrans_id 
                WHERE 
                date(venta_fecha) >= '2022-10-20' and 
                date(venta_fecha) <='2022-10-20' and 
                vs.usuario_id = 1 
                group by `vs`.producto_id 
                order by total_venta";
        
        $moneda = $this->db->query($sql)->result_array();
        return $moneda;
    }
    /**
     * Busca el buscar_codigo_clasificador, si encuentra regresa la moneda_id, sino regresa 0
     */
    function buscar_codigo_clasificador($moneda_codigoclasificador){
        return $this->db->query(
            "SELECT if(count(m.moneda_id) > 0,m.moneda_id,0) as moneda_id
            from moneda m
            where m.moneda_codigoclasificador = $moneda_codigoclasificador"
            )->row_array();
    }
    
    function truncate_table(){
        $sql = "truncate moneda";
        $this->db->query($sql);
        return true;
    }
    
}
