<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Orden_pago_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get orden_pago by orden_id
     */
    function get_orden_pago($orden_id)
    {
        return $this->db->get_where('orden_pago',array('orden_id'=>$orden_id))->row_array();
    }
        
    /*
     * Get all orden_pago
     */
    function get_pago_pendiente()
    {
        $sql = "select o.*,e.*
                from orden_pago o, estado e
                where e.estado_id = 8 and o.estado_id = e.estado_id";
        $resultado = $this->db->query($sql)->result_array();
        return $resultado;
    }
        
    /*
     * Get all usuario
     */
    function get_usuarios()
    {
        $sql = "select * from usuario order by  usuario_id";
        $resultado = $this->db->query($sql)->result_array();
        return $resultado;
    }
        
        
    /*
     * Get all orden_pago
     */
    function get_pagadas_hoy()
    {
        $sql = "select o.*,e.*
                from orden_pago o, estado e
                where e.estado_id = 9 and o.estado_id = e.estado_id 
                and o.orden_fechapago = date(now())";
        $resultado = $this->db->query($sql)->result_array();
        return $resultado;
    }
        
    /*
     * Pagados antes
     */
    function get_pagadas_antes()
    {
        $sql = "select o.*,e.*
                from orden_pago o, estado e
                where e.estado_id = 9 and o.estado_id = e.estado_id 
                and o.orden_fechapago <= date(now())";
        $resultado = $this->db->query($sql)->result_array();
        return $resultado;
    }
    /*
     * Pagados antes
     */
    function get_todos()
    {
        $sql = "select o.*,e.*
                from orden_pago o, estado e
                where e.estado_id = 8 and o.estado_id = e.estado_id 
                and o.orden_fechapago <= date(now())";
        $resultado = $this->db->query($sql)->result_array();
        return $resultado;
    }
        
    /*
     * function to add new orden_pago
     */
    function add_orden_pago($params)
    {
        $this->db->insert('orden_pago',$params);
        return $this->db->insert_id();
    }
    
        
    /*
     * function to add new orden_pago
     */
    function registrar_orden($sql)
    {
        $this->db->query($sql);
        return true;
    }
    
    /*
     * function to update orden_pago
     */
    function update_orden_pago($orden_id,$params)
    {
        $this->db->where('orden_id',$orden_id);
        return $this->db->update('orden_pago',$params);
    }
    
    /*
     * function to delete orden_pago
     */
    function delete_orden_pago($orden_id)
    {
        return $this->db->delete('orden_pago',array('orden_id'=>$orden_id));
    }
}
