<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class Pasaje_model extends CI_Model 
{ 
     function __construct()
      {
          parent::__construct();
      }
      /*
        * Get pasaje by pasaje_id 
      */ 
      function get_pasaje($pasaje_id)
      {
        try{
           return $this->db->get_where('pasaje',array('pasaje_id'=>$pasaje_id))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Pasaje_model Model : Error in get_pasaje function - ' . $ex);
           }  
      }
      /*
        * Get pasaje by  column name
      */ 
      function get_pasajebyclm_name($clm_name,$clm_value)
      {
        try{
           return $this->db->get_where('pasaje',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Pasaje_model Madel : Error in get_pasajebyclm_name function - ' . $ex);
           }  
      }
     /*
        * Get All pasaje count 
      */ 
      function get_all_pasaje_count()
      {
        try{
           $this->db->from('pasaje');
           return $this->db->count_all_results();
           } catch (Exception $ex) {
             throw new Exception('Pasaje_model model : Error in get_all_pasaje_count function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join pasajecount 
      */ 
      function get_all_with_asso_pasaje()
      {
        try{
           $this->db->select('*');
           $this->db->from('pasaje a  ' );
            $this->db->join('factura b', 'b.factura_id=a. factura_id','left');
            $this->db->join('asientos c', 'c.asiento_id=a. asiento_id','left');
            $this->db->join('tipo_vehiculo d', 'd.tipomovilidad_id=a. viaje_id','left');
            $this->db->join('cliente e', 'e.cliente_id=a. cliente_id','left');
            $this->db->join('estado f', 'f.estado_id=a. estado_id','left');
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Pasaje_model model : Error in get_all_with_asso_pasaje function - ' . $ex);
           }  
      }
      /*
          * Get all pasaje 
      */ 
      function get_all_pasaje($params = array())
      {
        try{
              $this->db->order_by('pasaje_id', 'desc');
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('pasaje')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Pasaje_model model : Error in get_all_pasaje function - ' . $ex);
           }  
      } 
      /*
         * function to add new pasaje 
      */
      function add_pasaje($params)
      {
        try{
          $this->db->insert('pasaje',$params);
        return $this->db->insert_id();
           } catch (Exception $ex) {
             throw new Exception('Pasaje_model model : Error in add_pasaje function - ' . $ex);
           }  
      }
      /* 
          * function to update pasaje 
      */
      function update_pasaje($pasaje_id,$params)
      {
        try{
            $this->db->where('pasaje_id',$pasaje_id);
        return $this->db->update('pasaje',$params);
           } catch (Exception $ex) {
             throw new Exception('Pasaje_model model : Error in update_pasaje function - ' . $ex);
           }  
       }
     /* 
          * function to delete pasaje 
      */
       function delete_pasaje($pasaje_id)
       {
        try{
             return $this->db->delete('pasaje',array('pasaje_id'=>$pasaje_id));
           } catch (Exception $ex) {
             throw new Exception('Pasaje_model model : Error in delete_pasaje function - ' . $ex);
           }  
       }
      /*
        * Get pasaje by  column name where not in particular id
      */ 
      function get_pasajebyclm_name_not_id($clm_name,$clm_value,$where_cond)
      {
        try{
            $this->db->where('pasaje_id!=', $where_cond);
           return $this->db->get_where('pasaje',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Pasaje_model model : Error in get_pasajebyclm_name_not_id function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join pasajecount 
      */ 
      function get_all_with_asso_pasaje_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
           $this->db->select('*');
           $this->db->from('pasaje a  ' );
              //$this->db->where($column_name, $value_id);
            $this->db->join('factura b', 'b.factura_id=a. factura_id','left');
              $this->db->where('a.'.$column_name, $value_id);
            $this->db->join('asientos c', 'c.asiento_id=a. asiento_id','left');
              $this->db->where('a.'.$column_name, $value_id);
            $this->db->join('tipo_vehiculo d', 'd.tipomovilidad_id=a. viaje_id','left');
              $this->db->where('a.'.$column_name, $value_id);
            $this->db->join('cliente e', 'e.cliente_id=a. cliente_id','left');
              $this->db->where('a.'.$column_name, $value_id);
            $this->db->join('estado f', 'f.estado_id=a. estado_id','left');
              $this->db->where('a.'.$column_name, $value_id);
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Pasaje_model model : Error in get_all_with_asso_pasaje_by_cat function - ' . $ex);
           }  
      }
      /*
          * Get all pasaje_by_cat 
      */ 
      function get_all_pasaje_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
              $this->db->order_by('pasaje_id', 'desc');
              $this->db->where($column_name, $value_id);
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('pasaje')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Pasaje_model model : Error in get_all_pasaje_by_cat function - ' . $ex);
           }  
      } 
 }
