<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Promocion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get promocion by promocion_id
     */
    function get_promocion($promocion_id)
    {
        $promocion = $this->db->query("
                SELECT 
                  p.*, t.producto_nombre
                FROM
                  promocion p

                LEFT JOIN 
                producto t on t.producto_id = p.producto_id

                WHERE
                promocion_id = ".$promocion_id."
        ",array($promocion_id))->row_array();

        return $promocion;
    }
    
    /*
     * Get all promocion count
     */
    function get_all_promocion_count()
    {
        $promocion = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `promocion`
        ")->row_array();

        return $promocion['count'];
    }
        
    /*
     * Get all promocion
     */
    function get_all_promocion($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $promocion = $this->db->query("
                SELECT p.*, e.`estado_tipo`,e.`estado_descripcion`,e.`estado_color`,
                pr.*

                FROM promocion p
                LEFT JOIN producto pr on pr.producto_id = p.producto_id
                LEFT JOIN estado e on e.estado_id = p.estado_id

                /*WHERE p.estado_id = 1       */
                ORDER BY
                  p.promocion_id DESC
        ")->result_array();

        return $promocion;
    }
        
    /*
     * function to add new promocion
     */
    function add_promocion($params)
    {
        $this->db->insert('promocion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update promocion
     */
    function update_promocion($promocion_id,$params)
    {
        $this->db->where('promocion_id',$promocion_id);
        return $this->db->update('promocion',$params);
    }
    
    /*
     * function to delete promocion
     */
    function delete_promocion($promocion_id)
    {
        return $this->db->delete('promocion',array('promocion_id'=>$promocion_id));
    }
    
    /*
     * function to delete promocion
     */
    function get_detalle_promocion($promocion_id)
    {
        $sql =  "select * from conspromocion where 
                 promocion_id = ".$promocion_id;
        return $this->db->query($sql)->result_array(); 
    }

    /*
     * ejecutar consulta
     */
    function ejecutar($sql)
    {
        $this->db->query($sql);
        return true;
    }
    
    /*
     * promociones
     */
    function get_promociones()
    {
        $sql =  "select p.*
                from promocion p 
                where 
                p.estado_id = 1 and 
                p.promocion_id in 
                ( select  distinct(promocion_id) from detalle_promocion)";
        return $this->db->query($sql)->result_array(); 
    }
    
}
