  <?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Venta_online_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get detalle_venta by detalleven_id
     */


  function ventas($filtro)
  {
        $detalle_venta = $this->db->query("
            SELECT
                v.*, e.entrega_nombre, c.cliente_nombre, c.cliente_razon, c.cliente_nit, c.cliente_telefono, c.cliente_direccion, ts.tiposerv_descripcion, f.forma_nombre
            FROM
                venta_online v 
            
            LEFT JOIN entrega e on v.entrega_id=e.entrega_id
            LEFT JOIN cliente c on v.cliente_id=c.cliente_id
            LEFT JOIN tipo_servicio ts on v.tiposerv_id=ts.tiposerv_id
            LEFT JOIN forma_pago f on v.forma_id=f.forma_id
            WHERE
            1=1
            ".$filtro."
            ORDER BY v.venta_id  
            
        ")->result_array();

        return $detalle_venta;
  }
  /* obtiene detalle venta online y existencia para comparar existencia.... en modal */
  function get_detalle($venta)
    {
        $sql = "SELECT
                        c.*, p.producto_nombre, p.producto_unidad, p.producto_marca, p.categoria_id,
                        p.producto_codigobarra, p.existencia
                FROM
                        detalle_ventaonline c
                LEFT JOIN inventario p on c.producto_id=p.producto_id
                WHERE
                        c.venta_id=".$venta." ORDER BY c.detalleven_id desc ";
        $result = $this->db->query($sql)->result_array();
        return $result;        
    }
    
    
    /*
     * function to eliminar 
     */
    function eliminar_detalleventaux($usuario_id)
    {
        return $this->db->delete('detalle_venta_aux',array('usuario_id'=>$usuario_id));
    }
    function ejecutar($sql)
    {
        $vonline = $this->db->query($sql);        
        $insert_id = $this->db->insert_id();   
        
        return $insert_id;
    }
    /* para obtener cliente_id */
    function get_thiscliente($venta_id)
    {
        $sql = "SELECT
                        v.cliente_id
                FROM
                        venta_online v
                WHERE
                        v.venta_id= $venta_id";
        $result = $this->db->query($sql)->row_array();
        return $result;        
    }
    /*
     * function to add venta online en modulo de ventas
     */
    function add_detalleventa_aux($params)
    {
        $this->db->insert('detalle_venta_aux',$params);
        return $this->db->insert_id();
    }
    
}