<?php 
/*
    Generated by Manuigniter v2.0 
    www.manuigniter.com
*/
use Restserver\Libraries\REST_Controller;
defined('BASEPATH') OR exit('No direct script access allowed');
require APPPATH . '/libraries/REST_Controller.php';
require APPPATH . 'libraries/Format.php';
class Parada extends REST_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('Parada_model');
 } 
 /*
* Listing of parada
 */
public function get_all_post()
{
  try{
  $data['parada'] = $this->Parada_model->get_all_parada();
     if($data['parada'] && $data['parada']!=null){
       $parada_ar = array();
       foreach($data['parada'] as $p)
       {
       $p_ar = array();
       $p_ar['parada_id'] = $p['parada_id'];
       $p_ar['estado_id'] = $p['estado_id'];
       $p_ar['parada_nombre'] = $p['parada_nombre'];
       $p_ar['parada_ubicacion'] = $p['parada_ubicacion'];
       $p_ar['parada_latitud'] = $p['parada_latitud'];
       $p_ar['parada_longitud'] = $p['parada_longitud'];
       $parada_ar[] = $p_ar;
       }
       $response = array(
       'status' => 200,
       'message' => 'get all data Succesfully',
       'data' => $parada_ar,
       );
       $this->response($response, REST_Controller::HTTP_OK);
     }
     else{
       $response = array(
      'status' => 400,
      'message' => 'Detail is not found'
        );
       $this->response($response, REST_Controller::HTTP_OK); 
        }
       } catch (Exception $ex) {
             throw new Exception('Parada controller_name : Error in get_all_post function - ' . $ex);
        }  
}
 /*
  * Adding a new parada
  */
 function addnew_post()
 {  
  try{
      $params = array(
       'estado_id'=> $this->input->post('estado_id'),
       'parada_nombre'=> $this->input->post('parada_nombre'),
       'parada_ubicacion'=> $this->input->post('parada_ubicacion'),
       'parada_latitud'=> $this->input->post('parada_latitud'),
       'parada_longitud'=> $this->input->post('parada_longitud'),
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
       if(isset($_POST) && count($_POST) > 0)     
        {  
            $parada_id= $this->Parada_model->add_parada($params);
   $data['parada'] = $this->Parada_model->get_parada($parada_id);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Added',
            'data' => $data
             );
           $this->response($response, REST_Controller::HTTP_OK);
        }
        else
        { 
           $response = array(
            'status' => 400,
            'message' => 'Not Added try again',
            'data' => ''
             );
           $this->response($response, REST_Controller::HTTP_OK);
        }
       } catch (Exception $ex) {
             throw new Exception('Parada controller_name : Error in new parada function - ' . $ex);
       }  
 }  
  /*
  * Editing a parada
 */
  function edit_post($parada_id)
 {   
  try{
   $data['parada'] = $this->Parada_model->get_parada($parada_id);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['parada']['parada_id']))
      {
        $params = array(
           'estado_id'=> $this->input->post('estado_id'),
           'parada_nombre'=> $this->input->post('parada_nombre'),
           'parada_ubicacion'=> $this->input->post('parada_ubicacion'),
           'parada_latitud'=> $this->input->post('parada_latitud'),
           'parada_longitud'=> $this->input->post('parada_longitud'),
        );
          if(isset($_POST) && count($_POST) > 0)     
           {  
           $this->Parada_model->update_parada($parada_id,$params);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Updated',
            'data' => $parada_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
           }
           else
          {
           $response = array(
            'status' => 400,
            'message' => 'Not Updated Try again',
            'data' => $parada_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
          }
  }
       } catch (Exception $ex) {
             throw new Exception('Parada controller_name : Error in edit_post function - ' . $ex);
        }  
} 
/*
  * Deleting parada
  */
  function remove_post($parada_id)
   {
  try{
      $parada = $this->Parada_model->get_parada($parada_id);
  // check if the parada exists before trying to delete it
       if(isset($parada['parada_id']))
       {
         $this->Parada_model->delete_parada($parada_id);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Removed',
            'data' => $parada_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
       }
       else
           $response = array(
            'status' => 400,
            'message' => 'Not Updated Try again',
            'data' => $parada_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
       } catch (Exception $ex) {
             throw new Exception('Parada controller_name : Error in remove_post function - ' . $ex);
        }  
  }
 }
